import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { requireTripManagementAccess, recordTripManagementAudit } from "@/lib/trip-management-access.server";

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function database(){const {supabaseAdmin}=await import("@/integrations/supabase/client.server");return supabaseAdmin as any}
function bookingMailEnabled(){return process.env.TRIP_BOOKING_MAIL_ENABLED==="true"}
function requireBookingMailEnabled(){if(!bookingMailEnabled())throw new Error("BOOKING_MAIL_TEMPORARILY_UNAVAILABLE")}

export const getTripBookingMail=createServerFn({method:"GET"}).middleware([requireSupabaseAuth])
 .validator((x:{tripId:string})=>x).handler(async({data,context})=>{if(!uuid.test(data.tripId))throw new Error("INVALID_TRIP");const db=await database();await requireTripManagementAccess(db,context.userId,data.tripId,"trips_plan");if(!bookingMailEnabled())return{available:false,address:null,drafts:[]};
  const {data:address,error}=await db.from("trip_booking_mail_addresses").select("id,address,allowed_senders,retention_days,active,revoked_at,mailbox_id,corporate_mailboxes(provisioning_status,provisioning_error_code)").eq("trip_uuid",data.tripId).maybeSingle();if(error)throw new Error("BOOKING_MAIL_UNAVAILABLE");
  const drafts=address?await db.from("trip_booking_mail_drafts").select("id,sender_address,subject,booking_type,status,parsed_data,confidence,created_at").eq("trip_uuid",data.tripId).order("created_at",{ascending:false}).limit(50):{data:[],error:null};if(drafts.error)throw new Error("BOOKING_MAIL_UNAVAILABLE");return{available:true,address,drafts:drafts.data??[]};});

export const createTripBookingMail=createServerFn({method:"POST"}).middleware([requireSupabaseAuth])
 .validator((x:{tripId:string;retentionDays:number;allowedSenders:string[]})=>x).handler(async({data,context})=>{requireBookingMailEnabled();if(!uuid.test(data.tripId))throw new Error("INVALID_TRIP");const db=await database();const access=await requireTripManagementAccess(db,context.userId,data.tripId,"trips_plan");
  const retention=Math.min(365,Math.max(1,Math.floor(data.retentionDays||30)));const senders=[...new Set(data.allowedSenders.map(x=>x.trim().toLowerCase()).filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))].slice(0,30);
  const existing=await db.from("trip_booking_mail_addresses").select("id,mailbox_id").eq("trip_uuid",data.tripId).maybeSingle();if(existing.data){const updated=await db.from("trip_booking_mail_addresses").update({allowed_senders:senders,retention_days:retention,active:true,revoked_at:null,updated_at:new Date().toISOString()}).eq("id",existing.data.id);await db.from("corporate_mailboxes").update({active:true,provisioning_status:"pending",provisioning_requested_at:new Date().toISOString()}).eq("id",existing.data.mailbox_id);if(updated.error)throw new Error("BOOKING_MAIL_SAVE_FAILED");return{ok:true};}
  const {randomBytes}=await import("node:crypto");const local=randomBytes(6).toString("hex"),address=`trip.${local}@globetrotr.nl`,password=randomBytes(32).toString("base64url");const {encryptSecret}=await import("@/lib/secret-crypto.server");
  const mailbox=await db.from("corporate_mailboxes").insert({address,display_name:"GlobeTrotr trip booking",mailbox_type:"automated",signature_text:"",active:true,hosting_mode:"self_hosted",provisioning_status:"pending",provisioning_requested_at:new Date().toISOString(),imap_host:"mail.globetrotr.nl",imap_port:993,imap_secure:true,imap_username:address,imap_password_ciphertext:encryptSecret(password),credentials_updated_at:new Date().toISOString()}).select("id").single();if(mailbox.error)throw new Error("BOOKING_MAILBOX_CREATE_FAILED");
  const linked=await db.from("trip_booking_mail_addresses").insert({trip_uuid:data.tripId,workspace_uuid:access.workspaceId,mailbox_id:mailbox.data.id,address,allowed_senders:senders,retention_days:retention,created_by:context.userId});if(linked.error){await db.from("corporate_mailboxes").delete().eq("id",mailbox.data.id);throw new Error("BOOKING_MAIL_CREATE_FAILED");}await recordTripManagementAudit(db,access,context.userId,"trip.booking_mail.create","trip",data.tripId);return{ok:true};});

export const reviewTripBookingMail=createServerFn({method:"POST"}).middleware([requireSupabaseAuth])
 .validator((x:{tripId:string;draftId:string;action:"accepted"|"rejected"})=>x).handler(async({data,context})=>{requireBookingMailEnabled();if(!uuid.test(data.tripId)||!uuid.test(data.draftId))throw new Error("INVALID_BOOKING_DRAFT");const db=await database();const access=await requireTripManagementAccess(db,context.userId,data.tripId,"trips_plan");const result=await db.from("trip_booking_mail_drafts").update({status:data.action,reviewed_by:context.userId,reviewed_at:new Date().toISOString()}).eq("id",data.draftId).eq("trip_uuid",data.tripId).eq("status","pending").select("id").maybeSingle();if(result.error||!result.data)throw new Error("BOOKING_DRAFT_REVIEW_FAILED");await recordTripManagementAudit(db,access,context.userId,`trip.booking_mail.${data.action}`,"booking_mail_draft",data.draftId);return{ok:true};});

export const revokeTripBookingMail=createServerFn({method:"POST"}).middleware([requireSupabaseAuth])
 .validator((x:{tripId:string})=>x).handler(async({data,context})=>{requireBookingMailEnabled();if(!uuid.test(data.tripId))throw new Error("INVALID_TRIP");const db=await database();const access=await requireTripManagementAccess(db,context.userId,data.tripId,"trips_plan");const current=await db.from("trip_booking_mail_addresses").select("id,mailbox_id").eq("trip_uuid",data.tripId).eq("active",true).maybeSingle();if(current.error||!current.data)throw new Error("BOOKING_MAIL_NOT_ACTIVE");const now=new Date().toISOString();const stopped=await db.from("trip_booking_mail_addresses").update({active:false,revoked_at:now,updated_at:now}).eq("id",current.data.id);const mailbox=await db.from("corporate_mailboxes").update({active:false,provisioning_status:"pending",provisioning_requested_at:now,updated_at:now}).eq("id",current.data.mailbox_id);if(stopped.error||mailbox.error)throw new Error("BOOKING_MAIL_REVOKE_FAILED");await recordTripManagementAudit(db,access,context.userId,"trip.booking_mail.revoke","trip",data.tripId);return{ok:true};});
