import {createServerFn} from "@tanstack/react-start";
import {requireSupabaseAuth} from "@/integrations/supabase/auth-middleware";
export const getPublicFeatureFlags=createServerFn({method:"GET"}).handler(async()=>{const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const{data,error}=await(supabaseAdmin as any).from("platform_feature_flags").select("flag_key,enabled").eq("audience","all");if(error)throw new Error("PUBLIC_FLAGS_UNAVAILABLE");return Object.fromEntries((data??[]).map((x:any)=>[x.flag_key,Boolean(x.enabled)])) as Record<string,boolean>;});
async function access(userId:string){const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const db=supabaseAdmin as any;const[{data:user},{data:admin}]=await Promise.all([db.auth.admin.getUserById(userId),db.from("platform_admins").select("role,permissions").eq("user_id",userId).eq("active",true).maybeSingle()]);if(user.user?.app_metadata?.corporate_admin!==true||!admin||(admin.role!=="owner"&&admin.permissions?.operations!==true))throw new Error("FORBIDDEN");return db;}
async function audit(db:any,actor:string,action:string,target:string,id:string|null,details:Record<string,unknown>){await db.from("platform_admin_audit_log").insert({actor_user_id:actor,action,target_type:target,target_id:id,result:"success",details});}
export const getCorporateGovernance=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=await access(context.userId);const[flags,requests,incidents,maintenance]=await Promise.all([db.from("platform_feature_flags").select("*").order("flag_key"),db.from("privacy_requests").select("*").order("due_at"),db.from("platform_incidents").select("*").order("started_at",{ascending:false}).limit(100),db.from("platform_maintenance").select("*").eq("singleton",true).maybeSingle()]);if(flags.error||requests.error||incidents.error||maintenance.error)throw new Error("GOVERNANCE_UNAVAILABLE");return{flags:flags.data??[],requests:requests.data??[],incidents:incidents.data??[],maintenance:maintenance.data};});
export const saveFeatureFlag=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((x:{key:string;enabled:boolean;audience:"internal"|"beta"|"all";reason:string})=>x).handler(async({data,context})=>{if(!/^[a-z][a-z0-9_.-]{2,79}$/.test(data.key)||data.reason.trim().length<10)throw new Error("INVALID_FLAG_CHANGE");const db=await access(context.userId);const{data:row,error}=await db.from("platform_feature_flags").update({enabled:data.enabled,audience:data.audience,updated_by:context.userId,updated_at:new Date().toISOString()}).eq("flag_key",data.key).select("flag_key").maybeSingle();if(error||!row)throw new Error("FLAG_SAVE_FAILED");await audit(db,context.userId,"platform.feature_flag.update","feature_flag",data.key,{enabled:data.enabled,audience:data.audience,reason:data.reason.trim()});return{ok:true};});
export const savePrivacyRequest=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((x:{id?:string;email:string;type:string;status:string;notes:string;response?:string})=>x).handler(async({data,context})=>{const db=await access(context.userId);const response=data.response?.trim()||null;if(response&&response.length>5000)throw new Error("INVALID_PRIVACY_RESPONSE");const payload={requester_email:data.email.trim().toLowerCase(),request_type:data.type,status:data.status,notes:data.notes.trim()||null,response_text:response,responded_at:response?new Date().toISOString():null,closed_at:["completed","rejected"].includes(data.status)?new Date().toISOString():null,updated_by:context.userId,updated_at:new Date().toISOString()};const q=data.id?db.from("privacy_requests").update(payload).eq("id",data.id):db.from("privacy_requests").insert(payload);const{data:row,error}=await q.select("id,user_id").single();if(error)throw new Error("PRIVACY_REQUEST_SAVE_FAILED");if(response&&row.user_id)await db.from("notifications").insert({user_id:row.user_id,kind:"account",title:"Antwoord op je privacyverzoek / Response to your privacy request",body:response,event_key:`privacy-response:${row.id}`,link:"/account"});await audit(db,context.userId,data.id?"privacy.request.update":"privacy.request.create","privacy_request",row.id,{status:data.status,type:data.type,responded:Boolean(response)});return{ok:true};});
export const setPrivacyRequestArchived=createServerFn({method:"POST"})
  .middleware([requireSupabaseAuth])
  .validator((input:{id:string;archived:boolean})=>input)
  .handler(async({data,context})=>{
    if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(data.id))
      throw new Error("INVALID_PRIVACY_REQUEST");
    const db=await access(context.userId);
    const{data:request,error:readError}=await db.from("privacy_requests")
      .select("id,status,archived_at").eq("id",data.id).maybeSingle();
    if(readError||!request)throw new Error("PRIVACY_REQUEST_NOT_FOUND");
    if(data.archived&&!['completed','rejected'].includes(request.status))
      throw new Error("PRIVACY_REQUEST_STILL_OPEN");
    if(Boolean(request.archived_at)===data.archived)return{ok:true};
    let update=db.from("privacy_requests").update({
      archived_at:data.archived?new Date().toISOString():null,
      updated_by:context.userId,
      updated_at:new Date().toISOString(),
    }).eq("id",data.id);
    if(data.archived)update=update.in("status",["completed","rejected"]);
    const{data:updated,error}=await update.select("id").maybeSingle();
    if(error||!updated)throw new Error("PRIVACY_ARCHIVE_FAILED");
    await audit(db,context.userId,data.archived?"privacy.request.archive":"privacy.request.restore",
      "privacy_request",data.id,{status:request.status});
    return{ok:true};
  });
export const saveIncident=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((x:{id?:string;title:string;severity:string;status:string;summary:string})=>x).handler(async({data,context})=>{const db=await access(context.userId);const payload={title:data.title.trim(),severity:data.severity,status:data.status,summary:data.summary.trim(),resolved_at:data.status==="resolved"?new Date().toISOString():null,updated_by:context.userId,updated_at:new Date().toISOString()};const q=data.id?db.from("platform_incidents").update(payload).eq("id",data.id):db.from("platform_incidents").insert(payload);const{data:row,error}=await q.select("id").single();if(error)throw new Error("INCIDENT_SAVE_FAILED");await audit(db,context.userId,data.id?"platform.incident.update":"platform.incident.create","incident",row.id,{status:data.status,severity:data.severity});return{ok:true};});

export const saveMaintenance=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((x:{active:boolean;reasonNl:string;reasonEn:string;startsAt:string|null;endsAt:string|null;reason:string})=>x).handler(async({data,context})=>{if(data.reason.trim().length<10||data.reasonNl.trim().length<10||data.reasonEn.trim().length<10)throw new Error("INVALID_MAINTENANCE" );const db=await access(context.userId);const payload={active:data.active,reason_nl:data.reasonNl.trim(),reason_en:data.reasonEn.trim(),starts_at:data.startsAt||null,ends_at:data.endsAt||null,updated_by:context.userId,updated_at:new Date().toISOString()};const{error}=await db.from("platform_maintenance").update(payload).eq("singleton",true);if(error)throw new Error("MAINTENANCE_SAVE_FAILED");await audit(db,context.userId,"platform.maintenance.update","maintenance",null,{active:data.active,reason:data.reason.trim(),endsAt:data.endsAt});return{ok:true};});
