import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

async function dbFor(userId:string,capability?:string){const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const db=supabaseAdmin as any;const[{data:user},{data:admin}]=await Promise.all([db.auth.admin.getUserById(userId),db.from("platform_admins").select("role,permissions").eq("user_id",userId).eq("active",true).maybeSingle()]);if(user.user?.app_metadata?.corporate_admin!==true||!admin||(capability&&admin.role!=="owner"&&admin.permissions?.[capability]!==true))throw new Error("FORBIDDEN");return db;}
async function log(db:any,actor:string,action:string,target:string|null,details:Record<string,unknown>={}){await db.from("platform_admin_audit_log").insert({actor_user_id:actor,action,target_type:"business_operations",target_id:target,result:"success",details});}
const addressPattern=/^[a-z0-9][a-z0-9._-]*@globetrotr\.nl$/;
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
async function staffDb(userId:string){return dbFor(userId,"mail");}
async function mailboxPermission(db:any,userId:string,mailboxId:string){const{data:mailbox}=await db.from("corporate_mailboxes").select("id,address,display_name,owner_user_id,signature_text,sync_status,active").eq("id",mailboxId).eq("active",true).maybeSingle();if(!mailbox)throw new Error("MAILBOX_NOT_FOUND");if(mailbox.owner_user_id===userId)return{mailbox,permission:"manage"};const{data:member}=await db.from("corporate_mailbox_members").select("permission").eq("mailbox_id",mailboxId).eq("user_id",userId).maybeSingle();if(!member)throw new Error("FORBIDDEN");return{mailbox,permission:member.permission as "read"|"reply"|"manage"};}

export const getCorporateBusinessData=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=await dbFor(context.userId,"mail");const[m,mm,p,a]=await Promise.all([db.from("corporate_mailboxes").select("*").order("address"),db.from("corporate_mailbox_members").select("mailbox_id,user_id,permission"),db.from("profiles").select("id,display_name,email"),db.from("platform_admins").select("user_id,role,active")]);if(m.error||mm.error||p.error||a.error)throw new Error("BUSINESS_DATA_UNAVAILABLE");const profiles=new Map((p.data??[]).map((row:any)=>[row.id,row]));return{mailboxes:m.data??[],mailboxMembers:mm.data??[],people:(a.data??[]).filter((x:any)=>x.active).map((x:any)=>{const profile:any=profiles.get(x.user_id);return{id:x.user_id,name:profile?.display_name||profile?.email||x.user_id,email:profile?.email,role:x.role}})};});

export const saveCorporateMailbox=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{id?:string;address:string;displayName:string;mailboxType:"personal"|"shared";ownerUserId?:string;signatureText:string;inboundSecretRef:string;outboundSecretRef:string;active:boolean})=>input).handler(async({data,context})=>{const db=await dbFor(context.userId,"mail");const address=data.address.trim().toLowerCase();if(!addressPattern.test(address)||data.displayName.trim().length<2||data.signatureText.length>2000)throw new Error("INVALID_MAILBOX");if(data.mailboxType==="personal"&&!data.ownerUserId)throw new Error("MAILBOX_OWNER_REQUIRED");const row={address,display_name:data.displayName.trim(),mailbox_type:data.mailboxType,owner_user_id:data.mailboxType==="personal"?data.ownerUserId:null,signature_text:data.signatureText.trim()||null,inbound_secret_ref:data.inboundSecretRef.trim()||null,outbound_secret_ref:data.outboundSecretRef.trim()||null,active:data.active,updated_at:new Date().toISOString()};const q=data.id?db.from("corporate_mailboxes").update(row).eq("id",data.id):db.from("corporate_mailboxes").insert(row);const{data:saved,error}=await q.select("id").single();if(error)throw new Error("MAILBOX_SAVE_FAILED");await log(db,context.userId,"platform.mailbox.save",saved.id,{address,mailboxType:data.mailboxType});return{ok:true,id:saved.id};});

export const setCorporateMailboxMember=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{mailboxId:string;userId:string;permission:"none"|"read"|"reply"|"manage"})=>input).handler(async({data,context})=>{const db=await dbFor(context.userId,"mail");const{error}=data.permission==="none"?await db.from("corporate_mailbox_members").delete().eq("mailbox_id",data.mailboxId).eq("user_id",data.userId):await db.from("corporate_mailbox_members").upsert({mailbox_id:data.mailboxId,user_id:data.userId,permission:data.permission},{onConflict:"mailbox_id,user_id"});if(error)throw new Error("MAILBOX_PERMISSION_FAILED");await log(db,context.userId,"platform.mailbox.permission",data.mailboxId,{userId:data.userId,permission:data.permission});return{ok:true};});

export const getMyCorporateMail=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).validator((input?:{mailboxId?:string})=>input??{}).handler(async({data,context})=>{const db=await staffDb(context.userId);const[{data:owned},{data:members}]=await Promise.all([db.from("corporate_mailboxes").select("id,address,display_name,owner_user_id,signature_text,sync_status").eq("owner_user_id",context.userId).eq("active",true),db.from("corporate_mailbox_members").select("permission,corporate_mailboxes(id,address,display_name,owner_user_id,signature_text,sync_status)").eq("user_id",context.userId)]);const access=[...(owned??[]).map((m:any)=>({...m,permission:"manage"})),...(members??[]).map((row:any)=>({...row.corporate_mailboxes,permission:row.permission}))].filter((m:any)=>m.id);const unique=Array.from(new Map(access.map((m:any)=>[m.id,m])).values()) as any[];const selectedId=data.mailboxId&&unique.some(m=>m.id===data.mailboxId)?data.mailboxId:unique[0]?.id;if(!selectedId)return{mailboxes:[],messages:[],outbox:[],selected:null};const selected=unique.find(m=>m.id===selectedId);const[messages,outbox]=await Promise.all([db.from("corporate_mail_messages").select("id,direction,sender_address,recipient_addresses,subject,preview_text,received_at,read_at,archived_at").eq("mailbox_id",selectedId).is("archived_at",null).order("received_at",{ascending:false}).limit(100),db.from("corporate_mail_send_queue").select("id,recipient_addresses,cc_addresses,subject,status,attempts,sent_at,last_error_code,created_at").eq("mailbox_id",selectedId).order("created_at",{ascending:false}).limit(100)]);if(messages.error||outbox.error)throw new Error("MAIL_LOAD_FAILED");return{mailboxes:unique,messages:messages.data??[],outbox:outbox.data??[],selected};});

export const queueCorporateMail=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{mailboxId:string;recipients:string[];cc:string[];subject:string;body:string;replyToId?:string})=>input).handler(async({data,context})=>{const db=await staffDb(context.userId);const access=await mailboxPermission(db,context.userId,data.mailboxId);if(!["reply","manage"].includes(access.permission))throw new Error("FORBIDDEN");const recipients=[...new Set(data.recipients.map(v=>v.trim().toLowerCase()).filter(Boolean))];const cc=[...new Set(data.cc.map(v=>v.trim().toLowerCase()).filter(Boolean))];if(!recipients.length||recipients.length>25||cc.length>25||![...recipients,...cc].every(v=>emailPattern.test(v))||!data.subject.trim()||!data.body.trim())throw new Error("INVALID_MESSAGE");const body=`${data.body.trim()}${access.mailbox.signature_text?`\n\n${access.mailbox.signature_text}`:""}`;const{data:config}=await db.from("email_delivery_config").select("mode").eq("id",true).maybeSingle();const status=config?.mode==="live"?"pending":"held";const{data:queued,error}=await db.from("corporate_mail_send_queue").insert({mailbox_id:data.mailboxId,created_by:context.userId,in_reply_to_message_id:data.replyToId??null,recipient_addresses:recipients,cc_addresses:cc,subject:data.subject.trim(),body_text:body,status}).select("id").single();if(error)throw new Error("MAIL_QUEUE_FAILED");await log(db,context.userId,"platform.mail.queue",queued.id,{mailboxId:data.mailboxId,recipientCount:recipients.length,reply:Boolean(data.replyToId),status});return{ok:true,id:queued.id,status};});

export const updateMyCorporateSignature=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{mailboxId:string;signatureText:string})=>input).handler(async({data,context})=>{const db=await staffDb(context.userId);const access=await mailboxPermission(db,context.userId,data.mailboxId);if(access.mailbox.owner_user_id!==context.userId||data.signatureText.length>2000)throw new Error("FORBIDDEN");const{error}=await db.from("corporate_mailboxes").update({signature_text:data.signatureText.trim()||null,updated_at:new Date().toISOString()}).eq("id",data.mailboxId).eq("owner_user_id",context.userId);if(error)throw new Error("SIGNATURE_UPDATE_FAILED");await log(db,context.userId,"platform.mail.signature",data.mailboxId);return{ok:true};});

export const updateCorporateMailMessage=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{mailboxId:string;messageId:string;action:"read"|"unread"|"archive"})=>input).handler(async({data,context})=>{const db=await staffDb(context.userId);await mailboxPermission(db,context.userId,data.mailboxId);const changes=data.action==="archive"?{archived_at:new Date().toISOString()}:data.action==="read"?{read_at:new Date().toISOString()}:{read_at:null};const{error}=await db.from("corporate_mail_messages").update(changes).eq("id",data.messageId).eq("mailbox_id",data.mailboxId);if(error)throw new Error("MAIL_UPDATE_FAILED");return{ok:true};});

export const getCorporateFinanceData=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).validator((input?:{days?:number})=>input??{}).handler(async({data,context})=>{const db=await dbFor(context.userId,"finance");const days=Math.min(366,Math.max(7,Math.floor(data.days??30)));const since=new Date(Date.now()-days*86400000).toISOString();const[invoices,subscriptions,transactions,webhooks]=await Promise.all([db.from("corporate_invoices").select("*").order("issued_at",{ascending:false}).limit(500),db.from("billing_subscriptions").select("id,plan,status,currency,recurring_total_minor,billing_interval,current_period_end,created_at"),db.from("billing_transactions").select("id,status,currency,total_minor,refunded_minor,occurred_at").gte("occurred_at",since).order("occurred_at"),db.from("billing_webhook_events").select("status").in("status",["received","processing","failed"])]);if(invoices.error||subscriptions.error||transactions.error||webhooks.error)throw new Error("FINANCE_DATA_UNAVAILABLE");const subs=subscriptions.data??[],tx=transactions.data??[];const completed=tx.filter((x:any)=>["paid","completed","refunded","partially_refunded"].includes(x.status));const revenueMinor=completed.reduce((sum:number,x:any)=>sum+Number(x.total_minor)-Number(x.refunded_minor||0),0);const refundedMinor=completed.reduce((sum:number,x:any)=>sum+Number(x.refunded_minor||0),0);const mrrMinor=subs.filter((x:any)=>["trialing","active","past_due"].includes(x.status)).reduce((sum:number,x:any)=>sum+Math.round(Number(x.recurring_total_minor)*(x.billing_interval==="year"?1/12:1)),0);const daily=new Map<string,number>();for(const x of completed){const day=String(x.occurred_at).slice(0,10);daily.set(day,(daily.get(day)??0)+Number(x.total_minor)-Number(x.refunded_minor||0))}return{days,invoices:invoices.data??[],subscriptions:subs,metrics:{mrrMinor,revenueMinor,refundedMinor,activeSubscriptions:subs.filter((x:any)=>x.status==="active").length,pastDue:subs.filter((x:any)=>x.status==="past_due").length,pendingWebhooks:(webhooks.data??[]).length},dailyRevenue:Array.from(daily,([date,totalMinor])=>({date,totalMinor}))};});

export const getCorporateStaff=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=await dbFor(context.userId,"users");const[admins,profiles,mailboxes,authUsers]=await Promise.all([db.from("platform_admins").select("user_id,role,active,job_title,permissions,created_at,updated_at,deactivated_at").order("created_at"),db.from("profiles").select("id,display_name,email"),db.from("corporate_mailboxes").select("id,address,owner_user_id,mailbox_type,active"),db.auth.admin.listUsers({page:1,perPage:1000})]);if(admins.error||profiles.error||mailboxes.error||authUsers.error)throw new Error("STAFF_DATA_UNAVAILABLE");const profilesById=new Map((profiles.data??[]).map((p:any)=>[p.id,p]));return{staff:(admins.data??[]).map((a:any)=>{const p:any=profilesById.get(a.user_id),u=authUsers.data.users.find((x:any)=>x.id===a.user_id);return{...a,name:p?.display_name||u?.user_metadata?.full_name||"",accountEmail:p?.email||u?.email||"",mailbox:(mailboxes.data??[]).find((m:any)=>m.owner_user_id===a.user_id&&m.mailbox_type==="personal")??null}}),candidates:authUsers.data.users.map((u:any)=>{const p:any=profilesById.get(u.id);return{id:u.id,name:p?.display_name||u.user_metadata?.full_name||"",email:p?.email||u.email||""}}),sharedMailboxes:(mailboxes.data??[]).filter((m:any)=>m.mailbox_type==="shared")};});

function suggestedMailbox(name:string){const parts=name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9\s-]/g,"").trim().split(/\s+/).filter(Boolean);if(parts.length<2)return"";return`${parts[0][0]}.${parts.at(-1)!.replace(/-/g,"")}@globetrotr.nl`;}
export const suggestCorporateMailbox=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{name:string})=>input).handler(async({data,context})=>{await dbFor(context.userId,"users");return{address:suggestedMailbox(data.name)}});

export const saveCorporateStaff=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{userId:string;role:"owner"|"admin"|"support";jobTitle:string;active:boolean;permissions:Record<string,boolean>;mailboxAddress:string;reason:string})=>input).handler(async({data,context})=>{const db=await dbFor(context.userId);const{data:actor}=await db.from("platform_admins").select("role").eq("user_id",context.userId).eq("active",true).single();if(actor?.role!=="owner")throw new Error("OWNER_REQUIRED");if(!uuid.test(data.userId)||data.reason.trim().length<10||data.jobTitle.length>100||data.mailboxAddress&&!addressPattern.test(data.mailboxAddress.trim().toLowerCase()))throw new Error("INVALID_STAFF");if(data.userId===context.userId&&!data.active)throw new Error("CANNOT_DEACTIVATE_SELF");if(!data.active){const{count}=await db.from("platform_admins").select("user_id",{count:"exact",head:true}).eq("role","owner").eq("active",true);const{data:target}=await db.from("platform_admins").select("role").eq("user_id",data.userId).maybeSingle();if(target?.role==="owner"&&(count??0)<=1)throw new Error("LAST_OWNER");}const allowed=["users","agencies","finance","mail","operations","issues"];const permissions=Object.fromEntries(allowed.map(k=>[k,data.role==="owner"?true:Boolean(data.permissions[k])]));const row={user_id:data.userId,role:data.role,job_title:data.jobTitle.trim()||null,permissions,active:data.active,updated_at:new Date().toISOString(),deactivated_at:data.active?null:new Date().toISOString(),created_by:context.userId};const{error}=await db.from("platform_admins").upsert(row,{onConflict:"user_id"});if(error)throw new Error("STAFF_SAVE_FAILED");const user=await db.auth.admin.getUserById(data.userId);if(!user.data.user)throw new Error("USER_NOT_FOUND");await db.auth.admin.updateUserById(data.userId,{app_metadata:{...user.data.user.app_metadata,corporate_admin:data.active}});if(data.mailboxAddress){const address=data.mailboxAddress.trim().toLowerCase();const{error:mailError}=await db.from("corporate_mailboxes").upsert({address,display_name:user.data.user.user_metadata?.full_name||address.split("@")[0],mailbox_type:"personal",owner_user_id:data.userId,active:data.active,updated_at:new Date().toISOString()},{onConflict:"address"});if(mailError)throw new Error("STAFF_MAILBOX_FAILED");}else if(!data.active)await db.from("corporate_mailboxes").update({active:false,updated_at:new Date().toISOString()}).eq("owner_user_id",data.userId).eq("mailbox_type","personal");await log(db,context.userId,"platform.staff.save",data.userId,{role:data.role,active:data.active,permissions,reason:data.reason.trim()});return{ok:true,requiresRelogin:true};});

export const getMyCorporateCapabilities=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const db=await dbFor(context.userId);const{data}=await db.from("platform_admins").select("role,job_title,permissions").eq("user_id",context.userId).eq("active",true).single();const all={users:true,agencies:true,finance:true,mail:true,operations:true,issues:true},none={users:false,agencies:false,finance:false,mail:false,operations:false,issues:false};return{role:data.role,jobTitle:data.job_title,permissions:data.role==="owner"?all:{...none,...data.permissions}};});

export const getCorporateStaffActivity=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).validator((input:{userId:string})=>input).handler(async({data,context})=>{
  if(!uuid.test(data.userId))throw new Error("INVALID_USER");
  const db=await dbFor(context.userId,"users");
  const{data:entries,error}=await db.from("platform_admin_audit_log").select("id,actor_user_id,action,result,details,created_at").eq("target_id",data.userId).order("created_at",{ascending:false}).limit(50);
  if(error)throw new Error("STAFF_ACTIVITY_UNAVAILABLE");
  return entries??[];
});
