export type OfflineJournalEntry={id:string;author_id:string;entry_date:string;title:string;body:string;location_name:string|null;rating:number|null;visibility:"private"|"members"|"public";photo_paths:string[];photo_captions:Record<string,string>;photo_sizes?:Record<string,number>;updated_at?:string};
export type JournalQueueItem={id:string;tripId:string;kind:"create"|"update"|"delete";entry:OfflineJournalEntry;files?:File[];createdAt:string};
const dbName="globetrotr-journal-v1";
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(dbName,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("snapshots"))db.createObjectStore("snapshots",{keyPath:"tripId"});if(!db.objectStoreNames.contains("photos"))db.createObjectStore("photos",{keyPath:"key"});if(!db.objectStoreNames.contains("queue"))db.createObjectStore("queue",{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function store(name:string,mode:IDBTransactionMode="readonly"){const db=await openDb();return db.transaction(name,mode).objectStore(name)}
function request<T>(value:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{value.onsuccess=()=>resolve(value.result);value.onerror=()=>reject(value.error)})}
export async function saveJournalSnapshot(tripId:string,entries:OfflineJournalEntry[]){await request((await store("snapshots","readwrite")).put({tripId,entries,savedAt:new Date().toISOString()}))}
export async function loadJournalSnapshot(tripId:string){return request<any>((await store("snapshots")).get(tripId)) as Promise<{tripId:string;entries:OfflineJournalEntry[];savedAt:string}|undefined>}
export async function saveOfflinePhoto(tripId:string,path:string,url:string){const response=await fetch(url);if(!response.ok)throw new Error("PHOTO_DOWNLOAD_FAILED");const blob=await response.blob();await request((await store("photos","readwrite")).put({key:tripId+":"+path,tripId,path,blob,size:blob.size}));return blob.size}
export async function loadOfflinePhoto(tripId:string,path:string){const row=await request<any>((await store("photos")).get(tripId+":"+path));return row?.blob as Blob|undefined}
export async function pruneOfflinePhotos(tripId:string,keepPaths:string[]){const rows=await request<any[]>((await store("photos")).getAll());const keep=new Set(keepPaths);for(const row of rows)if(row.tripId===tripId&&!keep.has(row.path))await request((await store("photos","readwrite")).delete(row.key))}
export async function queueJournalChange(item:Omit<JournalQueueItem,"id"|"createdAt">){const row={...item,id:crypto.randomUUID(),createdAt:new Date().toISOString()};await request((await store("queue","readwrite")).put(row));return row}
export async function journalQueue(tripId:string){const rows=await request<any[]>((await store("queue")).getAll());return rows.filter(row=>row.tripId===tripId) as JournalQueueItem[]}
export async function removeJournalQueueItem(id:string){await request((await store("queue","readwrite")).delete(id))}
export async function journalOfflineUsage(tripId:string){const photos=await request<any[]>((await store("photos")).getAll());const snapshot=await loadJournalSnapshot(tripId);return photos.filter(row=>row.tripId===tripId).reduce((sum,row)=>sum+(row.size||0),0)+new TextEncoder().encode(JSON.stringify(snapshot??{})).byteLength}
export async function clearJournalOfflineTrip(tripId:string){const photos=await request<any[]>((await store("photos")).getAll());const queued=await request<any[]>((await store("queue")).getAll());for(const row of photos)if(row.tripId===tripId)await request((await store("photos","readwrite")).delete(row.key));for(const row of queued)if(row.tripId===tripId)await request((await store("queue","readwrite")).delete(row.id));await request((await store("snapshots","readwrite")).delete(tripId))}
export async function clearOfflineJournal(){if(typeof indexedDB==="undefined")return;await new Promise<void>((resolve,reject)=>{const operation=indexedDB.deleteDatabase(dbName);operation.onsuccess=()=>resolve();operation.onerror=()=>reject(operation.error);operation.onblocked=()=>resolve()})}
