import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

export type PublicTestimonial = { id:string; authorName:string; authorContextNl:string; authorContextEn:string; quoteNl:string; quoteEn:string; rating:number|null };

async function db() { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); return supabaseAdmin as any; }
async function adminDb(userId:string) { const client=await db(); const [user,admin]=await Promise.all([client.auth.admin.getUserById(userId),client.from("platform_admins").select("role,permissions").eq("user_id",userId).eq("active",true).maybeSingle()]); if(user.error||user.data.user?.app_metadata?.corporate_admin!==true||!admin.data||(admin.data.role!=="owner"&&admin.data.permissions?.issues!==true&&admin.data.permissions?.operations!==true))throw new Error("FORBIDDEN"); return client; }
async function audit(client:any,userId:string,action:string,id:string|null,details:Record<string,unknown>={}) { await client.from("platform_admin_audit_log").insert({actor_user_id:userId,action,target_type:"testimonial",target_id:id,result:"success",details}); }

export const listPublicTestimonials=createServerFn({method:"GET"}).handler(async()=>{const client=await db();const{data,error}=await client.rpc("list_public_testimonials");if(error)throw new Error("TESTIMONIALS_UNAVAILABLE");return (data??[]) as PublicTestimonial[];});
export const listTestimonials=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const client=await adminDb(context.userId);const{data,error}=await client.from("testimonials").select("*").order("position").order("created_at",{ascending:false});if(error)throw error;return data??[];});
export const saveTestimonial=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{id?:string;authorName:string;authorContextNl:string;authorContextEn:string;quoteNl:string;quoteEn:string;rating:number|null;position:number;published:boolean})=>input).handler(async({data,context})=>{const name=data.authorName.trim(),quoteNl=data.quoteNl.trim(),quoteEn=data.quoteEn.trim();if(name.length<2||name.length>80||quoteNl.length<20||quoteNl.length>600||(quoteEn.length>0&&quoteEn.length<20)||quoteEn.length>600||!Number.isInteger(data.position)||data.position<0||data.position>10000||(data.rating!==null&&(!Number.isInteger(data.rating)||data.rating<1||data.rating>5)))throw new Error("INVALID_TESTIMONIAL");const client=await adminDb(context.userId);const row={author_name:name,author_context_nl:data.authorContextNl.trim()||null,author_context_en:data.authorContextEn.trim()||null,quote_nl:quoteNl,quote_en:quoteEn||null,rating:data.rating,position:data.position,published:data.published,updated_by:context.userId,updated_at:new Date().toISOString()};const query=data.id?client.from("testimonials").update(row).eq("id",data.id):client.from("testimonials").insert(row);const{data:saved,error}=await query.select("id").single();if(error)throw new Error(error.code==="42501"?"FORBIDDEN":"TESTIMONIAL_SAVE_FAILED");await audit(client,context.userId,data.id?"testimonial.update":"testimonial.create",saved.id,{published:data.published});return{ok:true,id:saved.id};});
export const archiveTestimonial=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{id:string;archived:boolean})=>input).handler(async({data,context})=>{const client=await adminDb(context.userId);const changes:any={archived_at:data.archived?new Date().toISOString():null,updated_by:context.userId,updated_at:new Date().toISOString()};if(data.archived)changes.published=false;const{error}=await client.from("testimonials").update(changes).eq("id",data.id);if(error)throw error;await audit(client,context.userId,data.archived?"testimonial.archive":"testimonial.restore",data.id);return{ok:true};});
