import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Compass, Heart, MapPinned, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/lib/locale";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "Over GlobeTrotr — Van reischaos naar voorpret" },
  { name: "description", content: "Lees waarom Domenic GlobeTrotr bouwde tijdens het plannen van een droomreis naar Zweden." },
  { property: "og:title", content: "Het verhaal achter GlobeTrotr" },
  { property: "og:description", content: "Van verspreide spreadsheets naar één rustige plek voor je hele reis." },
  { property: "og:image", content: "https://globetrotr.nl/about/domenic-founder-web.jpg" },
], links: [{ rel: "canonical", href: "https://globetrotr.nl/about" }] }), component: AboutPage });

function AboutPage() {
  const { text, locale } = useLocale();
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: "GlobeTrotr", url: "https://globetrotr.nl", founder: { "@type": "Person", name: "Domenic" }, email: "info@globetrotr.nl", address: { "@type": "PostalAddress", streetAddress: "Gedempte Oude Gracht 95", postalCode: "2011 GT", addressLocality: "Haarlem", addressCountry: "NL" } }) }} />
  <article className="pb-12">
    <header className="mx-auto grid max-w-6xl items-center gap-8 py-5 sm:py-8 lg:grid-cols-[.82fr_1.18fr] lg:gap-10 lg:py-14">
      <div className="relative mx-auto aspect-[4/5] w-full max-w-md overflow-hidden rounded-[2rem] shadow-2xl"><img src="/about/domenic-founder-web.jpg" alt={text("Domenic, oprichter van GlobeTrotr", "Domenic, founder of GlobeTrotr")} className="size-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-7 pt-28 text-white"><p className="font-display text-2xl font-semibold">Domenic</p><p className="text-sm text-white/80">{text("Oprichter van GlobeTrotr", "Founder of GlobeTrotr")}</p></div></div>
      <div><Badge variant="secondary">{text("Een persoonlijk reisverhaal", "A personal travel story")}</Badge><h1 className="mt-5 max-w-3xl font-display text-3xl font-semibold leading-tight sm:text-5xl lg:text-6xl">{text("GlobeTrotr begon niet in een vergaderzaal, maar boven een veel te grote spreadsheet.", "GlobeTrotr did not start in a boardroom, but over a spreadsheet that had grown far too large.")}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground sm:mt-6 sm:text-lg sm:leading-8">{text("Dit is het verhaal van een droomreis naar Zweden, zoekgeraakte boekingen en de overtuiging dat reisvoorpret veel eenvoudiger kan.", "This is the story of a dream trip to Sweden, lost bookings and the belief that planning a journey can be much simpler.")}</p></div>
    </header>
    <div className="mx-auto max-w-3xl space-y-8 text-[1.05rem] leading-8 text-foreground/90">
      {locale === "en-GB" ? <><p>Honestly, I am not a seasoned software developer. I was simply trying to plan an epic trip through Sweden. By day three, the excitement had been replaced by tabs, spreadsheets and notes that no one else could follow.</p><p>Flight confirmations lived somewhere in an email archive. Hotel addresses were copied into separate notes. Fuel costs had their own calculation and the group chat kept returning to the same question: who had paid for what?</p><p>The problem was not a lack of travel apps. Each app solved one small part, while the trip itself remained scattered. I wanted one calm place for the route, bookings, daily plans, packing and shared expenses.</p><p>When I could not find that place, I started building it. The first version existed for one reason: saving our own Sweden trip from administrative chaos. Every improvement since then has come from an actual journey, an actual mistake or a question from someone travelling together.</p><p>That experiment became GlobeTrotr: a shared travel dashboard for travellers, groups and agencies. It should tell you what happens next, where the booking is, what remains of the budget and who can change which part of the trip.</p></> : <><p>Eerlijk is eerlijk: ik ben geen doorgewinterde softwaredeveloper. Ik wilde gewoon een epische reis door Zweden plannen. Na drie dagen had de voorpret plaatsgemaakt voor tabbladen, spreadsheets en notities die niemand behalve ik nog begreep.</p><p>Vluchtbevestigingen stonden ergens in een e-mailarchief. Hoteladressen waren naar losse notities gekopieerd. Benzinekosten hadden een eigen berekening en in de groepsapp kwam steeds dezelfde vraag terug: wie had nou wat betaald?</p><p>Het probleem was niet dat er geen reisapps bestonden. Iedere app loste één klein onderdeel op, terwijl de reis zelf verspreid bleef. Ik wilde één rustige plek voor de route, boekingen, dagplanning, paklijst en gezamenlijke uitgaven.</p><p>Toen ik die plek niet vond, ben ik haar zelf gaan bouwen. De eerste versie had één doel: onze eigen Zwedenreis redden van administratieve chaos. Iedere verbetering daarna kwam voort uit een echte reis, een echte fout of een vraag van iemand die samen op pad ging.</p><p>Dat experiment groeide uit tot GlobeTrotr: een gedeeld reisdashboard voor reizigers, groepen en reisorganisaties. Het moet je vertellen wat er straks gebeurt, waar de boeking staat, hoeveel budget er over is en wie welk onderdeel mag aanpassen.</p></>}
      <figure className="my-12 border-y py-10"><blockquote className="font-display text-2xl font-medium leading-relaxed sm:text-3xl">“{text("Reizen hoort te gaan over vrijheid, avontuur en voorpret. Niet over formules en discussies in WhatsApp-groepen.", "Travel should be about freedom, adventure and anticipation. It should not require formulas or arguments in group chats.")}”</blockquote><figcaption className="mt-4 text-sm text-muted-foreground">— Domenic, {text("oprichter van GlobeTrotr", "founder of GlobeTrotr")}</figcaption></figure>
      <h2 className="font-display text-3xl font-semibold">{text("Van eigen hulpmiddel naar reisplatform", "From personal tool to travel platform")}</h2><p>{text("GlobeTrotr wordt onafhankelijk vanuit Nederland gebouwd. De primaire gegevensopslag blijft binnen de Europese Unie en je bepaalt zelf wat privé blijft, wie aan een reis deelneemt en wat openbaar wordt gedeeld. We publiceren onze roadmap, wijzigingen en bekende problemen omdat vertrouwen ook betekent dat je eerlijk laat zien waar je staat.", "GlobeTrotr is built independently in the Netherlands. Primary data storage remains within the European Union, while you decide what stays private, who joins a trip and what is shared publicly. We publish our roadmap, changes and known issues because trust also means being honest about where the product stands.")}</p>
    </div>
    <section className="mx-auto mt-14 grid max-w-5xl gap-8 rounded-[2rem] bg-muted/35 p-7 sm:p-10 md:grid-cols-3"><Principle icon={MapPinned} title={text("Ontstaan uit een echte reis", "Born from a real trip")} body={text("Functies beginnen bij herkenbare problemen onderweg en tijdens het plannen.", "Features begin with recognisable problems on the road and while planning.")}/><Principle icon={ShieldCheck} title={text("Privacy met keuzes", "Privacy with control")} body={text("Jij bepaalt toegang, delen en optionele koppelingen.", "You control access, sharing and optional connections.")}/><Principle icon={Heart} title={text("Open blijven verbeteren", "Keep improving openly")} body={text("Feedback, roadmap en bekende problemen blijven zichtbaar.", "Feedback, the roadmap and known issues remain visible.")}/></section>
    <footer className="mx-auto mt-14 flex max-w-3xl flex-col items-center text-center"><Compass className="size-8 text-primary"/><h2 className="mt-4 font-display text-3xl font-semibold">{text("Pak je koffers. De spreadsheets laten we thuis.", "Pack your bags. We are leaving the spreadsheets at home.")}</h2><div className="mt-6 flex w-full flex-col justify-center gap-3 sm:w-auto sm:flex-row sm:flex-wrap"><Button asChild size="lg" className="min-h-11 w-full sm:w-auto"><Link to="/demo">{text("Bekijk de demo", "View the demo")}<ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="outline" className="min-h-11 w-full sm:w-auto"><Link to="/contact">{text("Vertel wat jij mist", "Tell us what you need")}</Link></Button></div></footer>
  </article></>;
}

function Principle({ icon: Icon, title, body }: { icon: typeof MapPinned; title: string; body: string }) { return <div><Icon className="size-6 text-primary"/><h3 className="mt-4 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></div>; }
