import { createFileRoute, Link } from "@tanstack/react-router";
import { Beaker, Bug, CheckCircle2, CircleAlert, ClipboardCheck, Mail, Rocket, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
import { PUBLIC_BETA_STATUS } from "@/lib/public-changelog";

export const Route = createFileRoute("/beta-voorwaarden")({ head: () => ({ meta: [{ title: "Internationale beta — GlobeTrotr" }, { name: "description", content: "Alles over testen en deelnemen aan de GlobeTrotr-beta." }] }), component: BetaPage });

export function BetaPage() {
  const { user } = useAuth();
  const { text } = useLocale();
  const journey = [
    [ClipboardCheck, text("1. Maak een echte testreis", "1. Create a real test trip"), text("Voeg bestemmingen, datums, planning en een paar uitgaven toe.", "Add destinations, dates, itinerary items and a few expenses.")],
    [ShieldCheck, text("2. Test samenwerken en delen", "2. Test collaboration and sharing"), text("Probeer een reisrol, openbare link en PIN zonder gevoelige echte gegevens.", "Try a trip role, public link and PIN without sensitive real data.")],
    [Bug, text("3. Meld wat schuurt", "3. Report friction"), text("Noem pagina, apparaat, taal, handeling en wat je verwachtte. Een schermafbeelding helpt.", "Include page, device, language, action and expected result. A screenshot helps.")],
  ] as const;
  const testAreas = [
    text("Reis maken en instellingen bewaren", "Create a trip and save settings"),
    text("Route, kaart en dagplanning", "Route, map and daily itinerary"),
    text("Vluchten, verblijf, vervoer en activiteiten", "Flights, accommodation, transport and activities"),
    text("Uitgaven, valuta en slimme verrekening", "Expenses, currencies and smart settlement"),
    text("Paklijst, exports en openbare reispagina", "Packing list, exports and public trip page"),
    text("Mobiele weergave en Nederlands/Engels", "Mobile layout and Dutch/English"),
  ];
  return <div className="mx-auto max-w-5xl space-y-10">
    <header className="aurora overflow-hidden rounded-3xl px-6 py-12 sm:px-10 sm:py-16">
      <Badge variant="secondary" className="mb-4 gap-1.5"><Beaker className="size-3.5" /> {text("Internationale beta", "International beta")}</Badge>
      <h1 className="max-w-3xl font-display text-3xl font-semibold sm:text-5xl">{text("Help de reisplanner te bouwen die je zelf wilt meenemen", "Help build the trip planner you want to take with you")}</h1>
      <p className="mt-4 max-w-2xl text-sm leading-relaxed opacity-90 sm:text-base">{text("Test echte reissituaties, ontdek wat goed werkt en vertel ons waar je vastloopt. Je feedback bepaalt wat als volgende wordt verbeterd.", "Test real travel situations, discover what works well and tell us where you get stuck. Your feedback shapes what improves next.")}</p>
      <div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg"><Link to={user ? "/dashboard" : "/auth"}><Rocket className="size-4" /> {user ? text("Start met testen", "Start testing") : text("Beta-account maken", "Create beta account")}</Link></Button><Button asChild size="lg" variant="outline"><Link to="/updates">{text("Bekijk updates", "View updates")}</Link></Button></div>
    </header>

    <section><h2 className="font-display text-2xl font-semibold">{text("Een goede testronde in drie stappen", "A useful test round in three steps")}</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{journey.map(([Icon,title,body])=><Card key={title} className="surface"><CardContent className="p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p></CardContent></Card>)}</div></section>

    <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]">
      <Card className="surface"><CardContent className="p-6 sm:p-8"><h2 className="font-display text-xl font-semibold">{text("Wat kun je testen?", "What can you test?")}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{testAreas.map(item=><div key={item} className="flex gap-2 rounded-xl bg-muted/40 p-3 text-sm"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-primary" />{item}</div>)}</div></CardContent></Card>
      {PUBLIC_BETA_STATUS.unavailable.length > 0 ? <Card className="surface border-amber-500/25"><CardContent className="p-6"><CircleAlert className="size-6 text-amber-600" /><h2 className="mt-4 font-display text-xl font-semibold">{text("Bewust nog niet beschikbaar", "Intentionally unavailable")}</h2><ul className="mt-4 space-y-3 text-sm text-muted-foreground">{PUBLIC_BETA_STATUS.unavailable.map(item=><li key={item.nl} className="flex gap-2"><span aria-hidden>•</span>{text(item.nl,item.en)}</li>)}</ul></CardContent></Card> : <Card className="surface"><CardContent className="p-6"><CheckCircle2 className="size-6 text-primary" /><h2 className="mt-4 font-display text-xl font-semibold">{text("Geen bewuste functieblokkades", "No intentional feature blocks")}</h2><p className="mt-3 text-sm text-muted-foreground">{text("Alle functies in deze beta kunnen worden getest. Sommige koppelingen vereisen nog wel hun normale DNS- of providerinstellingen.", "All features in this beta can be tested. Some integrations still require their normal DNS or provider configuration.")}</p></CardContent></Card>}
    </section>

    <Card className="surface"><CardContent className="grid gap-6 p-6 sm:p-8 md:grid-cols-2"><div><h2 className="font-display text-xl font-semibold">{text("Test veilig en zorgvuldig", "Test safely and responsibly")}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text("GlobeTrotr is een testversie en kan veranderen of tijdelijk onderbroken zijn. Gebruik geen paspoortnummers, betaalkaartgegevens of medische informatie. Controleer tijden, prijzen, visa, verzekeringen en reserveringen altijd bij de officiële aanbieder; GlobeTrotr verkoopt geen reizen.", "GlobeTrotr is a test version and may change or be temporarily interrupted. Do not enter passport numbers, payment card details or medical information. Always verify times, prices, visas, insurance and reservations with the official provider; GlobeTrotr does not sell travel.")}</p></div><div><h2 className="font-display text-xl font-semibold">{text("Een bruikbare foutmelding", "A useful bug report")}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text("Stuur je melding via het kanaal waarmee je bent uitgenodigd. Beschrijf de laatste stappen, vermeld browser en apparaat en voeg alleen een schermafbeelding toe waarop geen privégegevens staan.", "Send your report through the channel used for your invitation. Describe the last steps, include browser and device, and only attach a screenshot that contains no private data.")}</p><p className="mt-4 flex items-center gap-2 text-sm font-medium"><Mail className="size-4 text-primary" /> {text("We bevestigen bekende problemen in de changelog.", "Known issues are acknowledged in the changelog.")}</p></div></CardContent></Card>
    <Card className="surface"><CardContent className="space-y-6 p-6 sm:p-8">
      <h2 className="font-display text-2xl font-semibold">{text("Deelnamevoorwaarden", "Participation terms")}</h2>
      <Term title={text("1. Deelname en account", "1. Participation and account")}>{text("Je moet minimaal 16 jaar zijn en juiste accountgegevens gebruiken. Houd je inloggegevens geheim en meld vermoed misbruik. De beta is persoonlijk; geef een uitnodiging of account niet door.", "You must be at least 16 and use accurate account details. Keep credentials confidential and report suspected misuse. The beta is personal; do not transfer an invitation or account.")}</Term>
      <Term title={text("2. Toegestaan gebruik", "2. Acceptable use")}>{text("Gebruik GlobeTrotr rechtmatig en respecteer de rechten en privacy van anderen. Probeer beveiliging, toegangsrechten, limieten of de werking van de dienst niet te omzeilen of verstoren. Upload geen malware, illegale inhoud of gegevens waarvoor je geen gebruiksrecht hebt.", "Use GlobeTrotr lawfully and respect others' rights and privacy. Do not attempt to bypass or disrupt security, access controls, limits or operation of the service. Do not upload malware, illegal content or data you have no right to use.")}</Term>
      <Term title={text("3. Jouw inhoud", "3. Your content")}>{text("Je houdt de rechten op je reisinhoud. Je geeft GlobeTrotr alleen de beperkte toestemming om die inhoud te hosten, verwerken, tonen en technisch kopiëren voor het leveren, beveiligen en herstellen van de dienst. Deze toestemming eindigt na verwijdering, behalve voor tijdelijke back-ups of een wettelijke bewaarplicht.", "You retain rights to your trip content. You only grant GlobeTrotr the limited permission to host, process, display and technically copy it to provide, secure and recover the service. This permission ends after deletion, except for temporary backups or a legal retention duty.")}</Term>
      <Term title={text("4. Beta, reisbeslissingen en derden", "4. Beta, travel decisions and third parties")}>{text("De beta kan fouten bevatten, wijzigen of tijdelijk niet beschikbaar zijn. Kaarten, weer, koersen, vluchtgegevens en berekeningen kunnen onjuist of vertraagd zijn. Controleer essentiële reisinformatie bij officiële bronnen. Overeenkomsten met vervoerders, accommodaties en andere aanbieders sluit je zelf; GlobeTrotr is daarbij geen reisorganisator of bemiddelaar.", "The beta may contain errors, change or be temporarily unavailable. Maps, weather, rates, flight data and calculations may be inaccurate or delayed. Verify essential travel information with official sources. You enter into agreements with carriers, accommodation and other providers yourself; GlobeTrotr is not the travel organiser or intermediary.")}</Term>
      <Term title={text("5. Beschikbaarheid, beëindiging en gegevens", "5. Availability, termination and data")}>{text("Je kunt deelname stoppen en je account exporteren of verwijderen via Accountinstellingen. GlobeTrotr kan toegang beperken bij misbruik, beveiligingsrisico's of beëindiging van de beta en geeft waar redelijk vooraf bericht. De privacyverklaring blijft gelden voor de verwerking en verwijdering van persoonsgegevens.", "You can stop participating and export or delete your account through Account settings. GlobeTrotr may restrict access for misuse, security risks or termination of the beta and will give advance notice where reasonable. The privacy notice continues to govern processing and deletion of personal data.")}</Term>
      <Term title={text("6. Aansprakelijkheid en consumentenrecht", "6. Liability and consumer law")}>{text("GlobeTrotr is aansprakelijk voor zover dwingend recht dat vereist. Niets in deze voorwaarden sluit aansprakelijkheid uit voor opzet, bewuste roekeloosheid, overlijden of letsel door nalatigheid, of andere aansprakelijkheid die wettelijk niet mag worden uitgesloten. Wettelijke consumentenrechten blijven volledig gelden.", "GlobeTrotr is liable where mandatory law requires it. Nothing in these terms excludes liability for intent, deliberate recklessness, death or personal injury caused by negligence, or other liability that cannot legally be excluded. Statutory consumer rights remain fully applicable.")}</Term>
      <Term title={text("7. Recht, wijzigingen en contact", "7. Law, changes and contact")}>{text("Nederlands recht is van toepassing, zonder verlies van dwingende bescherming die je als consument hebt in het land waar je woont. Geschillen kunnen worden voorgelegd aan de bevoegde rechter volgens de wettelijke regels. We kondigen wezenlijke wijzigingen vooraf aan wanneer dat redelijkerwijs mogelijk is; als je niet akkoord gaat, kun je stoppen en je gegevens exporteren. Contact: GlobeTrotr, postadres (geen bezoekadres), Gedempte Oude Gracht 95, 2011 GT Haarlem, privacy@globetrotr.nl.", "Dutch law applies without taking away mandatory protection you have as a consumer in your country of residence. Disputes may be submitted to the competent court under applicable law. We announce material changes in advance where reasonably possible; if you disagree, you can stop and export your data. Contact: GlobeTrotr, postal address (not a visiting address), Gedempte Oude Gracht 95, 2011 GT Haarlem, privacy@globetrotr.nl.")}</Term>
    </CardContent></Card>
    <p className="text-xs leading-relaxed text-muted-foreground">{text("Door een beta-account te maken en de dienst te gebruiken accepteer je deze voorwaarden. Je behoudt je AVG- en consumentenrechten. Versie 8 september 2026.", "By creating a beta account and using the service, you accept these terms. You retain your GDPR and consumer rights. Version 8 September 2026.")}</p>
  </div>;
}

function Term({ title, children }: { title: string; children: string }) {
  return <section><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{children}</p></section>;
}
