import{useState,type CSSProperties,type ReactNode}from"react";
import{createFileRoute,Link}from"@tanstack/react-router";import{useQuery}from"@tanstack/react-query";import{CheckCircle2,ClipboardList,Clock3,LockKeyhole}from"lucide-react";import{toast}from"sonner";
import{Button}from"@/components/ui/button";import{Card,CardContent}from"@/components/ui/card";import{Input}from"@/components/ui/input";import{Textarea}from"@/components/ui/textarea";import{getPublicAgencyForm,submitPublicAgencyForm,type AgencyFormAnswer,type AgencyFormField}from"@/lib/agency.functions";import{useLocale}from"@/lib/locale";
export const Route=createFileRoute("/client-form/$token")({component:Page});
function Page(){const{token}=Route.useParams();const{text}=useLocale();const query=useQuery({queryKey:["public-client-form",token],queryFn:()=>getPublicAgencyForm({data:{token}}),retry:false});const[answers,setAnswers]=useState<Record<string,AgencyFormAnswer>>({});const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);const data=query.data as any;
 async function submit(){setBusy(true);try{const r=await submitPublicAgencyForm({data:{token,answers}});if(r.status!=="submitted")throw new Error(r.status);setDone(true)}catch{toast.error(text("Controleer de verplichte velden en probeer opnieuw.","Check the required fields and try again."))}finally{setBusy(false)}}
 if(query.isLoading)return <Shell><p className="text-sm text-muted-foreground">{text("Formulier laden…","Loading form…")}</p></Shell>;
 if(done||data?.status==="submitted")return <Shell><CheckCircle2 className="mx-auto size-12 text-primary"/><h1 className="mt-4 text-center font-display text-2xl font-semibold">{text("Antwoorden ontvangen","Answers received")}</h1><p className="mt-2 text-center text-sm text-muted-foreground">{text("De reisorganisatie controleert je antwoorden voordat deze worden verwerkt.","The travel organisation will review your answers before processing them.")}</p></Shell>;
 if(!data||data.status!=="available")return <Shell><ClipboardList className="mx-auto size-10 text-muted-foreground"/><h1 className="mt-4 text-center font-display text-2xl font-semibold">{data?.status==="expired"?text("Deze link is verlopen","This link has expired"):data?.status==="revoked"?text("Deze link is ingetrokken","This link has been revoked"):text("Formulier niet beschikbaar","Form unavailable")}</h1><p className="mt-2 text-center text-sm text-muted-foreground">{text("Vraag je reisorganisatie om een nieuwe link.","Ask your travel organisation for a new link.")}</p></Shell>;
 const en=data.locale==="en";return <div className="mx-auto max-w-2xl space-y-5 py-6 sm:py-10" style={{"--brand-hue":String(data.branding?.accent??168)}as CSSProperties}><header className="rounded-3xl border bg-card p-5 sm:p-8"><img src={data.branding?.logoUrl||"/assets/email/logo.png"} className="mb-4 max-h-14 max-w-48 object-contain" alt=""/><p className="text-sm font-medium text-primary">{data.branding?.brandName||"GlobeTrotr Agency"}</p><h1 className="mt-2 break-words font-display text-3xl font-semibold">{data.title}</h1>{data.introduction&&<p className="mt-3 whitespace-pre-wrap text-muted-foreground">{data.introduction}</p>}<div className="mt-4 flex flex-wrap gap-3 text-xs text-muted-foreground"><span>{en?"For":"Voor"} {data.clientName}</span><span className="inline-flex items-center gap-1"><Clock3 className="size-3.5"/>{en?"Valid until":"Geldig tot"} {new Date(data.expiresAt).toLocaleDateString(en?"en-GB":"nl-NL")}</span></div></header><Card className="surface"><CardContent className="space-y-5 p-5 sm:p-8">{data.fields.map((field:AgencyFormField)=><FormField key={field.key} field={field} en={en} value={answers[field.key]} onChange={value=>setAnswers(current=>({...current,[field.key]:value}))}/>)}<div className="rounded-xl border bg-muted/30 p-4 text-xs text-muted-foreground"><p className="flex gap-2"><LockKeyhole className="size-4 shrink-0 text-primary"/>{en?"Your answers are sent securely and remain draft data until an authorised employee reviews them. Do not enter passwords, payment-card details or authentication codes.":"Je antwoorden worden beveiligd verstuurd en blijven conceptgegevens totdat een bevoegde medewerker ze controleert. Vul geen wachtwoorden, betaalkaartgegevens of authenticatiecodes in."}</p></div><Button className="w-full" disabled={busy} onClick={()=>void submit()}>{busy?(en?"Sending…":"Versturen…"):(en?"Send answers":"Antwoorden versturen")}</Button></CardContent></Card></div>}
function FormField({field,en,value,onChange}:{field:AgencyFormField;en:boolean;value:AgencyFormAnswer|undefined;onChange:(v:AgencyFormAnswer)=>void}){const label=en?field.labelEn:field.labelNl;return <label className="block space-y-1.5 text-sm"><span className="font-medium">{label}{field.required&&" *"}</span><span className="block text-xs text-muted-foreground">{field.purpose}</span>{field.type==="textarea"?<Textarea rows={4} maxLength={4000} required={field.required} value={String(value??"")} onChange={e=>onChange(e.target.value)}/>:field.type==="choice"?<select required={field.required} className="h-10 w-full rounded-md border bg-background px-3" value={String(value??"")} onChange={e=>onChange(e.target.value)}><option value="">—</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==="checkbox"?<input type="checkbox" className="size-5" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>:<Input type={field.type==="phone"?"tel":field.type} maxLength={field.type==="number"?undefined:4000} required={field.required} value={String(value??"")} onChange={e=>onChange(field.type==="number"&&e.target.value!==""?Number(e.target.value):e.target.value)}/>}</label>}
function Shell({children}:{children:ReactNode}){return <div className="mx-auto max-w-xl py-10"><Card className="surface"><CardContent className="p-6">{children}<Button asChild variant="outline" className="mt-6 w-full"><Link to="/">GlobeTrotr</Link></Button></CardContent></Card></div>}
