import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { LandingDemo } from "@/components/LandingDemo";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
export const Route=createFileRoute("/demo")({head:()=>({meta:[{title:"Interactive product demo — GlobeTrotr"},{name:"description",content:"Explore a safe interactive GlobeTrotr demo for routes, itineraries and shared expenses."}]}),component:DemoPage});
function DemoPage(){const{text}=useLocale();const{user}=useAuth();return <div className="space-y-10 pb-8"><section className="mx-auto max-w-3xl text-center"><Badge>{text("Interactieve productdemo","Interactive product demo")}</Badge><h1 className="mt-5 font-display text-4xl font-semibold sm:text-5xl">{text("Klik door een reis voordat je begint.","Explore a trip before you begin.")}</h1><p className="mt-4 text-muted-foreground">{text("Probeer route, planning, paklijst en kosten met veilige voorbeelddata. Er wordt niets opgeslagen.","Try the route, itinerary, packing and expenses with safe sample data. Nothing is saved.")}</p></section><div className="mx-auto max-w-3xl"><LandingDemo /></div><section className="mx-auto grid max-w-3xl gap-3 sm:grid-cols-2">{[text("Werkt direct in je browser","Works directly in your browser"),text("Geen account nodig voor deze demo","No account needed for this demo"),text("NL en EN beschikbaar","Available in NL and EN"),text("Privé totdat jij delen inschakelt","Private until you enable sharing")].map(item=><p key={item} className="flex items-center gap-2 rounded-xl border p-4 text-sm"><CheckCircle2 className="size-4 text-primary"/>{item}</p>)}</section><div className="text-center"><Button asChild size="lg"><Link to={user?"/dashboard":"/auth"}>{user?text("Open mijn reizen","Open my trips"):text("Maak gratis een reis","Create a trip for free")}<ArrowRight className="size-4"/></Link></Button></div></div>}
