import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { LandingDemo } from "@/components/LandingDemo";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
import { portalUrl } from "@/lib/site-routing";

export const Route=createFileRoute("/demo")({head:()=>({meta:[{title:"Interactive product tour — GlobeTrotr"},{name:"description",content:"Follow a realistic GlobeTrotr trip from route and bookings to discoveries, journal and offline use."},{property:"og:title",content:"Try the GlobeTrotr product tour"},{property:"og:description",content:"Explore a realistic trip from planning and comparison to memories and offline use."}],links:[{rel:"canonical",href:"https://globetrotr.nl/demo"}]}),component:DemoPage});

function DemoPage(){const{text}=useLocale();const{user}=useAuth();return <div className="space-y-10 pb-8"><section className="mx-auto max-w-3xl text-center"><Badge>{text("Interactieve productrondleiding","Interactive product tour")}</Badge><h1 className="mt-5 font-display text-4xl font-semibold sm:text-5xl">{text("Volg één reis van plannen tot terugkijken.","Follow one trip from planning to remembering.")}</h1><p className="mt-4 text-muted-foreground">{text("Geen losse trucjes, maar een realistisch voorbeeld. Klik door route, boekingen, vergelijken, dagplanning, ontdekken, kosten, dagboek en offline gebruik.","A realistic workflow instead of disconnected widgets. Explore routes, bookings, comparison, itinerary, discovery, expenses, journal and offline use.")}</p></section><LandingDemo expanded/><section className="mx-auto grid max-w-5xl gap-3 sm:grid-cols-2 lg:grid-cols-4">{[text("Werkt direct in je browser","Works directly in your browser"),text("Geen account nodig","No account required"),text("NL en EN beschikbaar","Available in NL and EN"),text("Niets wordt opgeslagen","Nothing is saved")].map(item=><p key={item} className="flex items-center gap-2 rounded-xl border p-4 text-sm"><CheckCircle2 className="size-4 text-primary"/>{item}</p>)}</section><div className="text-center"><Button asChild size="lg"><a href={portalUrl(user?"/dashboard":"/register")}>{user?text("Open mijn reizen","Open my trips"):text("Plan mijn eerste reis","Plan my first trip")}<ArrowRight className="size-4"/></a></Button></div></div>}
