import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BriefcaseBusiness, CalendarDays, Check, CircleDollarSign, Globe2, MapPin, MapPinned, Plane, ShieldCheck, Sparkles, UserRound, Users, Wallet } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
import { listPublicTrips } from "@/lib/public.functions";
import { LandingDemo } from "@/components/LandingDemo";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "GlobeTrotr — Plan samen, reis slimmer" }, { name: "description", content: "Routes, boekingen, dagplanning en eerlijke kostenverdeling in één reisplanner." }, { property: "og:title", content: "GlobeTrotr — Plan samen, reis slimmer" }, { property: "og:description", content: "Van eerste bestemming tot laatste betaalverzoek: organiseer je hele reis samen." }, { property: "og:url", content: "https://globetrotr.nl/" }, { name: "twitter:title", content: "GlobeTrotr — Plan samen, reis slimmer" }, { name: "twitter:description", content: "Plan routes, boekingen, dagplanning en kosten samen." }], links: [{ rel: "canonical", href: "https://globetrotr.nl/" }] }), component: Landing });

const FEATURES = [
  [MapPin, ["Route die vanzelf overzichtelijk wordt", "A route that stays clear"], ["Zoek bestemmingen wereldwijd, orden stops en zie je hele reis direct op de kaart.", "Find destinations worldwide, order stops and see the complete trip on a map."]],
  [Plane, ["Alle boekingen bij elkaar", "Every booking together"], ["Bewaar vluchten, verblijf, huurauto's, vervoer en activiteiten naast je planning.", "Keep flights, accommodation, rental cars, transport and activities next to your itinerary."]],
  [Wallet, ["Geen gedoe met de rekening", "No expense confusion"], ["Boek uitgaven in meerdere valuta en bereken met zo min mogelijk betalingen wie wie terugbetaalt.", "Track multiple currencies and calculate who repays whom with fewer transfers."]],
  [Users, ["Samen plannen met duidelijke rollen", "Plan together with clear roles"], ["Geef reisgenoten precies toegang tot planning, financiën of alleen bekijken.", "Give fellow travellers the right access to planning, finances or viewing only."]],
] as const;

function AudienceLinks() {
  const { text } = useLocale();
  const audiences = [
    { icon: UserRound, title: text("Voor reizigers", "For travellers"), body: text("Route, planning, boekingen en paklijst in één rustig overzicht.", "Route, itinerary, bookings and packing in one calm overview."), to: "/for-travelers" as const },
    { icon: Users, title: text("Voor groepen", "For groups"), body: text("Samenwerken met duidelijke rollen, meldingen en eerlijke kosten.", "Collaborate with clear roles, notifications and fair expenses."), to: "/for-groups" as const },
    { icon: BriefcaseBusiness, title: text("Voor Agencies", "For agencies"), body: text("Klanten, teamrechten, offertes, taken en huisstijl professioneel beheren.", "Professionally manage clients, permissions, quotes, tasks and branding."), to: "/for-agencies" as const },
  ];
  return <section><div className="mx-auto max-w-2xl text-center"><Badge variant="outline">{text("Voor iedere manier van reizen", "For every way of travelling")}</Badge><h2 className="mt-4 font-display text-3xl font-semibold sm:text-4xl">{text("Van eigen avontuur tot professionele reisservice", "From personal adventure to professional travel service")}</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{audiences.map(({icon:Icon,title,body,to})=><Card key={to} className="surface group"><CardContent className="p-6"><Icon className="size-6 text-primary"/><h3 className="mt-4 font-display text-xl font-semibold">{title}</h3><p className="mt-2 min-h-10 text-sm text-muted-foreground">{body}</p><Link to={to} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">{text("Meer bekijken","Explore more")}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link></CardContent></Card>)}</div></section>;
}

function Landing() {
  const { user } = useAuth();
  const { text } = useLocale();
  const publicTrips = useQuery({ queryKey: ["public-trips"], queryFn: () => listPublicTrips(), staleTime: 60_000 });
  const cta = user ? text("Open mijn reizen", "Open my trips") : text("Gratis beginnen", "Start for free");
  return <div className="space-y-20 pb-8">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"GlobeTrotr",applicationCategory:"TravelApplication",operatingSystem:"Web",url:"https://globetrotr.nl/",description:"Collaborative travel planning for routes, bookings, itineraries and shared expenses.",offers:{"@type":"Offer",price:"0",priceCurrency:"EUR"}})}} />
    <section className="aurora relative overflow-hidden rounded-[2rem] px-6 py-12 sm:px-10 lg:px-14 lg:py-16">
      <div className="absolute -right-16 -top-20 size-72 rounded-full bg-primary/15 blur-3xl" />
      <div className="relative grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]">
        <div><Badge variant="secondary" className="mb-5 gap-1.5"><Sparkles className="size-3.5" /> {text("Nu open voor internationale beta", "Now open for international beta")}</Badge><h1 className="max-w-3xl font-display text-4xl font-semibold leading-[1.08] sm:text-5xl lg:text-6xl">{text("Van reisidee naar vertrek, samen in één overzicht.", "From travel idea to takeoff, together in one place.")}</h1><p className="mt-5 max-w-xl text-base leading-relaxed opacity-90 sm:text-lg">{text("GlobeTrotr brengt je route, planning, boekingen, paklijst en kosten samen. Minder zoeken in chats en spreadsheets, meer zin in de reis.", "GlobeTrotr brings your route, itinerary, bookings, packing list and expenses together. Less searching through chats and spreadsheets, more excitement for the trip.")}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to={user ? "/dashboard" : "/auth"}>{cta}<ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="outline"><Link to="/features">{text("Ontdek alle mogelijkheden", "Explore all features")}</Link></Button></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs opacity-80">{[text("Gratis starten", "Start free"), text("Privé als standaard", "Private by default"), text("Nederlands & English", "English & Nederlands")].map(item=><span key={item} className="flex items-center gap-1.5"><Check className="size-3.5" />{item}</span>)}</div></div>
        <LandingDemo />
      </div>
    </section>

    <section><div className="mx-auto max-w-2xl text-center"><Badge variant="outline">{text("Alles voor je reis", "Everything for your trip")}</Badge><h2 className="mt-4 font-display text-3xl font-semibold sm:text-4xl">{text("Eén rustige plek voor alle bewegende delen", "One calm place for every moving part")}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground sm:text-base">{text("GlobeTrotr volgt de manier waarop een reis echt groeit: eerst een route, daarna details, afspraken en kosten.", "GlobeTrotr follows how a trip actually grows: a route first, then details, decisions and expenses.")}</p></div><div className="mt-8 grid gap-4 md:grid-cols-2">{FEATURES.map(([Icon,title,copy])=><Card key={title[0]} className="surface group overflow-hidden"><CardContent className="flex gap-4 p-6"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-primary/10 text-primary transition-transform group-hover:scale-105"><Icon className="size-6" /></span><div><h3 className="font-display text-lg font-semibold">{text(title[0],title[1])}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text(copy[0],copy[1])}</p></div></CardContent></Card>)}</div></section>

    <AudienceLinks />

    <section className="grid items-center gap-8 rounded-3xl border border-border bg-card/60 p-6 sm:p-10 lg:grid-cols-2"><div><Badge variant="secondary">{text("Zo werkt het", "How it works")}</Badge><h2 className="mt-4 font-display text-3xl font-semibold">{text("Drie stappen. Daarna kan de voorpret beginnen.", "Three steps. Then the anticipation can begin.")}</h2><div className="mt-7 space-y-5">{[["01",text("Maak je reis en zet de route uit", "Create your trip and map the route")],["02",text("Nodig je reisgenoten uit en verdeel rollen", "Invite fellow travellers and assign roles")],["03",text("Plan, boek, pak en verreken samen", "Plan, book, pack and settle together")]].map(([n,label])=><div key={n} className="flex items-center gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-primary font-semibold text-primary-foreground">{n}</span><p className="font-medium">{label}</p></div>)}</div></div><div className="rounded-2xl bg-muted/50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">{text("Volgende reis", "Next trip")}</p><p className="font-display text-xl font-semibold">Iceland roadtrip</p></div><Badge>12 {text("dagen", "days")}</Badge></div><div className="mt-5 grid grid-cols-3 gap-2">{[[MapPinned,"8",text("stops", "stops")],[CalendarDays,"24",text("plannen", "plans")],[CircleDollarSign,"€842",text("besteed", "spent")]].map(([Icon,value,label])=><div key={String(label)} className="rounded-xl border bg-background p-3"><Icon className="size-4 text-primary" /><p className="mt-3 font-semibold">{value as string}</p><p className="text-[11px] text-muted-foreground">{label as string}</p></div>)}</div><div className="mt-4 rounded-xl border bg-background p-4"><div className="mb-3 flex justify-between text-xs"><span>{text("Route", "Route")}</span><span className="text-muted-foreground">Reykjavík → Vík → Höfn</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full w-2/3 rounded-full bg-primary" /></div></div></div></section>

    <section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><Badge variant="outline"><Globe2 className="mr-1 size-3" /> {text("Reisinspiratie", "Travel inspiration")}</Badge><h2 className="mt-3 font-display text-3xl font-semibold">{text("Bekijk openbare reisverhalen", "Explore public travel stories")}</h2><p className="mt-2 text-sm text-muted-foreground">{text("Routes die reizigers bewust openbaar hebben gedeeld.", "Routes travellers have intentionally shared publicly.")}</p></div></div>{publicTrips.isLoading?<p className="text-sm text-muted-foreground">{text("Reizen laden…", "Loading trips…")}</p>:publicTrips.isError?<p className="text-sm text-muted-foreground">{text("Openbare reizen konden niet worden geladen.", "Public trips could not be loaded.")} <button type="button" className="text-primary underline" onClick={() => void publicTrips.refetch()}>{text("Opnieuw proberen", "Try again")}</button></p>:(publicTrips.data??[]).length===0?<Card className="surface"><CardContent className="py-8 text-center text-sm text-muted-foreground">{text("Nog geen openbare reizen. Deel straks de eerste.", "No public trips yet. Be the first to share one.")}</CardContent></Card>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(publicTrips.data??[]).slice(0,6).map(t=><Card key={`${t.token}-${t.tripId}`} className="surface flex flex-col transition-transform hover:-translate-y-1"><CardHeader><CardTitle className="break-anywhere text-base"><Link to="/trip/$token/$tripId" params={{token:t.token,tripId:t.tripId}}>{t.name}</Link></CardTitle><p className="text-xs text-muted-foreground">{t.start} → {t.end} · {text("door","by")} {t.authorName}</p></CardHeader><CardContent className="mt-auto flex items-start gap-2 text-sm text-muted-foreground"><MapPin className="mt-0.5 size-4 shrink-0" /><span className="break-anywhere">{t.stops.slice(0,4).map(s=>s.name).join(" · ")||text("Nog geen bestemmingen","No destinations yet")}</span></CardContent></Card>)}</div>}</section>

    <section className="aurora rounded-3xl px-6 py-10 text-center sm:px-10 sm:py-14"><ShieldCheck className="mx-auto size-8 text-primary" /><h2 className="mt-4 font-display text-3xl font-semibold">{text("Klaar om je volgende reis bij elkaar te brengen?", "Ready to bring your next trip together?")}</h2><p className="mx-auto mt-3 max-w-xl text-sm opacity-85">{text("Begin gratis in de beta. Je reizen zijn privé totdat jij besluit ze te delen.", "Start free in the beta. Your trips stay private until you choose to share them.")}</p><Button asChild size="lg" className="mt-7"><Link to={user?"/dashboard":"/auth"}>{cta}<ArrowRight className="size-4" /></Link></Button></section>
  </div>;
}
