import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, CircleAlert, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
import { PLANS } from "@/lib/plans";

export const Route = createFileRoute("/prijzen")({ head: () => ({ meta: [{ title: "Prijzen — GlobeTrotr" }, { name: "description", content: "Vergelijk GlobeTrotr Free, Pro en Agency." }] }), component: PricingPage });

const featureEn: Record<string,string> = {"2 actieve reizen":"2 active trips","Routekaart & uitgaven":"Route map & expenses","CSV-export":"CSV export","Onbeperkt reizen":"Unlimited trips","Live weer & valutakoersen":"Live weather & exchange rates","PDF-reisoverzicht":"PDF trip overview","Eigen merk en domein":"Your own brand and domain","Rollen en rechten":"Roles and permissions","Declarabele klantuitgaven":"Billable client expenses","Bonnetjes bij uitgaven":"Expense receipts"};

export function PricingPage(){
  const {user}=useAuth(); const {text}=useLocale();
  return <div className="mx-auto max-w-6xl space-y-10">
    <header className="aurora rounded-3xl px-6 py-12 text-center sm:px-10 sm:py-16"><Badge variant="secondary" className="gap-1.5"><Sparkles className="size-3.5"/>{text("Eenvoudige prijzen","Simple pricing")}</Badge><h1 className="mt-5 font-display text-4xl font-semibold sm:text-5xl">{text("Begin gratis. Groei mee met je reizen.","Start free. Grow with your travels.")}</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-relaxed opacity-90 sm:text-base">{text("Een plan voor je eigen reizen, samenwerken met je reisgroep of professioneel klantbeheer.","A plan for your own trips, collaboration with your travel group or professional client management.")}</p></header>
    <div className="grid gap-5 md:grid-cols-3">{PLANS.map(plan=><Card key={plan.id} className={`surface flex flex-col ${plan.id==="pro"?"border-primary/50 ring-1 ring-primary/20":""}`}><CardHeader>{plan.id==="pro"&&<Badge className="mb-2 w-fit">{text("Meest gekozen","Most popular")}</Badge>}<CardTitle className="text-xl">{plan.name}</CardTitle><p className="pt-2 font-display text-4xl font-semibold">€{plan.price}<span className="text-sm font-normal text-muted-foreground">/{text("maand","month")}</span></p><p className="text-sm text-muted-foreground">{text(plan.seats,plan.id==="free"?"For you":plan.id==="pro"?"For you and your travel group":"Unlimited team members")}</p></CardHeader><CardContent className="flex flex-1 flex-col"><ul className="flex-1 space-y-3 text-sm">{plan.highlights.map(item=><li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-primary"/><span>{text(item,featureEn[item]??item)}</span></li>)}</ul><Button asChild className="mt-6 w-full" variant={plan.id==="pro"?"default":"outline"}><Link to={user?"/billing":"/auth"}>{user?text("Bekijk abonnement","View plan"):text("Start de gratis beta","Start the free beta")}<ArrowRight className="size-4"/></Link></Button></CardContent></Card>)}</div>
    <Card className="border-amber-500/25 bg-amber-500/5"><CardContent className="flex gap-3 p-5"><CircleAlert className="mt-0.5 size-5 shrink-0 text-amber-600"/><div><h2 className="font-semibold">{text("Beta en betalingen via Paddle","Beta and payments through Paddle")}</h2><p className="mt-1 text-sm text-muted-foreground">{text("Tijdens de huidige beta wordt niets afgeschreven. De getoonde Pro- en Agency-prijzen zijn de beoogde maandprijzen voor de betaalde lancering. Zodra betalingen live zijn, is Paddle de Merchant of Record: Paddle verkoopt het abonnement, berekent toepasselijke belasting, verwerkt de betaling en verstrekt het betalingsbewijs. De checkout toont altijd eerst de definitieve totaalprijs, valuta, factureringsperiode en verlengingsvoorwaarden.","Nothing is charged during the current beta. The displayed Pro and Agency prices are the intended monthly prices for the paid launch. Once payments are live, Paddle is the Merchant of Record: Paddle sells the subscription, calculates applicable tax, processes payment and issues the receipt. Checkout always shows the final total price, currency, billing period and renewal terms first.")}</p></div></CardContent></Card>
    <div className="flex flex-wrap justify-center gap-3 text-sm"><Link to="/terms" className="text-primary underline">{text("Algemene voorwaarden","Terms and conditions")}</Link><span>·</span><Link to="/refund-policy" className="text-primary underline">{text("Terugbetalingsbeleid","Refund policy")}</Link></div>
  </div>;
}
