import { createFileRoute, Link } from "@tanstack/react-router";
import { FileDown, Scale, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
import { openPrivacyChoices } from "@/lib/privacy-consent";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacy — GlobeTrotr" }, { name: "description", content: "Privacy- en browseropslagverklaring van GlobeTrotr." }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const { user } = useAuth();
  const { text } = useLocale();
  return <div className="mx-auto max-w-4xl space-y-8">
    <header className="aurora rounded-3xl px-6 py-10 sm:px-10 sm:py-14">
      <Badge variant="secondary" className="mb-4 gap-1.5"><ShieldCheck className="size-3.5" /> AVG / GDPR</Badge>
      <h1 className="font-display text-3xl font-semibold sm:text-5xl">{text("Jouw reis, jouw gegevens", "Your trip, your data")}</h1>
      <p className="mt-4 max-w-2xl text-sm leading-relaxed opacity-90">{text("Privacy- en browseropslagverklaring voor de internationale beta en de beoogde betaalde dienst. Versie 11 september 2026.", "Privacy and browser-storage notice for the international beta and intended paid service. Version 11 September 2026.")}</p>
    </header>
    <Card className="surface"><CardContent className="space-y-8 p-6 sm:p-8">
      <Policy title={text("1. Verwerkingsverantwoordelijke", "1. Controller")}><span>GlobeTrotr<br />{text("Postadres (geen bezoekadres):", "Postal address (not a visiting address):")}<br />Gedempte Oude Gracht 95<br />2011 GT Haarlem<br /><a className="text-primary underline" href="mailto:privacy@globetrotr.nl">privacy@globetrotr.nl</a></span></Policy>
      <Policy title={text("2. Gegevens, doelen en grondslagen", "2. Data, purposes and legal bases")}><ul className="list-disc space-y-2 pl-5">
        <li>{text("Account-, profiel- en authenticatiegegevens: om je account te leveren en beveiligen; uitvoering van de overeenkomst.", "Account, profile and authentication data: to provide and secure your account; performance of the agreement.")}</li>
        <li>{text("Reizen, routes, planning, reisleden, boekingen, uitgaven, paklijsten en uploads: om de gekozen functies en samenwerking te leveren; uitvoering van de overeenkomst.", "Trips, routes, itinerary, members, bookings, expenses, packing lists and uploads: to provide selected features and collaboration; performance of the agreement.")}</li>
        <li>{text("IP-adres, serverlogs, fout- en misbruikgegevens: beveiliging, foutonderzoek en fraudepreventie; gerechtvaardigd belang, afgewogen tegen jouw privacy.", "IP address, server logs, error and abuse data: security, troubleshooting and fraud prevention; legitimate interests balanced against your privacy.")}</li>
        <li>{text("E-mailberichten en bezorggegevens: accountbevestigingen, uitnodigingen, beveiligingsmeldingen en noodzakelijke servicecommunicatie verzenden; uitvoering van de overeenkomst en beveiliging. Marketingmail vereist een afzonderlijke geldige grondslag.", "Email messages and delivery data: sending account confirmations, invitations, security notices and necessary service communications; performance of the agreement and security. Marketing email requires a separate valid legal basis.")}</li>
        <li>{text("Abonnements-, transactie- en factuurgegevens die Paddle met ons deelt: toegang activeren, abonnementen beheren, ondersteuning bieden en voldoen aan administratieplichten; uitvoering van de overeenkomst en wettelijke verplichting. GlobeTrotr ontvangt geen volledige betaalkaartgegevens.", "Subscription, transaction and invoice data shared with us by Paddle: activating access, managing subscriptions, providing support and meeting record-keeping duties; performance of the agreement and legal obligation. GlobeTrotr does not receive full payment card details.")}</li>
        <li>{text("Openbaar delen en optionele voorkeursopslag: jouw actieve keuze of toestemming. Je kunt die keuze altijd terugdraaien.", "Public sharing and optional preference storage: your active choice or consent. You can reverse that choice at any time.")}</li>
        <li>{text("Gegevens die wettelijk moeten worden bewaard of verstrekt: wettelijke verplichting.", "Data that must legally be retained or disclosed: legal obligation.")}</li>
      </ul></Policy>
      <Policy title={text("3. Ontvangers, hosting en leveranciers", "3. Recipients, hosting and suppliers")}><div className="space-y-3"><p>{text("Gegevens zijn beschikbaar voor jou, reisleden binnen hun rol, bezoekers van een reis die jij openbaar maakt en leveranciers die de dienst uitvoeren. GlobeTrotr verkoopt geen persoonsgegevens.", "Data is available to you, trip members within their role, visitors to a trip you publish and suppliers that provide the service. GlobeTrotr does not sell personal data.")}</p><ul className="list-disc space-y-2 pl-5">
        <li>{text("De GlobeTrotr-applicatieserver wordt na de migratie beheerd op gehuurde VPS-infrastructuur. De infrastructuurleverancier verwerkt daarbij technisch IP-adressen, verzoeken, tijdelijke gegevens en beveiligingslogs. De concrete leverancier, regio en bewaartermijnen worden hier vóór de productieomschakeling gepubliceerd.", "After migration, the GlobeTrotr application server will be managed on rented VPS infrastructure. The infrastructure provider technically processes IP addresses, requests, temporary data and security logs. The specific provider, region and retention periods will be published here before the production switch.")}</li>
        <li>{text("Supabase verzorgt database, authenticatie en bestandsopslag en verwerkt daarvoor account- en reisgegevens in opdracht van GlobeTrotr.", "Supabase provides the database, authentication and file storage and processes account and trip data on GlobeTrotr's behalf.")}</li>
        <li>{text("De gekozen SMTP-leverancier zal e-mailadres, naam, berichtinhoud, tijdstip en technische bezorgstatus verwerken voor transactionele e-mail. De leverancier, regio, verwerkersafspraken en bewaartermijn worden vóór activering gepubliceerd.", "The selected SMTP provider will process email address, name, message content, timestamp and technical delivery status for transactional email. The provider, region, processing terms and retention period will be published before activation.")}</li>
        <li>{text("Paddle treedt bij betaalde aankopen op als Merchant of Record en zelfstandig verwerkingsverantwoordelijke voor checkout, betaling, belasting, facturatie, fraude- en compliancecontroles. Paddle kan noodzakelijke koper- en transactiegegevens aan GlobeTrotr verstrekken voor levering en ondersteuning. Op de checkout gelden ook de actuele privacyverklaring en kopersvoorwaarden van Paddle.", "For paid purchases, Paddle acts as Merchant of Record and an independent controller for checkout, payment, tax, invoicing, fraud and compliance checks. Paddle may provide necessary buyer and transaction data to GlobeTrotr for fulfilment and support. Paddle's current privacy notice and buyer terms also apply at checkout.")}</li>
        <li>{text("OpenStreetMap/Nominatim levert kaarten en locatiezoekresultaten, Open-Meteo en MET Norway weergegevens, Frankfurter/ECB wisselkoersen en SkyLink vluchtinformatie. Bij rechtstreeks gebruik kan de leverancier technische verzoekgegevens ontvangen, waaronder IP-adres, tijdstip en aangevraagde inhoud.", "OpenStreetMap/Nominatim provides maps and location searches, Open-Meteo and MET Norway weather, Frankfurter/ECB exchange rates and SkyLink flight information. When used directly, the provider may receive technical request data including IP address, time and requested content.")}</li>
      </ul></div></Policy>
      <Policy title={text("4. Doorgifte buiten de EER", "4. Transfers outside the EEA")}>{text("Leveranciers kunnen gegevens buiten de Europese Economische Ruimte verwerken. Waar vereist worden een adequaatheidsbesluit, standaardcontractbepalingen en passende aanvullende maatregelen gebruikt. De concrete locatie en waarborg hangen af van de actuele infrastructuur van de leverancier.", "Suppliers may process data outside the European Economic Area. Where required, an adequacy decision, standard contractual clauses and appropriate supplementary measures are used. The specific location and safeguard depend on the supplier's current infrastructure.")}</Policy>
      <Policy title={text("5. Bewaren", "5. Retention")}><ul className="list-disc space-y-2 pl-5">
        <li>{text("Account- en reisgegevens: zolang je account actief is of totdat je ze verwijdert.", "Account and trip data: while your account is active or until you delete it.")}</li>
        <li>{text("Uitnodigingen en samenwerking: zolang de uitnodiging of reisrelatie nodig is.", "Invitations and collaboration: while the invitation or trip relationship is needed.")}</li>
        <li>{text("Lokale reiscache: totdat je uitlogt, je account verwijdert of browseropslag wist.", "Local trip cache: until you sign out, delete your account or clear browser storage.")}</li>
        <li>{text("Logs en back-ups: gedurende de technisch of juridisch noodzakelijke herstel-, beveiligings- of bewaartermijn; daarna verwijderd of overschreven.", "Logs and backups: for the technically or legally necessary recovery, security or retention period; then deleted or overwritten.")}</li>
        <li>{text("Transactionele e-mailmetadata: zolang nodig voor bezorging, foutonderzoek en beveiliging; de definitieve termijn wordt met de SMTP-leverancier vóór activering vastgesteld.", "Transactional email metadata: as long as needed for delivery, troubleshooting and security; the final period will be set with the SMTP provider before activation.")}</li>
        <li>{text("Abonnements- en financiële administratie: gedurende de toepasselijke wettelijke bewaartermijn, ook nadat een account is verwijderd. Paddle bewaart eigen transactiegegevens volgens zijn wettelijke plichten en privacyverklaring.", "Subscription and financial records: for the applicable statutory retention period, including after account deletion. Paddle retains its own transaction data under its legal obligations and privacy notice.")}</li>
      </ul></Policy>
      <Policy title={text("6. Openbare reizen", "6. Public trips")}>{text("Reizen zijn standaard privé. Publiceer alleen gegevens die je mag delen. Een openbare link kan worden doorgestuurd en informatie kan worden gekopieerd. Boekingsnummers, prijzen, notities en live vluchtgegevens worden niet via de publieke reis-API vrijgegeven. Schakel delen uit zodra het niet meer nodig is.", "Trips are private by default. Publish only data you are allowed to share. A public link can be forwarded and information can be copied. Booking references, prices, notes and live flight data are not released through the public trip API. Disable sharing when no longer needed.")}</Policy>
      <Policy title={text("7. Jouw AVG-rechten", "7. Your GDPR rights")}>{text("Je kunt, waar van toepassing, vragen om informatie, inzage, correctie, verwijdering, beperking, overdraagbaarheid of bezwaar. Je kunt toestemming altijd intrekken zonder dat eerdere verwerking daardoor onrechtmatig wordt. Er is geen uitsluitend geautomatiseerde besluitvorming met juridische of vergelijkbaar belangrijke gevolgen. We kunnen je identiteit controleren en reageren normaal binnen één maand; verzoeken zijn doorgaans gratis. Je kunt een klacht indienen bij de Autoriteit Persoonsgegevens of de toezichthouder waar je woont of werkt.", "Where applicable, you can request information, access, correction, deletion, restriction, portability or object. You can withdraw consent at any time without making earlier processing unlawful. There is no solely automated decision-making with legal or similarly significant effects. We may verify your identity and normally respond within one month; requests are generally free. You may complain to the Dutch Data Protection Authority or the authority where you live or work.")}</Policy>
      <section id="browseropslag"><h2 className="font-display text-lg font-semibold">{text("8. Cookies en browseropslag", "8. Cookies and browser storage")}</h2>
        <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead><tr className="border-b"><th className="p-2">{text("Naam", "Name")}</th><th className="p-2">{text("Doel", "Purpose")}</th><th className="p-2">{text("Categorie", "Category")}</th><th className="p-2">{text("Bewaring", "Retention")}</th></tr></thead><tbody className="text-muted-foreground">
          <StorageRow name="sb-…-auth-token" purpose={text("Inlogsessie en tokenvernieuwing", "Sign-in session and token refresh")} category={text("Noodzakelijk", "Necessary")} retention={text("Tot uitloggen of verlopen", "Until sign-out or expiry")} />
          <StorageRow name="globetrotr.workspace.v1.…" purpose={text("Lokale reiscache en herstel bij verbindingsverlies", "Local trip cache and recovery after connection loss")} category={text("Noodzakelijk", "Necessary")} retention={text("Tot uitloggen, verwijderen of browser wissen", "Until sign-out, deletion or browser clearing")} />
          <StorageRow name="globetrotr.privacy-choice.v1" purpose={text("Je privacykeuze onthouden", "Remember your privacy choice")} category={text("Noodzakelijk", "Necessary")} retention={text("Tot wissen of vervangen", "Until cleared or replaced")} />
          <StorageRow name="globetrotr.theme" purpose={text("De gekozen lichte, donkere of systeemweergave vóór de eerste schermweergave toepassen", "Apply the selected light, dark or system appearance before the first screen is painted")} category={text("Functionele voorkeur", "Functional preference")} retention={text("Tot wijzigen of browser wissen", "Until changed or browser clearing")} />
          <StorageRow name="globetrotr.locale" purpose={text("Je taalkeuze onthouden", "Remember your language choice")} category={text("Optionele voorkeur", "Optional preference")} retention={text("Tot intrekken of browser wissen", "Until withdrawal or browser clearing")} />
        </tbody></table></div>
        <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text("Dit zijn localStorage-items, geen traditionele cookies. De regels gelden ook voor vergelijkbare opslag op je apparaat. GlobeTrotr gebruikt geen analyse-, advertentie-, marketing- of cross-site-trackingtechnologie. Noodzakelijke opslag houdt de ingelogde app werkend; optionele voorkeuren worden pas na jouw keuze bewaard.", "These are localStorage items, not traditional cookies. The rules also cover similar storage on your device. GlobeTrotr uses no analytics, advertising, marketing or cross-site tracking technologies. Necessary storage keeps the signed-in app working; optional preferences are saved only after your choice.")}</p>
      </section>
      <Policy title={text("9. Beveiliging, kinderen en wijzigingen", "9. Security, children and changes")}>{text("We gebruiken onder meer toegangsrollen, afgeschermde serverfuncties, beperkte publieke velden, versleuteld transport, beperkte secrets en serverlogs voor beveiliging. VPS- en SMTP-toegang worden tot bevoegde beheerders beperkt. Geen beveiliging is absoluut. De dienst is niet gericht op kinderen jonger dan 16 jaar. Vóór de hosting-, SMTP- of Paddle-productieomschakeling vullen we deze verklaring aan met de definitieve leveranciers, locaties, bewaartermijnen en eventuele cookies. Bij wezenlijke wijzigingen informeren we actieve gebruikers waar nodig.", "We use access roles, protected server functions, limited public fields, encrypted transport, restricted secrets and server logs for security. VPS and SMTP access is limited to authorised administrators. No security is absolute. The service is not directed at children under 16. Before the hosting, SMTP or Paddle production switch, we will add the final providers, locations, retention periods and any cookies to this notice. We notify active users of material changes where required.")}</Policy>
    </CardContent></Card>
    <div className="flex flex-wrap gap-3"><Button type="button" variant="outline" onClick={openPrivacyChoices}>{text("Privacykeuzes wijzigen", "Change privacy choices")}</Button>{user && <Button asChild><Link to="/account"><FileDown className="size-4" /> {text("Exporteren of verwijderen", "Export or delete")}</Link></Button>}<Button asChild variant="outline"><a href="https://autoriteitpersoonsgegevens.nl/een-tip-of-klacht-indienen-bij-de-ap" target="_blank" rel="noreferrer"><Scale className="size-4" /> Autoriteit Persoonsgegevens</a></Button></div>
  </div>;
}

function Policy({ title, children }: { title: string; children: ReactNode }) { return <section><h2 className="font-display text-lg font-semibold">{title}</h2><div className="mt-2 text-sm leading-relaxed text-muted-foreground">{children}</div></section>; }
function StorageRow({ name, purpose, category, retention }: { name: string; purpose: string; category: string; retention: string }) { return <tr className="border-b align-top"><td className="p-2 font-mono text-foreground">{name}</td><td className="p-2">{purpose}</td><td className="p-2">{category}</td><td className="p-2">{retention}</td></tr>; }
