import { createFileRoute, Link } from "@tanstack/react-router";
import { FileDown, Scale, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";
import { openPrivacyChoices } from "@/lib/privacy-consent";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacy — GlobeTrotr" }, { name: "description", content: "Privacy- en browseropslagverklaring van GlobeTrotr." }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const { user } = useAuth();
  const { text } = useLocale();
  return <div className="mx-auto max-w-4xl space-y-8">
    <header className="aurora rounded-3xl px-6 py-10 sm:px-10 sm:py-14">
      <Badge variant="secondary" className="mb-4 gap-1.5"><ShieldCheck className="size-3.5" /> AVG / GDPR</Badge>
      <h1 className="font-display text-3xl font-semibold sm:text-5xl">{text("Jouw reis, jouw gegevens", "Your trip, your data")}</h1>
      <p className="mt-4 max-w-2xl text-sm leading-relaxed opacity-90">{text("Privacy- en browseropslagverklaring voor de internationale beta. Versie 8 september 2026.", "Privacy and browser-storage notice for the international beta. Version 8 September 2026.")}</p>
    </header>
    <Card className="surface"><CardContent className="space-y-8 p-6 sm:p-8">
      <Policy title={text("1. Verwerkingsverantwoordelijke", "1. Controller")}>{text("GlobeTrotr bepaalt voor welke doelen en hoe persoonsgegevens in deze dienst worden verwerkt. De officiële juridische naam, het postadres en het privacy-e-mailadres worden vóór de openbare productieopening hier gepubliceerd. Tijdens de besloten beta gebruik je het contactkanaal van je uitnodiging.", "GlobeTrotr determines why and how personal data is processed in this service. The official legal name, postal address and privacy email address will be published here before the public production launch. During the closed beta, use the contact channel from your invitation.")}</Policy>
      <Policy title={text("2. Gegevens, doelen en grondslagen", "2. Data, purposes and legal bases")}><ul className="list-disc space-y-2 pl-5">
        <li>{text("Account-, profiel- en authenticatiegegevens: om je account te leveren en beveiligen; uitvoering van de overeenkomst.", "Account, profile and authentication data: to provide and secure your account; performance of the agreement.")}</li>
        <li>{text("Reizen, routes, planning, reisleden, boekingen, uitgaven, paklijsten en uploads: om de gekozen functies en samenwerking te leveren; uitvoering van de overeenkomst.", "Trips, routes, itinerary, members, bookings, expenses, packing lists and uploads: to provide selected features and collaboration; performance of the agreement.")}</li>
        <li>{text("IP-adres, serverlogs, fout- en misbruikgegevens: beveiliging, foutonderzoek en fraudepreventie; gerechtvaardigd belang, afgewogen tegen jouw privacy.", "IP address, server logs, error and abuse data: security, troubleshooting and fraud prevention; legitimate interests balanced against your privacy.")}</li>
        <li>{text("Openbaar delen en optionele voorkeursopslag: jouw actieve keuze of toestemming. Je kunt die keuze altijd terugdraaien.", "Public sharing and optional preference storage: your active choice or consent. You can reverse that choice at any time.")}</li>
        <li>{text("Gegevens die wettelijk moeten worden bewaard of verstrekt: wettelijke verplichting.", "Data that must legally be retained or disclosed: legal obligation.")}</li>
      </ul></Policy>
      <Policy title={text("3. Ontvangers en leveranciers", "3. Recipients and suppliers")}>{text("Gegevens zijn beschikbaar voor jou, reisleden binnen hun rol, bezoekers van een reis die jij openbaar maakt en leveranciers die de dienst uitvoeren. Supabase verzorgt database, authenticatie en bestandsopslag. OpenStreetMap/Nominatim levert kaarten en locatiezoekresultaten, Open-Meteo weergegevens, Frankfurter/ECB wisselkoersen en SkyLink vluchtinformatie. Bij gebruik van zo'n functie ontvangt de leverancier technische verzoekgegevens, waaronder IP-adres, tijdstip en aangevraagde inhoud. GlobeTrotr verkoopt geen persoonsgegevens.", "Data is available to you, trip members within their role, visitors to a trip you publish and suppliers that provide the service. Supabase provides database, authentication and file storage. OpenStreetMap/Nominatim provides maps and location searches, Open-Meteo weather, Frankfurter/ECB exchange rates and SkyLink flight information. When such a feature is used, the supplier receives technical request data including IP address, time and requested content. GlobeTrotr does not sell personal data.")}</Policy>
      <Policy title={text("4. Doorgifte buiten de EER", "4. Transfers outside the EEA")}>{text("Leveranciers kunnen gegevens buiten de Europese Economische Ruimte verwerken. Waar vereist worden een adequaatheidsbesluit, standaardcontractbepalingen en passende aanvullende maatregelen gebruikt. De concrete locatie en waarborg hangen af van de actuele infrastructuur van de leverancier.", "Suppliers may process data outside the European Economic Area. Where required, an adequacy decision, standard contractual clauses and appropriate supplementary measures are used. The specific location and safeguard depend on the supplier's current infrastructure.")}</Policy>
      <Policy title={text("5. Bewaren", "5. Retention")}><ul className="list-disc space-y-2 pl-5">
        <li>{text("Account- en reisgegevens: zolang je account actief is of totdat je ze verwijdert.", "Account and trip data: while your account is active or until you delete it.")}</li>
        <li>{text("Uitnodigingen en samenwerking: zolang de uitnodiging of reisrelatie nodig is.", "Invitations and collaboration: while the invitation or trip relationship is needed.")}</li>
        <li>{text("Lokale reiscache: totdat je uitlogt, je account verwijdert of browseropslag wist.", "Local trip cache: until you sign out, delete your account or clear browser storage.")}</li>
        <li>{text("Logs en back-ups: gedurende de technisch of juridisch noodzakelijke herstel-, beveiligings- of bewaartermijn; daarna verwijderd of overschreven.", "Logs and backups: for the technically or legally necessary recovery, security or retention period; then deleted or overwritten.")}</li>
      </ul></Policy>
      <Policy title={text("6. Openbare reizen", "6. Public trips")}>{text("Reizen zijn standaard privé. Publiceer alleen gegevens die je mag delen. Een openbare link kan worden doorgestuurd en informatie kan worden gekopieerd. Boekingsnummers, prijzen, notities en live vluchtgegevens worden niet via de publieke reis-API vrijgegeven. Schakel delen uit zodra het niet meer nodig is.", "Trips are private by default. Publish only data you are allowed to share. A public link can be forwarded and information can be copied. Booking references, prices, notes and live flight data are not released through the public trip API. Disable sharing when no longer needed.")}</Policy>
      <Policy title={text("7. Jouw AVG-rechten", "7. Your GDPR rights")}>{text("Je kunt, waar van toepassing, vragen om informatie, inzage, correctie, verwijdering, beperking, overdraagbaarheid of bezwaar. Je kunt toestemming altijd intrekken zonder dat eerdere verwerking daardoor onrechtmatig wordt. Er is geen uitsluitend geautomatiseerde besluitvorming met juridische of vergelijkbaar belangrijke gevolgen. We kunnen je identiteit controleren en reageren normaal binnen één maand; verzoeken zijn doorgaans gratis. Je kunt een klacht indienen bij de Autoriteit Persoonsgegevens of de toezichthouder waar je woont of werkt.", "Where applicable, you can request information, access, correction, deletion, restriction, portability or object. You can withdraw consent at any time without making earlier processing unlawful. There is no solely automated decision-making with legal or similarly significant effects. We may verify your identity and normally respond within one month; requests are generally free. You may complain to the Dutch Data Protection Authority or the authority where you live or work.")}</Policy>
      <section id="browseropslag"><h2 className="font-display text-lg font-semibold">{text("8. Cookies en browseropslag", "8. Cookies and browser storage")}</h2>
        <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead><tr className="border-b"><th className="p-2">{text("Naam", "Name")}</th><th className="p-2">{text("Doel", "Purpose")}</th><th className="p-2">{text("Categorie", "Category")}</th><th className="p-2">{text("Bewaring", "Retention")}</th></tr></thead><tbody className="text-muted-foreground">
          <StorageRow name="sb-…-auth-token" purpose={text("Inlogsessie en tokenvernieuwing", "Sign-in session and token refresh")} category={text("Noodzakelijk", "Necessary")} retention={text("Tot uitloggen of verlopen", "Until sign-out or expiry")} />
          <StorageRow name="atlasledger.workspace.v1.…" purpose={text("Lokale reiscache en herstel bij verbindingsverlies", "Local trip cache and recovery after connection loss")} category={text("Noodzakelijk", "Necessary")} retention={text("Tot uitloggen, verwijderen of browser wissen", "Until sign-out, deletion or browser clearing")} />
          <StorageRow name="globetrotr.privacy-choice.v1" purpose={text("Je privacykeuze onthouden", "Remember your privacy choice")} category={text("Noodzakelijk", "Necessary")} retention={text("Tot wissen of vervangen", "Until cleared or replaced")} />
          <StorageRow name="globetrotr.locale" purpose={text("Je taalkeuze onthouden", "Remember your language choice")} category={text("Optionele voorkeur", "Optional preference")} retention={text("Tot intrekken of browser wissen", "Until withdrawal or browser clearing")} />
        </tbody></table></div>
        <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text("Dit zijn localStorage-items, geen traditionele cookies. De regels gelden ook voor vergelijkbare opslag op je apparaat. GlobeTrotr gebruikt geen analyse-, advertentie-, marketing- of cross-site-trackingtechnologie. Noodzakelijke opslag houdt de ingelogde app werkend; optionele voorkeuren worden pas na jouw keuze bewaard.", "These are localStorage items, not traditional cookies. The rules also cover similar storage on your device. GlobeTrotr uses no analytics, advertising, marketing or cross-site tracking technologies. Necessary storage keeps the signed-in app working; optional preferences are saved only after your choice.")}</p>
      </section>
      <Policy title={text("9. Beveiliging, kinderen en wijzigingen", "9. Security, children and changes")}>{text("We gebruiken onder meer toegangsrollen, afgeschermde serverfuncties, beperkte publieke velden en versleuteld transport. Geen beveiliging is absoluut. De dienst is niet gericht op kinderen jonger dan 16 jaar. Bij wezenlijke wijzigingen passen we de versiedatum aan en informeren we actieve gebruikers waar nodig.", "We use access roles, protected server functions, limited public fields and encrypted transport, among other measures. No security is absolute. The service is not directed at children under 16. For material changes, we update the version date and notify active users where needed.")}</Policy>
    </CardContent></Card>
    <div className="flex flex-wrap gap-3"><Button type="button" variant="outline" onClick={openPrivacyChoices}>{text("Privacykeuzes wijzigen", "Change privacy choices")}</Button>{user && <Button asChild><Link to="/account"><FileDown className="size-4" /> {text("Exporteren of verwijderen", "Export or delete")}</Link></Button>}<Button asChild variant="outline"><a href="https://autoriteitpersoonsgegevens.nl/een-tip-of-klacht-indienen-bij-de-ap" target="_blank" rel="noreferrer"><Scale className="size-4" /> Autoriteit Persoonsgegevens</a></Button></div>
  </div>;
}

function Policy({ title, children }: { title: string; children: ReactNode }) { return <section><h2 className="font-display text-lg font-semibold">{title}</h2><div className="mt-2 text-sm leading-relaxed text-muted-foreground">{children}</div></section>; }
function StorageRow({ name, purpose, category, retention }: { name: string; purpose: string; category: string; retention: string }) { return <tr className="border-b align-top"><td className="p-2 font-mono text-foreground">{name}</td><td className="p-2">{purpose}</td><td className="p-2">{category}</td><td className="p-2">{retention}</td></tr>; }
