import { createFileRoute, Link } from "@tanstack/react-router";
import { Database, FileDown, LockKeyhole, Scale, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";
import { useLocale } from "@/lib/locale";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacy — GlobeTrotr" }, { name: "description", content: "Privacyverklaring van GlobeTrotr." }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const { user } = useAuth();
  const { text } = useLocale();
  const overview = [
    { icon: Database, title: text("Wat we verwerken", "What we process"), body: text("Account- en profielgegevens, reisinhoud, samenwerkingen, uitgaven, uploads, voorkeuren en technische beveiligingsgegevens.", "Account and profile details, trip content, collaboration data, expenses, uploads, preferences and technical security data.") },
    { icon: LockKeyhole, title: text("Waarom", "Why"), body: text("Om je account en reisplanner te leveren, samenwerkingen uit te voeren, de dienst te beveiligen en aan wettelijke verplichtingen te voldoen.", "To provide your account and trip planner, enable collaboration, secure the service and meet legal obligations.") },
    { icon: FileDown, title: text("Jouw controle", "Your control"), body: text("Pas gegevens aan, download een machineleesbare export of verwijder je account vanuit Accountinstellingen.", "Edit data, download a machine-readable export or delete your account from Account settings.") },
  ];
  return <div className="mx-auto max-w-4xl space-y-8">
    <header className="aurora rounded-3xl px-6 py-10 sm:px-10 sm:py-14">
      <Badge variant="secondary" className="mb-4 gap-1.5"><ShieldCheck className="size-3.5" /> AVG / GDPR</Badge>
      <h1 className="font-display text-3xl font-semibold sm:text-5xl">{text("Jouw reis, jouw gegevens", "Your trip, your data")}</h1>
      <p className="mt-4 max-w-2xl text-sm leading-relaxed opacity-90 sm:text-base">{text("Deze privacyverklaring legt uit hoe GlobeTrotr persoonsgegevens verwerkt tijdens de internationale beta. Laatst bijgewerkt op 8 september 2026.", "This privacy notice explains how GlobeTrotr processes personal data during the international beta. Last updated 8 September 2026.")}</p>
    </header>
    <div className="grid gap-4 md:grid-cols-3">{overview.map(({ icon: Icon, title, body }) => <Card key={title} className="surface"><CardContent className="p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p></CardContent></Card>)}</div>
    <Card className="surface"><CardContent className="space-y-7 p-6 sm:p-8">
      <Policy title={text("1. Wie is verantwoordelijk?", "1. Who is responsible?")}>{text("GlobeTrotr is de verwerkingsverantwoordelijke voor persoonsgegevens in deze dienst. Tijdens de besloten beta bereik je GlobeTrotr via het contactkanaal waarmee je bent uitgenodigd. Vermeld bij een privacyverzoek het e-mailadres van je account, maar stuur nooit je wachtwoord.", "GlobeTrotr is the controller for personal data in this service. During the closed beta, contact GlobeTrotr through the channel used for your invitation. Include your account email with a privacy request, but never send your password.")}</Policy>
      <Policy title={text("2. Gegevens, doelen en grondslagen", "2. Data, purposes and legal bases")}><ul className="list-disc space-y-2 pl-5"><li>{text("Account, profiel, voorkeuren en authenticatie: nodig om de overeenkomst uit te voeren en je account te beveiligen.", "Account, profile, preferences and authentication: necessary to perform the agreement and secure your account.")}</li><li>{text("Reizen, routes, planning, reisgenoten, boekingsnotities, uitgaven en uploads: nodig om de door jou gekozen functies te leveren.", "Trips, routes, itineraries, travellers, booking notes, expenses and uploads: necessary to provide the features you choose.")}</li><li>{text("Beveiligings- en foutgegevens: gerechtvaardigd belang om misbruik te voorkomen, fouten te onderzoeken en de dienst betrouwbaar te houden.", "Security and error data: legitimate interest in preventing abuse, investigating errors and keeping the service reliable.")}</li><li>{text("Openbaar delen: je eigen keuze, die je altijd kunt uitschakelen. Financiële informatie vereist een afzonderlijke keuze.", "Public sharing: your choice, which you can disable at any time. Financial information requires a separate choice.")}</li></ul></Policy>
      <Policy title={text("3. Delen, verwerkers en doorgifte", "3. Sharing, processors and transfers")}>{text("Gegevens zijn alleen beschikbaar voor jou, reisleden volgens hun rol, bezoekers van een door jou openbaar gemaakte reis en dienstverleners die nodig zijn voor hosting, database, authenticatie, opslag, kaarten, weer, valuta en vluchtinformatie. GlobeTrotr verkoopt geen persoonsgegevens. Bij verwerking buiten de EER moeten passende AVG-waarborgen gelden, zoals een adequaatheidsbesluit of standaardcontractbepalingen.", "Data is only available to you, trip members according to their role, visitors to a trip you publish, and providers required for hosting, database, authentication, storage, maps, weather, currencies and flight information. GlobeTrotr does not sell personal data. Processing outside the EEA must use appropriate GDPR safeguards, such as an adequacy decision or standard contractual clauses.")}</Policy>
      <Policy title={text("4. Openbare reizen en gegevens van anderen", "4. Public trips and other people's data")}>{text("Reizen zijn standaard privé. Deel alleen gegevens waarvoor je toestemming of een andere geldige reden hebt, zeker bij namen, contactgegevens, boekingsgegevens en bonnetjes van reisgenoten. Ontvangers kunnen openbare links doorsturen. Schakel openbaar delen uit zodra het niet meer nodig is.", "Trips are private by default. Only share data when you have permission or another valid reason, especially names, contact details, booking information and receipts belonging to fellow travellers. Recipients can forward public links. Disable public sharing when it is no longer needed.")}</Policy>
      <Policy title={text("5. Bewaren en verwijderen", "5. Retention and deletion")}>{text("Account- en reisgegevens blijven bewaard zolang je account actief is. Bij accountverwijdering worden je account, eigen reizen en uploads uit de actieve dienst verwijderd. Technische back-ups kunnen gedurende een beperkte herstelperiode blijven bestaan en worden daarna overschreven. Gegevens kunnen langer worden bewaard wanneer een wettelijke plicht, geschil of beveiligingsonderzoek dit vereist.", "Account and trip data are retained while your account is active. Account deletion removes your account, owned trips and uploads from the active service. Technical backups may remain for a limited recovery period and are then overwritten. Data may be retained longer where required by law, a dispute or a security investigation.")}</Policy>
      <Policy title={text("6. Jouw AVG-rechten", "6. Your GDPR rights")}>{text("Je hebt, waar van toepassing, recht op informatie, inzage, correctie, verwijdering, beperking, overdraagbaarheid en bezwaar. Je kunt toestemming intrekken zonder dat dit eerdere verwerking ongeldig maakt. GlobeTrotr gebruikt geen uitsluitend geautomatiseerde besluitvorming met rechtsgevolgen. We kunnen je identiteit controleren en reageren in beginsel binnen één maand. Verzoeken zijn normaal gratis.", "Where applicable, you have rights to information, access, correction, deletion, restriction, portability and objection. You can withdraw consent without affecting earlier processing. GlobeTrotr does not use solely automated decision-making with legal effects. We may verify your identity and generally respond within one month. Requests are normally free.")}</Policy>
      <Policy title={text("7. Beveiliging, cookies en kinderen", "7. Security, cookies and children")}>{text("GlobeTrotr gebruikt toegangsrollen, afgeschermde serverfuncties en beperkte openbare gegevens. Meld een vermoedelijk datalek direct via het beta-contactkanaal. Deze beta gebruikt geen advertentie- of marketingcookies; lokale opslag en sessiegegevens dienen voor inloggen, taal, weergave en appwerking. De dienst is niet gericht op kinderen jonger dan 16 jaar.", "GlobeTrotr uses access roles, protected server functions and limited public data. Report a suspected breach immediately through the beta contact channel. This beta uses no advertising or marketing cookies; local storage and session data support sign-in, language, appearance and app operation. The service is not directed at children under 16.")}</Policy>
      <Policy title={text("8. Klacht en wijzigingen", "8. Complaints and changes")}><span>{text("Neem bij vragen eerst contact op met GlobeTrotr. Je mag ook een klacht indienen bij de ", "Contact GlobeTrotr first with questions. You may also lodge a complaint with the ")}<a className="text-primary underline underline-offset-4" href="https://autoriteitpersoonsgegevens.nl/een-tip-of-klacht-indienen-bij-de-ap" target="_blank" rel="noreferrer">Autoriteit Persoonsgegevens</a>{text(". Bij belangrijke wijzigingen passen we de datum bovenaan aan en informeren we actieve gebruikers waar passend.", ". For material changes, we update the date above and inform active users where appropriate.")}</span></Policy>
    </CardContent></Card>
    <div className="flex flex-wrap gap-3">{user && <Button asChild><Link to="/account"><FileDown className="size-4" /> {text("Exporteren of verwijderen", "Export or delete")}</Link></Button>}<Button asChild variant="outline"><a href="https://eur-lex.europa.eu/legal-content/NL/TXT/?uri=CELEX:32016R0679" target="_blank" rel="noreferrer"><Scale className="size-4" /> {text("Lees de AVG", "Read the GDPR")}</a></Button></div>
  </div>;
}

function Policy({ title, children }: { title: string; children: ReactNode }) { return <section><h2 className="font-display text-lg font-semibold">{title}</h2><div className="mt-2 text-sm leading-relaxed text-muted-foreground">{children}</div></section>; }
