import { createFileRoute, Link } from "@tanstack/react-router";
import { RotateCcw } from "lucide-react";
import { LegalPage, LegalSection } from "@/components/LegalPage";
import { useLocale } from "@/lib/locale";

export const Route=createFileRoute("/terugbetalingsbeleid")({head:()=>({meta:[{title:"Terugbetalingsbeleid — GlobeTrotr"},{name:"description",content:"Opzegging, herroeping en terugbetalingen bij GlobeTrotr."}]}),component:RefundPage});
function RefundPage(){const{text}=useLocale();return <LegalPage icon={RotateCcw} badge={text("Opzeggen en terugbetalen","Cancellation and refunds")} title={text("Terugbetalingsbeleid","Refund policy")} intro={text("Heldere afspraken voor de gratis beta en voor abonnementen zodra betaalde plannen beschikbaar komen.","Clear arrangements for the free beta and for subscriptions once paid plans become available.")} version={text("Versie 11 september 2026","Version 11 September 2026")}>
  <LegalSection title={text("1. Huidige gratis beta","1. Current free beta")}><p>{text("Tijdens de huidige beta verwerkt GlobeTrotr geen abonnementskosten. Er is daarom geen betaald bedrag om terug te betalen. Een planwijziging in de testomgeving verandert alleen beschikbare functies.","During the current beta, GlobeTrotr does not process subscription charges. There is therefore no paid amount to refund. A plan change in the test environment only changes available features.")}</p></LegalSection>
  <LegalSection title={text("2. Betaalde abonnementen","2. Paid subscriptions")}><p>{text("Zodra betalingen live zijn, kun je een abonnement opzeggen vóór de volgende verlenging. De opzegging stopt toekomstige afschrijvingen en toegang blijft normaal beschikbaar tot het einde van de reeds betaalde periode. Alleen stoppen met gebruiken of je account verwijderen annuleert niet automatisch een extern verwerkt abonnement; de accountflow zal je daarom naar de juiste opzegstap leiden.","Once payments are live, you can cancel a subscription before the next renewal. Cancellation stops future charges and access normally remains available until the end of the paid period. Merely stopping use or deleting your account does not automatically cancel an externally processed subscription; the account flow will therefore direct you to the correct cancellation step.")}</p></LegalSection>
  <LegalSection title={text("3. Wettelijke bedenktijd voor consumenten","3. Statutory cooling-off period for consumers")}><p>{text("Een consument die online een dienstenovereenkomst sluit, kan deze in beginsel binnen 14 dagen na het sluiten zonder reden herroepen. Vraag je uitdrukkelijk om directe uitvoering tijdens de bedenktijd, dan kan bij herroeping een evenredige vergoeding gelden voor het reeds geleverde deel. Is de dienst volledig uitgevoerd na jouw uitdrukkelijke voorafgaande instemming en erkenning, dan kan het herroepingsrecht eindigen voor zover de wet dat toestaat.","A consumer entering an online services contract can generally withdraw without reason within 14 days after conclusion. If you expressly request immediate performance during the cooling-off period, a proportionate charge may apply for the part already supplied when you withdraw. If the service has been fully performed following your express prior consent and acknowledgement, the right of withdrawal may end to the extent permitted by law.")}</p></LegalSection>
  <LegalSection title={text("4. Een verzoek indienen","4. Submit a request")}><p>{text("Gebruik na betaalactivatie bij voorkeur de contact- of terugbetalingsmogelijkheid van Paddle die bij de transactie of op het betalingsbewijs staat, omdat Paddle de verkoper en betaalpartij is. Je kunt ook binnen de toepasselijke termijn een ondubbelzinnige verklaring naar info@globetrotr.nl sturen; GlobeTrotr helpt het verzoek dan bij Paddle af te handelen. Vermeld het e-mailadres van je account en het transactie- of factuurnummer, maar nooit een wachtwoord of volledige betaalkaartgegevens. Je mag schrijven: ‘Hierbij herroep ik mijn GlobeTrotr-abonnement dat ik op [datum] via Paddle heb afgesloten.’","After payments go live, preferably use Paddle's contact or refund option shown with the transaction or on the receipt, because Paddle is the seller and payment party. You may also send an unambiguous statement within the applicable period to info@globetrotr.nl; GlobeTrotr will then help process the request with Paddle. Include your account email and transaction or invoice number, but never a password or full card details. You may write: ‘I hereby withdraw from my GlobeTrotr subscription concluded through Paddle on [date].’")}</p></LegalSection>
  <LegalSection title={text("5. Andere terugbetalingen","5. Other refunds")}><p>{text("Neem contact op bij een dubbele of onjuiste afschrijving, ongeautoriseerde betaling of wanneer een betaalde dienst door een aan GlobeTrotr toe te rekenen technisch probleem wezenlijk niet kon worden gebruikt. We beoordelen het verzoek op de transactie, het gebruik en toepasselijk recht. Dit beleid beperkt geen wettelijke rechten op prijsvermindering, herstel, beëindiging of schadevergoeding bij een gebrekkige digitale dienst.","Contact us for a duplicate or incorrect charge, unauthorised payment, or where a paid service was materially unusable due to a technical issue attributable to GlobeTrotr. We assess the request based on the transaction, use and applicable law. This policy does not limit statutory rights to price reduction, remedy, termination or compensation for a defective digital service.")}</p></LegalSection>
  <LegalSection title={text("6. Uitbetaling door Paddle","6. Payment by Paddle")}><p>{text("Paddle voert als Merchant of Record de verschuldigde volledige of gedeeltelijke terugbetaling uit, in beginsel via dezelfde betaalmethode en uiterlijk binnen de toepasselijke wettelijke termijn. Nadat Paddle de terugbetaling heeft verwerkt, hangt de zichtbaarheid op je rekening af van de betaalmethode en bank. De actuele Paddle-kopersvoorwaarden en het Paddle-terugbetalingsbeleid bij de checkout blijven van toepassing en wettelijke consumentenrechten gaan altijd voor.","As Merchant of Record, Paddle issues any full or partial refund due, generally through the same payment method and no later than the applicable statutory deadline. After Paddle processes the refund, the time it appears in your account depends on the payment method and bank. Paddle's current buyer terms and refund policy shown at checkout remain applicable, and statutory consumer rights always prevail.")}</p></LegalSection>
  <LegalSection title={text("7. Contact","7. Contact")}><p>GlobeTrotr<br/>{text("Postadres (geen bezoekadres):","Postal address (not a visiting address):")} Gedempte Oude Gracht 95, 2011 GT Haarlem<br/><a className="text-primary underline" href="mailto:info@globetrotr.nl">info@globetrotr.nl</a></p><p><Link to="/algemene-voorwaarden" className="text-primary underline">{text("Algemene voorwaarden","Terms and conditions")}</Link>{" · "}<Link to="/prijzen" className="text-primary underline">{text("Prijzen","Pricing")}</Link></p></LegalSection>
</LegalPage>}
