import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, RotateCcw, Save, ShieldCheck, UserCog } from "lucide-react";
import { toast } from "sonner";
import { getAgencyPermissions, getAgencyTeam, saveAgencyMemberPermissions, saveAgencyRolePermissions } from "@/lib/agency.functions";
import { AGENCY_PERMISSIONS, effectiveAgencyPermissions, type AgencyPermission, type AgencyPermissionMap, type AgencyPermissionOverrides } from "@/lib/agency-permissions";
import { useLocale } from "@/lib/locale";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";

export const Route=createFileRoute("/_authenticated/agency-admin/permissions")({head:()=>({meta:[{title:"Agency-rechten — GlobeTrotr"}]}),component:AgencyPermissionsPage});
function AgencyPermissionsPage(){
 const {text}=useLocale(); const permissions=useQuery({queryKey:["agency-permissions"],queryFn:()=>getAgencyPermissions(),retry:false}); const team=useQuery({queryKey:["agency-team"],queryFn:()=>getAgencyTeam(),retry:false}); const [busy,setBusy]=useState(""); const [selectedUser,setSelectedUser]=useState("");
 useEffect(()=>{if(!selectedUser&&permissions.data?.members[0])setSelectedUser(permissions.data.members[0].userId)},[permissions.data,selectedUser]);
 async function saveRole(role:"advisor"|"finance",map:AgencyPermissionMap){setBusy(role);try{await saveAgencyRolePermissions({data:{role,permissions:map}});await permissions.refetch();toast.success(text("Standaardrechten opgeslagen.","Default permissions saved."));}catch{toast.error(text("Rechten konden niet worden opgeslagen.","Permissions could not be saved."));}finally{setBusy("")}}
 async function saveMember(userId:string,overrides:AgencyPermissionOverrides){setBusy(userId);try{await saveAgencyMemberPermissions({data:{userId,overrides}});await permissions.refetch();toast.success(text("Gebruikersrechten opgeslagen.","User permissions saved."));}catch{toast.error(text("Gebruikersrechten konden niet worden opgeslagen.","User permissions could not be saved."));}finally{setBusy("")}}
 if(permissions.isError)return <Card className="surface"><CardContent className="p-6"><h1 className="font-display text-xl font-semibold">{text("Rechtenbeheer nog niet beschikbaar","Permission management not available yet")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Dit scherm wordt actief nadat de Agency-rechtenmigratie later is uitgevoerd.","This screen becomes active after the Agency permissions migration is applied later.")}</p></CardContent></Card>;
 return <div className="space-y-6"><header><Button asChild variant="ghost" size="sm" className="mb-2 -ml-3"><Link to="/agency-admin"><ArrowLeft className="size-4"/>Agency Admin</Link></Button><h1 className="flex items-center gap-2 font-display text-3xl font-semibold"><ShieldCheck className="size-7 text-primary"/>{text("Rollen en rechten","Roles and permissions")}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{text("Stel eerst de standaardrechten per Agency-rol in. Geef daarna alleen waar nodig een afzonderlijke gebruiker een afwijking.","Set default permissions for each Agency role first. Then add a user-specific exception only where needed.")}</p></header>
 <section className="grid gap-5 lg:grid-cols-2">{(["advisor","finance"] as const).map(role=><RoleCard key={role} role={role} initial={permissions.data?.roles[role]??effectiveAgencyPermissions(role)} busy={busy===role} onSave={map=>void saveRole(role,map)} text={text}/>)}</section>
 <section><h2 className="mb-3 flex items-center gap-2 font-display text-xl font-semibold"><UserCog className="size-5 text-primary"/>{text("Afwijkingen per gebruiker","Exceptions per user")}</h2>{permissions.data?.members.length?<div className="space-y-4"><label className="block max-w-xl space-y-1 text-sm"><span className="text-muted-foreground">{text("Kies een teamlid","Choose a team member")}</span><select className="h-10 w-full rounded-md border bg-background px-3" value={selectedUser} onChange={event=>setSelectedUser(event.target.value)}>{permissions.data.members.map(member=>{const profile=team.data?.members.find(item=>item.userId===member.userId);return <option key={member.userId} value={member.userId}>{profile?.name||profile?.email||member.userId} · {member.role}</option>})}</select></label>{permissions.data.members.filter(member=>member.userId===selectedUser).map(member=>{const profile=team.data?.members.find(item=>item.userId===member.userId);return <MemberCard key={member.userId} name={profile?.name||profile?.email||member.userId} role={member.role} defaults={permissions.data!.roles[member.role]} initial={member.overrides} busy={busy===member.userId} onSave={map=>void saveMember(member.userId,map)} text={text}/>})}</div>:permissions.data&&<p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">{text("Nodig eerst een Advisor of Finance-teamlid uit.","Invite an Advisor or Finance team member first.")}</p>}</section></div>;
}
function RoleCard({role,initial,busy,onSave,text}:{role:"advisor"|"finance";initial:AgencyPermissionMap;busy:boolean;onSave:(map:AgencyPermissionMap)=>void;text:(nl:string,en:string)=>string}){const [map,setMap]=useState(initial);return <Card className="surface"><CardHeader><CardTitle>{role==="advisor"?"Advisor":"Finance"}</CardTitle></CardHeader><CardContent className="space-y-3">{AGENCY_PERMISSIONS.map(permission=><PermissionRow key={permission} permission={permission} checked={map[permission]} onChecked={checked=>setMap({...map,[permission]:checked})} text={text}/>)}<Button className="mt-2 w-full" disabled={busy} onClick={()=>onSave(map)}><Save className="size-4"/>{text("Rolrechten opslaan","Save role permissions")}</Button></CardContent></Card>}
function MemberCard({name,role,defaults,initial,busy,onSave,text}:{name:string;role:"advisor"|"finance";defaults:AgencyPermissionMap;initial:AgencyPermissionOverrides;busy:boolean;onSave:(map:AgencyPermissionOverrides)=>void;text:(nl:string,en:string)=>string}){const [map,setMap]=useState(initial);return <Card className="surface"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">{name}</CardTitle><p className="text-xs text-muted-foreground">{role==="advisor"?"Advisor":"Finance"} · {Object.keys(map).length} {text("afwijkingen","exceptions")}</p></div><Button variant="ghost" size="sm" onClick={()=>setMap({})}><RotateCcw className="size-4"/>{text("Rolstandaard","Role defaults")}</Button></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{AGENCY_PERMISSIONS.map(permission=>{const inherited=map[permission]===undefined;const checked=map[permission]??defaults[permission];return <div key={permission} className="rounded-xl border p-3"><PermissionRow permission={permission} checked={checked} onChecked={value=>setMap({...map,[permission]:value})} text={text}/><button className="mt-1 text-xs text-muted-foreground underline disabled:no-underline" disabled={inherited} onClick={()=>{const next={...map};delete next[permission];setMap(next)}}>{inherited?text("Volgt rolstandaard","Uses role default"):text("Afwijking verwijderen","Remove exception")}</button></div>})}<Button className="md:col-span-2" disabled={busy} onClick={()=>onSave(map)}><Save className="size-4"/>{text("Gebruikersrechten opslaan","Save user permissions")}</Button></CardContent></Card>}
function PermissionRow({permission,checked,onChecked,text}:{permission:AgencyPermission;checked:boolean;onChecked:(value:boolean)=>void;text:(nl:string,en:string)=>string}){const labels:Record<AgencyPermission,[string,string]>={trips_view:["Reizen bekijken","View trips"],trips_create:["Reizen aanmaken","Create trips"],trips_plan:["Planning en boekingen wijzigen","Edit planning and bookings"],expenses_manage:["Uitgaven beheren","Manage expenses"],trip_settings_manage:["Reisinstellingen en publicatie","Trip settings and publication"],members_manage:["Reisgenoten beheren","Manage travellers"],analytics_view:["Analyses bekijken","View analytics"],branding_manage:["Branding beheren","Manage branding"],billing_manage:["Abonnement beheren","Manage billing"]};return <label className="flex items-center justify-between gap-3 text-sm"><span>{text(...labels[permission])}</span><Switch checked={checked} onCheckedChange={onChecked}/></label>}
