import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Building2, ImagePlus, Loader2, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { getAgencySettings, saveAgencySettings, type AgencySettings } from "@/lib/agency.functions";
import { useLocale } from "@/lib/locale";
import { useWorkspace } from "@/lib/workspace";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";

export const Route=createFileRoute("/_authenticated/agency-admin/settings")({head:()=>({meta:[{title:"Agency-instellingen — GlobeTrotr"}]}),component:AgencySettingsPage});
function AgencySettingsPage(){
 const {text}=useLocale(); const {refreshWorkspace}=useWorkspace(); const query=useQuery({queryKey:["agency-settings"],queryFn:()=>getAgencySettings(),retry:false});
 const [form,setForm]=useState<AgencySettings|null>(null); const [busy,setBusy]=useState(""); const [logoUrl,setLogoUrl]=useState<string>();
 useEffect(()=>{if(query.data)setForm(query.data)},[query.data]);
 useEffect(()=>{if(!form?.logoPath){setLogoUrl(undefined);return} void supabase.storage.from("agency-logos").createSignedUrl(form.logoPath,3600).then(({data})=>setLogoUrl(data?.signedUrl?`${data.signedUrl}&v=${Date.now()}`:undefined));},[form?.logoPath]);
 const set=<K extends keyof AgencySettings>(key:K,value:AgencySettings[K])=>setForm(old=>old?{...old,[key]:value}:old);
 async function save(){if(!form)return;setBusy("save");try{const {workspaceId,...settings}=form;const result=await saveAgencySettings({data:settings});await Promise.all([query.refetch(),refreshWorkspace()]);toast.success(result.restored.length?text("Lege verplichte waarden zijn veilig hersteld en opgeslagen.","Empty required values were safely restored and saved."):text("Agency-instellingen opgeslagen en direct toegepast.","Agency settings saved and applied immediately."));}catch{toast.error(text("Controleer de verplichte velden.","Check the required fields."));}finally{setBusy("")}}
 async function upload(file?:File){if(!file||!form)return;if(file.size>2097152||!["image/png","image/jpeg","image/webp"].includes(file.type)){toast.error(text("Gebruik PNG, JPG of WebP van maximaal 2 MB.","Use PNG, JPG or WebP up to 2 MB."));return}setBusy("logo");const previous=form.logoPath;try{const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const path=`${form.workspaceId}/logo-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("agency-logos").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const next={...form,logoPath:path};const {workspaceId,...settings}=next;await saveAgencySettings({data:settings});setForm(next);if(previous)await supabase.storage.from("agency-logos").remove([previous]);await Promise.all([query.refetch(),refreshWorkspace()]);toast.success(text("Logo geüpload en direct toegepast.","Logo uploaded and applied immediately."));}catch{toast.error(text("Logo kon niet worden geüpload.","Logo could not be uploaded."));}finally{setBusy("")}}
 async function removeLogo(){if(!form?.logoPath)return;setBusy("logo");const previous=form.logoPath;try{const next={...form,logoPath:null};const {workspaceId,...settings}=next;await saveAgencySettings({data:settings});const {error}=await supabase.storage.from("agency-logos").remove([previous]);if(error)throw error;setForm(next);setLogoUrl(undefined);await Promise.all([query.refetch(),refreshWorkspace()]);toast.success(text("Logo verwijderd en direct toegepast.","Logo removed and applied immediately."));}catch{toast.error(text("Logo kon niet worden verwijderd.","Logo could not be removed."));}finally{setBusy("")}}
 if(query.isLoading)return <p className="flex gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>{text("Instellingen laden…","Loading settings…")}</p>;
 if(query.isError||!form)return <Card className="surface"><CardContent className="p-6"><h1 className="font-display text-xl font-semibold">{text("Agency-instellingen nog niet beschikbaar","Agency settings not available yet")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Deze pagina wordt actief nadat de Agency-migraties later zijn uitgevoerd.","This page becomes active after the Agency migrations are applied later.")}</p><Button asChild variant="outline" className="mt-4"><Link to="/agency-admin"><ArrowLeft className="size-4"/>{text("Terug","Back")}</Link></Button></CardContent></Card>;
 return <div className="space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><Button asChild variant="ghost" size="sm" className="mb-2 -ml-3"><Link to="/agency-admin"><ArrowLeft className="size-4"/>Agency Admin</Link></Button><h1 className="flex items-center gap-2 font-display text-3xl font-semibold"><Building2 className="size-7 text-primary"/>{text("Workspace-instellingen","Workspace settings")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Organisatiegegevens en merkuitstraling op één veilige plaats.","Organisation details and brand appearance in one secure place.")}</p></div><Button disabled={Boolean(busy)} onClick={()=>void save()}><Save className="size-4"/>{text("Wijzigingen opslaan","Save changes")}</Button></header>
 <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-5"><Card className="surface"><CardHeader><CardTitle>{text("Algemeen","General")}</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label={text("Systeemnaam","System name")} value={form.systemName} max={50} onChange={v=>set("systemName",v)}/><Field label={text("Afzendernaam","Sender name")} value={form.senderName} max={60} onChange={v=>set("senderName",v)}/><Field label={text("Contactadres","Contact email")} value={form.contactEmail} max={254} type="email" onChange={v=>set("contactEmail",v)}/><Field label={text("Domein","Domain")} value={form.domain} max={120} onChange={v=>set("domain",v)}/><label className="space-y-1 text-sm"><span>{text("Standaardtaal","Default language")}</span><select className="h-10 w-full rounded-md border bg-background px-3" value={form.defaultLocale} onChange={e=>set("defaultLocale",e.target.value as "nl"|"en")}><option value="nl">Nederlands</option><option value="en">English</option></select></label><Field label={text("Valuta","Currency")} value={form.currency} max={3} onChange={v=>set("currency",v.toUpperCase())}/><Field label={text("Tijdzone","Timezone")} value={form.timezone} max={50} onChange={v=>set("timezone",v)}/></CardContent></Card>
 <Card className="surface"><CardHeader><CardTitle>{text("Merkuitstraling","Brand appearance")}</CardTitle></CardHeader><CardContent className="space-y-5"><Field label="Tagline" value={form.tagline} max={120} onChange={v=>set("tagline",v)}/><div><span className="flex justify-between text-sm"><span>{text("Accentkleur","Accent colour")}</span><span>{form.accent}°</span></span><Slider className="mt-3" min={0} max={360} value={[form.accent]} onValueChange={v=>set("accent",v[0]??172)}/></div><div><p className="mb-2 text-sm font-medium">Logo</p><div className="flex flex-wrap items-center gap-3">{logoUrl?<img src={logoUrl} alt="Agency logo" className="h-16 w-32 rounded-xl border bg-white object-contain p-2"/>:<div className="flex h-16 w-32 items-center justify-center rounded-xl border border-dashed text-xs text-muted-foreground">{text("Geen logo","No logo")}</div>}<label><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])}/><span className="inline-flex h-9 cursor-pointer items-center gap-2 rounded-md border px-3 text-sm"><ImagePlus className="size-4"/>{text("Logo kiezen","Choose logo")}</span></label>{form.logoPath&&<Button variant="ghost" size="sm" onClick={()=>void removeLogo()}><Trash2 className="size-4"/>{text("Verwijderen","Remove")}</Button>}</div><p className="mt-2 text-xs text-muted-foreground">PNG, JPG or WebP · max. 2 MB</p></div></CardContent></Card></div>
 <Card className="surface h-fit"><CardHeader><CardTitle>{text("Live voorbeeld","Live preview")}</CardTitle></CardHeader><CardContent><div className="rounded-3xl border p-6" style={{borderColor:`hsl(${form.accent} 70% 45% / .45)`,background:`linear-gradient(135deg,hsl(${form.accent} 70% 45% / .16),transparent)`}}>{logoUrl&&<img src={logoUrl} alt="" className="mb-5 h-14 max-w-40 object-contain"/>}<p className="text-xs text-muted-foreground">{form.domain||"globetrotr.nl"}</p><h2 className="mt-1 break-words font-display text-2xl font-semibold">{form.systemName||"GlobeTrotr Agency"}</h2><p className="mt-2 break-words text-sm text-muted-foreground">{form.tagline||"Plan elke reis. Verantwoord elke euro."}</p><Button className="mt-6" style={{backgroundColor:`hsl(${form.accent} 65% 42%)`}}>{text("Bekijk reis","View trip")}</Button></div></CardContent></Card></div></div>;
}
function Field({label,value,max,onChange,type="text"}:{label:string;value:string;max:number;onChange:(value:string)=>void;type?:string}){return <label className="space-y-1 text-sm"><span className="flex justify-between gap-2"><span>{label}</span><span className="text-xs text-muted-foreground">{value.length}/{max}</span></span><Input type={type} value={value} maxLength={max} onChange={e=>onChange(e.target.value)}/></label>}
