import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Archive, Building2, CheckCircle2, CreditCard, Globe2, Plane, Users } from "lucide-react";
import { getAgencyUsage } from "@/lib/agency.functions";
import { useLocale } from "@/lib/locale";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const Route=createFileRoute("/_authenticated/agency-admin/subscription")({head:()=>({meta:[{title:"Agency-abonnement — GlobeTrotr"}]}),component:AgencySubscriptionPage});
function AgencySubscriptionPage(){const{text}=useLocale();const query=useQuery({queryKey:["agency-usage"],queryFn:()=>getAgencyUsage(),retry:false});if(query.isLoading)return <p className="text-sm text-muted-foreground">{text("Abonnement laden…","Loading subscription…")}</p>;if(!query.data)return <Card className="surface"><CardContent className="p-6 text-sm text-muted-foreground">{text("Abonnementsgegevens konden niet worden geladen.","Subscription data could not be loaded.")}</CardContent></Card>;const usage=query.data;return <div className="space-y-6"><header><h1 className="flex items-center gap-2 font-display text-3xl font-semibold"><CreditCard className="size-7 text-primary"/>{text("Abonnement en gebruik","Subscription and usage")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Actuele gegevens uit deze Agency-workspace.","Current data from this Agency workspace.")}</p></header><Card className="border-primary/30 surface"><CardContent className="flex flex-wrap items-center justify-between gap-4 p-6"><div><div className="flex items-center gap-2"><h2 className="font-display text-2xl font-semibold">GlobeTrotr Agency</h2><Badge><CheckCircle2 className="mr-1 size-3"/>{text("Actief","Active")}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{text("Gedeelde workspace, rollen, klantenbeheer en eigen huisstijl.","Shared workspace, roles, client management and custom branding.")}</p></div><Button asChild variant="outline"><Link to="/billing">{text("Alle plannen bekijken","View all plans")}</Link></Button></CardContent></Card><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric icon={Users} value={usage.teamMembers} label={text("Actieve teamleden","Active team members")}/><Metric icon={Building2} value={usage.activeClients} label={text("Actieve klanten","Active clients")}/><Metric icon={Plane} value={usage.activeTrips} label={text("Actieve reizen","Active trips")}/><Metric icon={Globe2} value={usage.publicTrips} label={text("Openbare reizen","Public trips")}/><Metric icon={Archive} value={usage.archivedTrips} label={text("Gearchiveerde reizen","Archived trips")}/><Metric icon={Users} value={usage.pendingInvitations} label={text("Open uitnodigingen","Pending invitations")}/></div><Card className="surface"><CardHeader><CardTitle>{text("Facturatie","Billing")}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{text("Online betalingen, facturen en automatische abonnementswijzigingen worden hier beschikbaar zodra Paddle veilig is aangesloten. Tot die tijd worden geen bedragen of facturen gesimuleerd.","Online payments, invoices and automatic subscription changes will become available here after Paddle is connected securely. No amounts or invoices are simulated in the meantime.")}</p></CardContent></Card></div>}
function Metric({icon:Icon,value,label}:{icon:typeof Users;value:number;label:string}){return <Card className="surface"><CardContent className="flex items-center gap-3 p-5"><span className="rounded-full bg-primary/10 p-2 text-primary"><Icon className="size-5"/></span><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
