import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { BarChart3, Building2, Copy, CreditCard, Lock, MailPlus, MoreHorizontal, Palette, Route as RouteIcon, Settings2, ShieldCheck, UserCog, Users } from "lucide-react";
import { toast } from "sonner";
import { createAgencyInvitation, getAgencyTeam, getMyAgencyAccess, manageAgencyInvitation, manageAgencyMember, type AgencyRole } from "@/lib/agency.functions";
import { useWorkspace } from "@/lib/workspace";
import { useLocale } from "@/lib/locale";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route = createFileRoute("/_authenticated/agency-admin/")({ head: () => ({ meta: [{ title: "Agency Admin — GlobeTrotr" }] }), component: AgencyAdminPage });

function AgencyAdminPage() {
  const { state } = useWorkspace();
  const { text, locale } = useLocale();
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"advisor" | "finance">("advisor");
  const [busy, setBusy] = useState("");
  const [inviteOpen, setInviteOpen] = useState(false);
  const access = useQuery({ queryKey: ["my-agency-access"], queryFn: () => getMyAgencyAccess(), enabled: state.plan === "agency", retry: false });
  const canManageMembers = access.data?.permissions.members_manage === true;
  const team = useQuery({ queryKey: ["agency-team"], queryFn: () => getAgencyTeam(), enabled: canManageMembers, retry: false });
  if (state.plan !== "agency" || access.isError) return <Card className="surface"><CardContent className="flex gap-3 p-6"><Lock className="size-5 shrink-0 text-primary"/><div><h1 className="font-display text-xl font-semibold">Agency Admin</h1><p className="mt-1 text-sm text-muted-foreground">{text("Dit dashboard vereist een actieve rol binnen een Agency-workspace.","This dashboard requires an active role in an Agency workspace.")}</p></div></CardContent></Card>;
  if (!access.data) return <p className="text-sm text-muted-foreground">{text("Agency-dashboard laden…","Loading Agency dashboard…")}</p>;
  const activeTrips = state.trips.filter((trip) => !trip.archived).length;

  async function invite() {
    setBusy("invite");
    try { const result = await createAgencyInvitation({ data: { email, role } }); const link = `${window.location.origin}/agency-invite/${result.token}`; try { await navigator.clipboard.writeText(link); } catch { window.prompt(text("Kopieer de uitnodigingslink", "Copy the invitation link"), link); } if (result.mailDelivery === "failed") toast.warning(text("Uitnodiging gemaakt, maar e-mail kon niet worden klaargezet. Deel de link zelf.", "Invitation created, but email could not be queued. Share the link yourself.")); else toast.success(text("Uitnodigingslink is gekopieerd.", "Invitation link copied.")); setEmail(""); setInviteOpen(false); await team.refetch(); }
    catch (error) { toast.error(String(error).includes("INVITATION_EXISTS") ? text("Voor dit adres staat al een uitnodiging open.", "An invitation is already open for this address.") : text("Uitnodiging kon niet worden gemaakt.", "Invitation could not be created.")); }
    finally { setBusy(""); }
  }
  async function memberAction(userId: string, action: "role"|"suspend"|"restore"|"remove", nextRole?: "advisor"|"finance") {
    if (action === "remove" && !window.confirm(text("Dit teamlid verliest direct de toegang tot alle Agency-reizen. Doorgaan?", "This team member will immediately lose access to all Agency trips. Continue?"))) return;
    setBusy(`${userId}:${action}`); try { await manageAgencyMember({ data: { userId, action, ...(nextRole ? { role: nextRole } : {}) } }); await team.refetch(); toast.success(text("Teamlid bijgewerkt.", "Team member updated.")); } catch { toast.error(text("Teamlid kon niet worden bijgewerkt.", "Team member could not be updated.")); } finally { setBusy(""); }
  }
  async function invitationAction(id: string, action: "renew"|"revoke") {
    if (action === "revoke" && !window.confirm(text("Deze uitnodigingslink direct ongeldig maken?", "Invalidate this invitation link now?"))) return;
    setBusy(`${id}:${action}`); try { const result = await manageAgencyInvitation({ data: { invitationId: id, action } }); if (result.token) { const link = `${window.location.origin}/agency-invite/${result.token}`; try { await navigator.clipboard.writeText(link); } catch { window.prompt(text("Kopieer de nieuwe link", "Copy the new link"), link); } if (result.mailDelivery === "failed") toast.warning(text("Nieuwe link gemaakt, maar e-mail kon niet worden klaargezet. Deel de link zelf.", "New link created, but email could not be queued. Share the link yourself.")); else toast.success(text("Nieuwe link is gekopieerd.", "New link copied.")); } else toast.success(text("Uitnodiging ingetrokken.", "Invitation revoked.")); await team.refetch(); } catch { toast.error(text("Uitnodiging kon niet worden bijgewerkt.", "Invitation could not be updated.")); } finally { setBusy(""); }
  }

  return <div className="space-y-6">
    <header className="aurora rounded-3xl px-6 py-8 sm:px-8"><Badge variant="secondary" className="gap-1.5"><Building2 className="size-3"/>Agency workspace</Badge><h1 className="mt-4 font-display text-3xl font-semibold">{state.branding.brandName}</h1><p className="mt-2 max-w-2xl text-sm opacity-85">{text("Beheer je organisatie, merkuitstraling, team, reizen en abonnement vanuit één centrale omgeving.","Manage your organisation, branding, team, trips and plan from one central workspace.")}</p></header>
    <section className="grid gap-3 sm:grid-cols-3"><Metric icon={RouteIcon} label={text("Actieve reizen","Active trips")} value={activeTrips}/><Metric icon={Users} label={text("Workspaceleden","Workspace members")} value={team.data?.members.length ?? "—"}/><Metric icon={Palette} label={text("Actief merk","Active brand")} value={state.branding.brandName}/></section>
    {canManageMembers && <Card className="surface"><CardHeader className="flex flex-row items-center justify-between gap-3"><div><CardTitle>{text("Agency-team", "Agency team")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{text("Workspacebrede toegang tot alle reizen, volgens de toegewezen rol.", "Workspace-wide access to every trip, based on the assigned role.")}</p></div><Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogTrigger asChild><Button><MailPlus className="size-4"/>{text("Teamlid uitnodigen", "Invite team member")}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{text("Teamlid uitnodigen", "Invite team member")}</DialogTitle></DialogHeader><div className="space-y-4"><label className="block space-y-1 text-sm"><span>{text("E-mailadres", "Email address")}</span><Input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="naam@organisatie.nl"/></label><label className="block space-y-1 text-sm"><span>{text("Agency-rol", "Agency role")}</span><Select value={role} onValueChange={(value)=>setRole(value as "advisor"|"finance")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="advisor">Advisor</SelectItem><SelectItem value="finance">Finance</SelectItem></SelectContent></Select></label><p className="text-xs text-muted-foreground">{text("De link is zeven dagen geldig en wordt direct naar je klembord gekopieerd.", "The link is valid for seven days and is copied directly to your clipboard.")}</p><Button className="w-full" disabled={!email.trim() || busy === "invite"} onClick={()=>void invite()}>{text("Uitnodiging maken", "Create invitation")}</Button></div></DialogContent></Dialog></CardHeader><CardContent className="space-y-5">
      {team.isError && <p className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm">{text("Het Agency-team is beschikbaar nadat de nieuwe Agency-migraties zijn uitgevoerd.", "The Agency team becomes available after the new Agency migrations have been applied.")}</p>}
      {team.data?.members.map((member)=><div key={member.userId} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate font-medium">{member.name}</p><p className="truncate text-xs text-muted-foreground">{member.email}</p></div><Badge variant={member.status === "active" ? "secondary" : "outline"}>{roleLabel(member.role,text)} · {member.status === "active" ? text("Actief","Active") : text("Geblokkeerd","Suspended")}</Badge>{member.role !== "owner" && <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label={text("Acties voor teamlid","Team member actions")} disabled={busy.startsWith(member.userId)}><MoreHorizontal className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>void memberAction(member.userId,"role",member.role === "advisor" ? "finance" : "advisor")}>{text("Wijzig rol naar", "Change role to")} {member.role === "advisor" ? "Finance" : "Advisor"}</DropdownMenuItem><DropdownMenuItem onClick={()=>void memberAction(member.userId,member.status === "active" ? "suspend" : "restore")}>{member.status === "active" ? text("Toegang blokkeren","Suspend access") : text("Toegang herstellen","Restore access")}</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={()=>void memberAction(member.userId,"remove")}>{text("Uit team verwijderen","Remove from team")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div>)}
      {!!team.data?.invitations.length && <div><h3 className="mb-2 text-sm font-semibold">{text("Openstaande uitnodigingen", "Pending invitations")}</h3><div className="space-y-2">{team.data.invitations.map((invitation)=><div key={invitation.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{invitation.email}</p><p className="text-xs text-muted-foreground">{roleLabel(invitation.role,text)} · {invitation.status === "expired" ? text("Verlopen","Expired") : new Date(invitation.expiresAt).toLocaleDateString(locale)}</p><p className="mt-1 text-xs text-muted-foreground">{text("E-mail","Email")}: {invitation.emailStatus ?? text("niet klaargezet","not queued")}{invitation.emailError ? ` · ${invitation.emailError}` : ""}</p></div><Button size="sm" variant="outline" disabled={busy.startsWith(invitation.id)} onClick={()=>void invitationAction(invitation.id,"renew")}><Copy className="size-3.5"/>{text("Nieuwe link","New link")}</Button><Button size="sm" variant="ghost" disabled={busy.startsWith(invitation.id)} onClick={()=>void invitationAction(invitation.id,"revoke")}>{text("Intrekken","Revoke")}</Button></div>)}</div></div>}
    </CardContent></Card>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{access.data.role==="owner"&&<AdminCard icon={UserCog} title={text("Rollen en rechten","Roles and permissions")} body={text("Standaardrechten per rol en gerichte uitzonderingen per teamlid.","Default permissions per role and targeted exceptions per team member.")} to="/agency-admin/permissions" action={text("Rechten beheren","Manage permissions")}/>} {access.data.permissions.branding_manage&&<AdminCard icon={Settings2} title={text("Workspace-instellingen","Workspace settings")} body={text("Organisatiegegevens, taal, valuta, tijdzone en logo op één plaats.","Organisation details, language, currency, timezone and logo in one place.")} to="/agency-admin/settings" action={text("Instellingen openen","Open settings")}/>} {access.data.permissions.analytics_view&&<AdminCard icon={BarChart3} title={text("Reisoperatie","Trip operations")} body={text("Volg echte reis-, kosten- en declaratiegegevens voor deze workspace.","Track real trip, expense and claim data for this workspace.")} to="/agency-admin/operations" action={text("Overzicht openen","Open overview")}/>} {access.data.permissions.billing_manage&&<AdminCard icon={CreditCard} title={text("Abonnement","Plan")} body={text("Bekijk het Agency-plan en de beschikbare mogelijkheden.","Review the Agency plan and available capabilities.")} to="/billing" action={text("Abonnement beheren","Manage plan")}/>}<Card className="surface md:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="size-4"/>{text("Jouw Agency-rol","Your Agency role")}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{text("Je ziet alleen onderdelen waarvoor jouw rol of persoonlijke uitzondering toegang geeft.","You only see areas granted by your role or personal exception.")}</CardContent></Card></section>
  </div>;
}

function roleLabel(role: AgencyRole, text: (nl:string,en:string)=>string){ return role === "owner" ? text("Eigenaar","Owner") : role === "finance" ? "Finance" : "Advisor"; }
function Metric({icon:Icon,label,value}:{icon:typeof RouteIcon;label:string;value:string|number}){return <Card className="surface"><CardContent className="flex items-center gap-3 p-4"><span className="rounded-xl bg-primary/10 p-2 text-primary"><Icon className="size-5"/></span><span className="min-w-0"><span className="block text-xs text-muted-foreground">{label}</span><strong className="block truncate text-xl">{value}</strong></span></CardContent></Card>}
function AdminCard({icon:Icon,title,body,to,action}:{icon:typeof Palette;title:string;body:string;to:"/agency-admin/permissions"|"/agency-admin/settings"|"/branding"|"/agency-admin/operations"|"/billing";action:string}){return <Card className="surface flex flex-col"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Icon className="size-4 text-primary"/>{title}</CardTitle></CardHeader><CardContent className="flex flex-1 flex-col"><p className="text-sm text-muted-foreground">{body}</p><Button asChild variant="outline" className="mt-5 w-full"><Link to={to}>{action}</Link></Button></CardContent></Card>}
