import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarClock, CheckCircle2, ListTodo, Plus, Save } from "lucide-react";
import { toast } from "sonner";
import { getAgencyTasks, saveAgencyTask, type AgencyTask } from "@/lib/agency.functions";
import { useLocale } from "@/lib/locale";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export const Route=createFileRoute("/_authenticated/agency-admin/tasks")({component:AgencyTasksPage});
type Draft={id?:string;title:string;notes:string;dueDate:string;priority:AgencyTask["priority"];status:AgencyTask["status"];tripId:string;clientId:string;assigneeUserId:string};
const empty:Draft={title:"",notes:"",dueDate:"",priority:"normal",status:"open",tripId:"",clientId:"",assigneeUserId:""};

function AgencyTasksPage(){
 const{text,locale}=useLocale();const query=useQuery({queryKey:["agency-tasks"],queryFn:()=>getAgencyTasks(),retry:false});
 const[view,setView]=useState<"active"|"done"|"all">("active");const[dialog,setDialog]=useState(false);const[draft,setDraft]=useState<Draft>(empty);const[busy,setBusy]=useState(false);
 const tasks=useMemo(()=>query.data?.tasks.filter(task=>view==="all"||(view==="done"?["done","cancelled"].includes(task.status):!["done","cancelled"].includes(task.status)))??[],[query.data,view]);
 function edit(task?:AgencyTask){setDraft(task?{id:task.id,title:task.title,notes:task.notes,dueDate:task.dueDate,priority:task.priority,status:task.status,tripId:task.tripId,clientId:task.clientId,assigneeUserId:task.assigneeUserId}:empty);setDialog(true)}
 async function save(){setBusy(true);try{await saveAgencyTask({data:draft});await query.refetch();setDialog(false);toast.success(text("Taak opgeslagen.","Task saved."))}catch{toast.error(text("Taak kon niet worden opgeslagen.","Task could not be saved."))}finally{setBusy(false)}}
 async function finish(task:AgencyTask){setBusy(true);try{await saveAgencyTask({data:{...task,id:task.id,status:"done"}});await query.refetch();toast.success(text("Taak afgerond.","Task completed."))}catch{toast.error(text("Taak kon niet worden bijgewerkt.","Task could not be updated."))}finally{setBusy(false)}}
 const today=new Date().toISOString().slice(0,10);return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 font-display text-3xl font-semibold"><ListTodo className="size-7 text-primary"/>{text("Taken en deadlines","Tasks and deadlines")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Verdeel werk rond reizen en klanten binnen je Agency-team.","Assign work for trips and clients across your Agency team.")}</p></div>{query.data?.canManage&&<Button onClick={()=>edit()}><Plus className="size-4"/>{text("Nieuwe taak","New task")}</Button>}</header>
 <div className="flex flex-wrap gap-2">{(["active","done","all"]as const).map(item=><Button key={item} size="sm" variant={view===item?"default":"outline"} onClick={()=>setView(item)}>{item==="active"?text("Openstaand","Active"):item==="done"?text("Afgerond","Completed"):text("Alles","All")}</Button>)}</div>
 {query.isError?<p className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">{text("Taken worden beschikbaar nadat de takenmigratie is uitgevoerd.","Tasks become available after the tasks migration has been applied.")}</p>:<div className="grid gap-3">{tasks.map(task=>{const overdue=Boolean(task.dueDate&&task.dueDate<today&&!["done","cancelled"].includes(task.status));const trip=query.data?.trips.find(item=>item.id===task.tripId);const client=query.data?.clients.find(item=>item.id===task.clientId);return <Card key={task.id} className="surface"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="break-anywhere font-medium">{task.title}</p><Badge variant={overdue?"destructive":"outline"}>{priorityLabel(task.priority,text)}</Badge><Badge variant="secondary">{statusLabel(task.status,text)}</Badge></div><p className="mt-1 flex flex-wrap gap-x-3 text-xs text-muted-foreground">{task.dueDate&&<span className={overdue?"text-destructive":""}><CalendarClock className="mr-1 inline size-3.5"/>{new Intl.DateTimeFormat(locale==="en-GB"?"en-GB":"nl-NL",{dateStyle:"medium"}).format(new Date(`${task.dueDate}T12:00:00`))}</span>}{task.assigneeName&&<span>{text("Toegewezen aan","Assigned to")} {task.assigneeName}</span>}{client&&<span>{client.name}</span>}{trip&&<Link className="underline" to="/trips/$tripId" params={{tripId:trip.id}}>{trip.name}</Link>}</p>{task.notes&&<p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{task.notes}</p>}</div>{query.data?.canManage&&<div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>edit(task)}>{text("Bewerken","Edit")}</Button>{!["done","cancelled"].includes(task.status)&&<Button size="sm" disabled={busy} onClick={()=>void finish(task)}><CheckCircle2 className="size-4"/>{text("Afronden","Complete")}</Button>}</div>}</CardContent></Card>})}{query.data&&!tasks.length&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text("Geen taken in dit overzicht.","No tasks in this view.")}</p>}</div>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{draft.id?text("Taak bewerken","Edit task"):text("Nieuwe taak","New task")}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label={text("Titel","Title")} wide><Input value={draft.title} maxLength={120} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label={text("Deadline","Deadline")}><Input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></Field><Field label={text("Prioriteit","Priority")}><select className="h-10 w-full rounded-md border bg-background px-3" value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as Draft["priority"]})}>{["low","normal","high","urgent"].map(value=><option key={value} value={value}>{priorityLabel(value as Draft["priority"],text)}</option>)}</select></Field><Field label={text("Status","Status")}><select className="h-10 w-full rounded-md border bg-background px-3" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Draft["status"]})}>{["open","in_progress","done","cancelled"].map(value=><option key={value} value={value}>{statusLabel(value as Draft["status"],text)}</option>)}</select></Field><Field label={text("Teamlid","Team member")}><select className="h-10 w-full rounded-md border bg-background px-3" value={draft.assigneeUserId} onChange={e=>setDraft({...draft,assigneeUserId:e.target.value})}><option value="">{text("Niet toegewezen","Unassigned")}</option>{query.data?.members.map(item=><option key={item.userId} value={item.userId}>{item.name}</option>)}</select></Field><Field label={text("Reis","Trip")}><select className="h-10 w-full rounded-md border bg-background px-3" value={draft.tripId} onChange={e=>setDraft({...draft,tripId:e.target.value})}><option value="">{text("Geen reis","No trip")}</option>{query.data?.trips.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label={text("Klant","Client")}><select className="h-10 w-full rounded-md border bg-background px-3" value={draft.clientId} onChange={e=>setDraft({...draft,clientId:e.target.value})}><option value="">{text("Geen klant","No client")}</option>{query.data?.clients.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label={text("Notities","Notes")} wide><Textarea rows={4} maxLength={1000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><Button className="sm:col-span-2" disabled={busy||!draft.title.trim()} onClick={()=>void save()}><Save className="size-4"/>{text("Taak opslaan","Save task")}</Button></div></DialogContent></Dialog></div>;
}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`space-y-1 text-sm ${wide?"sm:col-span-2":""}`}><span>{label}</span>{children}</label>}
function priorityLabel(value:AgencyTask["priority"],text:(nl:string,en:string)=>string){return {low:text("Laag","Low"),normal:text("Normaal","Normal"),high:text("Hoog","High"),urgent:text("Urgent","Urgent")}[value]}
function statusLabel(value:AgencyTask["status"],text:(nl:string,en:string)=>string){return {open:text("Open","Open"),in_progress:text("Bezig","In progress"),done:text("Afgerond","Completed"),cancelled:text("Geannuleerd","Cancelled")}[value]}
