import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Bell, Save, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { getAgencyNotificationPreferences, saveAgencyNotificationPreferences, type AgencyNotificationPreferences } from "@/lib/agency.functions";
import { useLocale } from "@/lib/locale";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";

export const Route=createFileRoute("/_authenticated/agency-admin/notifications")({head:()=>({meta:[{title:"Agency-meldingen — GlobeTrotr"}]}),component:AgencyNotificationsPage});
function AgencyNotificationsPage(){
 const{text}=useLocale();const query=useQuery({queryKey:["agency-notification-preferences"],queryFn:()=>getAgencyNotificationPreferences(),retry:false});const[form,setForm]=useState<AgencyNotificationPreferences|null>(null);const[saving,setSaving]=useState(false);useEffect(()=>{if(query.data)setForm(query.data)},[query.data]);
 async function save(){if(!form)return;setSaving(true);try{const{workspaceId,...preferences}=form;await saveAgencyNotificationPreferences({data:preferences});await query.refetch();toast.success(text("Meldingsvoorkeuren opgeslagen.","Notification preferences saved."))}catch{toast.error(text("Meldingsvoorkeuren konden niet worden opgeslagen.","Notification preferences could not be saved."))}finally{setSaving(false)}}
 if(query.isLoading)return <p className="text-sm text-muted-foreground">{text("Meldingsvoorkeuren laden…","Loading notification preferences…")}</p>;
 if(!form)return <Card className="surface"><CardContent className="p-6 text-sm text-muted-foreground">{text("Voer eerst de migratie voor Agency-meldingsvoorkeuren uit.","Apply the Agency notification preferences migration first.")}</CardContent></Card>;
 return <div className="space-y-6"><header><h1 className="flex items-center gap-2 font-display text-3xl font-semibold"><Bell className="size-7 text-primary"/>{text("Meldingen","Notifications")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Kies welke niet-kritieke Agency-activiteiten je wilt volgen.","Choose which non-critical Agency activity you want to follow.")}</p></header><Card className="surface"><CardHeader><CardTitle>{text("Persoonlijke voorkeuren","Personal preferences")}</CardTitle></CardHeader><CardContent className="space-y-2"><Preference label={text("Wijzigingen aan reizen","Trip changes")} description={text("Updates aan planning, boekingen en uitgaven binnen de Agency-workspace.","Updates to planning, bookings and expenses in the Agency workspace.")} checked={form.tripChanges} onChange={value=>setForm({...form,tripChanges:value})}/><Preference label={text("Reacties op uitnodigingen","Invitation responses")} description={text("Wanneer iemand een team- of reisuitnodiging accepteert of weigert.","When someone accepts or declines a team or trip invitation.")} checked={form.invitationResponses} onChange={value=>setForm({...form,invitationResponses:value})}/><Preference label={text("Wijzigingen aan klanten","Client updates")} description={text("Aanpassingen aan klantprofielen en gekoppelde reizen.","Changes to client profiles and linked trips.")} checked={form.clientUpdates} onChange={value=>setForm({...form,clientUpdates:value})}/></CardContent></Card><Card className="border-primary/30 surface"><CardContent className="flex gap-3 p-5"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary"/><div><p className="font-medium">{text("Kritieke beveiligingsmeldingen blijven actief","Critical security notifications remain enabled")}</p><p className="mt-1 text-sm text-muted-foreground">{text("Blokkades, verwijderde toegang en belangrijke platformberichten kunnen niet via deze voorkeuren worden uitgezet.","Suspensions, removed access and important platform notices cannot be disabled through these preferences.")}</p></div></CardContent></Card><Button disabled={saving} onClick={()=>void save()}><Save className="size-4"/>{saving?text("Opslaan…","Saving…"):text("Voorkeuren opslaan","Save preferences")}</Button></div>;
}
function Preference({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex items-start justify-between gap-5 rounded-xl border p-4"><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></span><Switch checked={checked} onCheckedChange={onChange}/></label>}
