import{useState}from"react";
import{createFileRoute}from"@tanstack/react-router";
import{useQuery}from"@tanstack/react-query";
import{Archive,BookOpenCheck,Copy,Plus,Send,ShieldCheck,Trash2}from"lucide-react";
import{toast}from"sonner";
import{Button}from"@/components/ui/button";import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";import{Dialog,DialogContent,DialogHeader,DialogTitle}from"@/components/ui/dialog";import{Input}from"@/components/ui/input";import{Textarea}from"@/components/ui/textarea";import{Badge}from"@/components/ui/badge";
import{archiveAgencyFormTemplate,createAgencyFormRequest,getAgencyFormBoard,manageAgencyFormRequest,saveAgencyFormTemplate,type AgencyFormField}from"@/lib/agency.functions";import{useLocale}from"@/lib/locale";
export const Route=createFileRoute("/_authenticated/agency-admin/forms")({component:Page});
const field=():AgencyFormField=>({key:"question",type:"text",labelNl:"Vraag",labelEn:"Question",purpose:"Reisvoorstel voorbereiden",required:false,visibility:"client"});
function Page(){const{text,locale}=useLocale();const query=useQuery({queryKey:["agency-client-forms"],queryFn:()=>getAgencyFormBoard(),retry:false});const[editor,setEditor]=useState(false);const[requestOpen,setRequestOpen]=useState(false);const[busy,setBusy]=useState(false);const[template,setTemplate]=useState({id:"",name:"",introduction:"",retentionDays:90,fields:[field()]});const[request,setRequest]=useState({templateId:"",clientId:"",tripId:"",title:"",expiresInDays:7});const[lastUrl,setLastUrl]=useState("");
 async function save(){setBusy(true);try{await saveAgencyFormTemplate({data:{...template,id:template.id||undefined}});await query.refetch();setEditor(false);toast.success(text("Formuliersjabloon opgeslagen.","Form template saved."))}catch{toast.error(text("Controleer alle velden, doelen en keuzeopties.","Check all fields, purposes and choice options."))}finally{setBusy(false)}}
 async function send(){setBusy(true);try{const r=await createAgencyFormRequest({data:request});setLastUrl(r.url);await query.refetch();toast.success(r.delivery==="queued"?text("Formulier en e-mail klaargezet.","Form and email queued."):text("Formulier gemaakt; controleer de mailwachtrij.","Form created; check the email queue."))}catch{toast.error(text("Formulierverzoek kon niet worden gemaakt.","Form request could not be created."))}finally{setBusy(false)}}
 async function action(id:string,next:"revoke"|"review"|"process"|"archive"){if(!confirm(text("Deze actie uitvoeren?","Perform this action?")))return;setBusy(true);try{await manageAgencyFormRequest({data:{id,action:next}});await query.refetch();toast.success(text("Formulier bijgewerkt.","Form updated."))}catch{toast.error(text("Actie kon niet worden uitgevoerd.","Action could not be completed."))}finally{setBusy(false)}}
 function download(item:any){const blob=new Blob([JSON.stringify({title:item.title,client:item.clientName,trip:item.tripName,submittedAt:item.submittedAt,answers:item.answers},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`client-form-${item.id}.json`;a.click();URL.revokeObjectURL(url)}
 const edit=(item?:any)=>{setTemplate(item?{...item,fields:item.fields.map((x:any)=>({...x}))}:{id:"",name:"",introduction:"",retentionDays:90,fields:[field()]});setEditor(true)};
 return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 font-display text-3xl font-semibold"><BookOpenCheck className="size-7 text-primary"/>{text("Klantformulieren","Client forms")}</h1><p className="mt-2 text-sm text-muted-foreground">{text("Vraag klantgegevens veilig op en verwerk antwoorden pas na controle.","Request client details securely and process answers only after review.")}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>edit()}><Plus className="size-4"/>{text("Sjabloon","Template")}</Button><Button onClick={()=>{const first=query.data?.templates[0],client=query.data?.clients[0];setRequest({templateId:first?.id??"",clientId:client?.id??"",tripId:"",title:first?.name??"",expiresInDays:7});setLastUrl("");setRequestOpen(true)}} disabled={!query.data?.templates.length||!query.data?.clients.length}><Send className="size-4"/>{text("Formulier sturen","Send form")}</Button></div></header>
 {query.isError&&<p className="rounded-xl border border-destructive/30 p-4 text-sm">{text("Klantformulieren worden beschikbaar na migratie 1550.","Client forms become available after migration 1550.")}</p>}
 <section><h2 className="mb-3 font-semibold">{text("Sjablonen","Templates")}</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{query.data?.templates.map(item=><Card key={item.id} className="surface"><CardHeader><CardTitle className="text-base">{item.name}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{item.fields.length} {text("velden","fields")} · {item.retentionDays} {text("dagen bewaren","days retention")}</p><div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={()=>edit(item)}>{text("Bewerken","Edit")}</Button><Button size="icon" variant="ghost" aria-label={text("Archiveren","Archive")} onClick={()=>void archiveAgencyFormTemplate({data:{id:item.id}}).then(()=>query.refetch())}><Archive className="size-4"/></Button></div></CardContent></Card>)}</div></section>
 <section><h2 className="mb-3 font-semibold">{text("Verzoeken en antwoorden","Requests and responses")}</h2><div className="space-y-3">{query.data?.requests.map(item=><Card key={item.id} className="surface"><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{item.title}</strong><p className="text-sm text-muted-foreground">{item.clientName}{item.tripName?` · ${item.tripName}`:""} · {new Date(item.expiresAt).toLocaleDateString(locale)}</p></div><Badge variant={item.revokedAt?"destructive":item.responseStatus==="processed"?"default":"secondary"}>{item.revokedAt?text("Ingetrokken","Revoked"):item.responseStatus||text("Open","Open")}</Badge></div>{Object.keys(item.answers).length>0&&<dl className="mt-3 grid gap-2 rounded-lg bg-muted/30 p-3 text-sm sm:grid-cols-2">{Object.entries(item.answers).map(([key,value])=><div key={key} className="min-w-0"><dt className="font-medium">{key}</dt><dd className="break-words text-muted-foreground">{typeof value==="boolean"?(value?text("Ja","Yes"):text("Nee","No")):String(value)}</dd></div>)}</dl>}<div className="mt-3 flex flex-wrap gap-2">{!item.revokedAt&&!item.submittedAt&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(item.id,"revoke")}>{text("Intrekken","Revoke")}</Button>}{item.responseStatus==="submitted"&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(item.id,"review")}>{text("Gecontroleerd","Mark reviewed")}</Button>}{["submitted","reviewed"].includes(item.responseStatus)&&<Button size="sm" disabled={busy} onClick={()=>void action(item.id,"process")}><ShieldCheck className="size-4"/>{text("Naar klantprofiel","Apply to client")}</Button>}{item.responseId&&<Button size="sm" variant="outline" onClick={()=>download(item)}>{text("JSON exporteren","Export JSON")}</Button>}{item.responseId&&item.responseStatus!=="archived"&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void action(item.id,"archive")}>{text("Archiveren","Archive")}</Button>}</div></CardContent></Card>)}</div></section>
 <Dialog open={editor} onOpenChange={setEditor}><DialogContent className="max-h-[calc(100dvh-2rem)] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{text("Formuliersjabloon","Form template")}</DialogTitle></DialogHeader><div className="space-y-4"><Input value={template.name} maxLength={100} placeholder={text("Naam","Name")} onChange={e=>setTemplate({...template,name:e.target.value})}/><Textarea value={template.introduction} maxLength={1000} placeholder={text("Uitleg voor de klant","Introduction for the client")} onChange={e=>setTemplate({...template,introduction:e.target.value})}/><label className="block text-sm">{text("Bewaartermijn na verlopen link (dagen)","Retention after link expiry (days)")}<Input type="number" min={1} max={730} value={template.retentionDays} onChange={e=>setTemplate({...template,retentionDays:Number(e.target.value)})}/></label>{template.fields.map((f,i)=><div key={i} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-2"><Input value={f.key} placeholder="field_key" onChange={e=>change(i,{key:e.target.value})}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={f.type} onChange={e=>change(i,{type:e.target.value as AgencyFormField["type"]})}>{["text","textarea","email","phone","date","number","choice","checkbox"].map(type=><option key={type}>{type}</option>)}</select><Input value={f.labelNl} placeholder="Label NL" onChange={e=>change(i,{labelNl:e.target.value})}/><Input value={f.labelEn} placeholder="Label EN" onChange={e=>change(i,{labelEn:e.target.value})}/><Input className="sm:col-span-2" value={f.purpose} placeholder={text("Doel van dit veld","Purpose of this field")} onChange={e=>change(i,{purpose:e.target.value})}/>{f.type==="choice"&&<Input className="sm:col-span-2" value={(f.options??[]).join(", ")} placeholder={text("Keuzes, gescheiden door komma's","Options, comma separated")} onChange={e=>change(i,{options:e.target.value.split(",")})}/>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.required} onChange={e=>change(i,{required:e.target.checked})}/>{text("Verplicht","Required")}</label><Button type="button" size="sm" variant="ghost" disabled={template.fields.length===1} onClick={()=>setTemplate({...template,fields:template.fields.filter((_,x)=>x!==i)})}><Trash2 className="size-4"/>{text("Verwijderen","Remove")}</Button></div>)}<Button variant="outline" disabled={template.fields.length>=40} onClick={()=>setTemplate({...template,fields:[...template.fields,field()]})}><Plus className="size-4"/>{text("Veld toevoegen","Add field")}</Button><Button className="w-full" disabled={busy||!template.name.trim()} onClick={()=>void save()}>{text("Sjabloon opslaan","Save template")}</Button></div></DialogContent></Dialog>
 <Dialog open={requestOpen} onOpenChange={setRequestOpen}><DialogContent><DialogHeader><DialogTitle>{text("Klantformulier versturen","Send client form")}</DialogTitle></DialogHeader><div className="space-y-4"><select className="h-10 w-full rounded-md border bg-background px-3" value={request.templateId} onChange={e=>{const t=query.data?.templates.find(x=>x.id===e.target.value);setRequest({...request,templateId:e.target.value,title:t?.name??request.title})}}>{query.data?.templates.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="h-10 w-full rounded-md border bg-background px-3" value={request.clientId} onChange={e=>setRequest({...request,clientId:e.target.value})}>{query.data?.clients.map(x=><option key={x.id} value={x.id}>{x.name}{!x.email?` (${text("geen e-mail","no email")})`:""}</option>)}</select><select className="h-10 w-full rounded-md border bg-background px-3" value={request.tripId} onChange={e=>setRequest({...request,tripId:e.target.value})}><option value="">{text("Geen specifieke reis","No specific trip")}</option>{query.data?.trips.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Input value={request.title} maxLength={140} onChange={e=>setRequest({...request,title:e.target.value})}/><label className="block text-sm">{text("Link geldig (dagen)","Link valid (days)")}<Input type="number" min={1} max={30} value={request.expiresInDays} onChange={e=>setRequest({...request,expiresInDays:Number(e.target.value)})}/></label><Button className="w-full" disabled={busy||!request.templateId||!request.clientId} onClick={()=>void send()}><Send className="size-4"/>{text("Maken en e-mailen","Create and email")}</Button>{lastUrl&&<div className="rounded-lg border p-3 text-sm"><p className="break-all">{lastUrl}</p><Button className="mt-2" size="sm" variant="outline" onClick={()=>void navigator.clipboard.writeText(lastUrl)}><Copy className="size-4"/>{text("Link kopiëren","Copy link")}</Button></div>}</div></DialogContent></Dialog>
 </div>;
 function change(index:number,patch:Partial<AgencyFormField>){setTemplate(current=>({...current,fields:current.fields.map((x,i)=>i===index?{...x,...patch}:x)}))}
}
