import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Building2,MessageSquareWarning,Route as RouteIcon,Users } from "lucide-react";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Metric } from "@/lib/corporate-admin-ui";
import { getCorporateAdminData } from "@/lib/issues.functions";
import { useLocale } from "@/lib/locale";
export const Route=createFileRoute("/_authenticated/corporate-admin/")({component:Overview});
function Overview(){const{text}=useLocale();const{data}=useQuery({queryKey:["corporate-admin-data"],queryFn:()=>getCorporateAdminData()});const m=data?.metrics;return <div className="space-y-5"><h2 className="font-display text-2xl font-semibold">{text("Bedrijfsoverzicht","Business overview")}</h2><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Workspaces" value={m?.workspaces} detail={text(`${m?.newWorkspaces30d??0} nieuw in 30 dagen`,`${m?.newWorkspaces30d??0} new in 30 days`)}/><Metric icon={Building2} label={text("Actief in 30 dagen","Active in 30 days")} value={m?.activeWorkspaces30d} detail={text("Workspace-activiteit","Workspace activity")}/><Metric icon={RouteIcon} label={text("Actieve reizen","Active trips")} value={m?.activeTrips} detail={text(`${m?.publicTrips??0} openbaar`,`${m?.publicTrips??0} public`)}/><Metric icon={MessageSquareWarning} label={text("Open werk","Open work")} value={(m?.openFeedback??0)+(m?.openIssues??0)} detail={`${m?.openFeedback??0} feedback · ${m?.openIssues??0} issues`}/></section><Card><CardHeader><CardTitle>{text("Planverdeling","Plan distribution")}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{(["free","pro","agency"] as const).map(p=><div key={p} className="rounded-xl border p-4"><span className="capitalize">{p}</span><strong className="mt-1 block text-2xl">{m?.plans[p]??"—"}</strong></div>)}</CardContent></Card></div>}
