import { useMemo, useState } from "react";
import { BedDouble, ExternalLink, Loader2, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { findHotelGaps, type HotelGap } from "@/lib/hotel-gaps";
import { searchNearbyHotels, type HotelSearchResult } from "@/lib/hotel-search.functions";
import { normalizeTravelOption } from "@/lib/trip-options";
import type { Trip } from "@/lib/types";
import { uid } from "@/lib/workspace";

type Text = (nl: string, en: string) => string;
export function HotelGapFinder({ trip, editable, save, text }: { trip: Trip; editable: boolean; save: (fn: (trip: Trip) => Trip) => Promise<void>; text: Text }) {
  const gaps = useMemo(() => findHotelGaps(trip.stops, trip.travelItems), [trip.stops, trip.travelItems]);
  const [gap, setGap] = useState<HotelGap>(); const [results, setResults] = useState<HotelSearchResult[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState<string>();
  async function search(item: HotelGap) { setGap(item); setResults([]); setLoading(true); try { const found = await searchNearbyHotels({ data: { tripId: trip.id, lat: item.lat, lon: item.lon } }); setResults(found.results); } catch (error) { toast.error(error instanceof Error && error.message === "HOTEL_SEARCH_RATE_LIMIT" ? text("Je zoekt te snel. Probeer het over een minuut opnieuw.", "You are searching too quickly. Try again in a minute.") : text("Hotels zoeken is tijdelijk niet beschikbaar.", "Hotel search is temporarily unavailable.")); } finally { setLoading(false); } }
  async function add(result: HotelSearchResult) { if (!gap) return; setSaving(result.id); try { const option = normalizeTravelOption({ id: uid(), type: "lodging", title: result.name, startDate: gap.startDate, endDate: gap.endDate, provider: "OpenStreetMap", distanceKm: result.distanceKm, sourceUrl: result.website ?? result.osmUrl, notes: text("Zoekresultaat; controleer prijs en beschikbaarheid bij de aanbieder.", "Search result; verify price and availability with the provider."), details: { locationName: `${gap.stopName}, ${gap.country}` }, status: "candidate", checkedAt: new Date().toISOString(), createdAt: new Date().toISOString() }); await save((current) => ({ ...current, travelOptions: [...(current.travelOptions ?? []), option] })); toast.success(text("Hotel toegevoegd aan de Vergelijker.", "Hotel added to Comparison.")); } catch { toast.error(text("Hotel kon niet worden toegevoegd.", "Hotel could not be added.")); } finally { setSaving(undefined); } }
  return <><Card><CardHeader><CardTitle className="flex items-center gap-2"><BedDouble className="size-5" />{text("Ontbrekende overnachtingen", "Missing accommodation")}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{text("GlobeTrotr vergelijkt de nachten van je route met geboekte verblijven.", "GlobeTrotr compares the nights in your route with booked accommodation.")}</p>{!gaps.length ? <p className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{text("Voor alle ingestelde reisnachten is een verblijf geboekt.", "Accommodation is booked for every configured trip night.")}</p> : gaps.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><strong>{item.stopName}</strong><p className="text-sm text-muted-foreground">{item.startDate} – {item.endDate} · {item.nights} {item.nights === 1 ? text("nacht", "night") : text("nachten", "nights")}</p></div><Button disabled={!editable || loading} onClick={() => search(item)}><Search className="size-4" />{text("Zoek hotels", "Find hotels")}</Button></div>)}<p className="text-xs text-muted-foreground">{text("OpenStreetMap-resultaten bevatten geen live prijzen of beschikbaarheid.", "OpenStreetMap results do not include live prices or availability.")}</p></CardContent></Card>
  <Dialog open={Boolean(gap)} onOpenChange={(open) => { if (!open) setGap(undefined); }}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{text("Hotels rond", "Hotels near")} {gap?.stopName}</DialogTitle></DialogHeader>{loading ? <div className="flex items-center justify-center gap-2 p-10"><Loader2 className="size-5 animate-spin" />{text("Hotels zoeken…", "Searching hotels…")}</div> : !results.length ? <p className="py-8 text-center text-sm text-muted-foreground">{text("Geen benoemde verblijven binnen 5 km gevonden.", "No named accommodation found within 5 km.")}</p> : <div className="space-y-2">{results.map((result) => <div key={result.id} className="rounded-lg border p-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><strong>{result.name}</strong><p className="text-sm text-muted-foreground">{result.kind.replaceAll("_", " ")} · {result.distanceKm} km{result.stars ? ` · ${result.stars}★` : ""}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" asChild><a href={result.website ?? result.osmUrl} target="_blank" rel="noopener noreferrer"><ExternalLink className="size-4" />{text("Bekijken", "View")}</a></Button><Button size="sm" disabled={!editable || Boolean(saving)} onClick={() => add(result)}>{saving === result.id && <Loader2 className="size-4 animate-spin" />}{text("Naar Vergelijker", "Add to Comparison")}</Button></div></div></div>)}</div>}<p className="text-xs text-muted-foreground">© <a className="underline" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a></p></DialogContent></Dialog></>;
}
