import { useMemo, useState } from "react";
import { BedDouble, CalendarDays, Check, ChevronRight, MapPinned, Plane, ReceiptText, Users, Wallet } from "lucide-react";
import { useLocale } from "@/lib/locale";

const STEPS = ["route", "bookings", "plan", "costs"] as const;
type Step = (typeof STEPS)[number];

export function LandingDemo({ expanded = false }: { expanded?: boolean }) {
  const { text, locale } = useLocale();
  const [step, setStep] = useState<Step>("route");
  const [selectedDay, setSelectedDay] = useState(0);
  const [packed, setPacked] = useState(false);
  const [settled, setSettled] = useState(false);
  const index = STEPS.indexOf(step);
  const money = (value: number) => new Intl.NumberFormat(locale, { style: "currency", currency: "EUR" }).format(value);
  const labels = useMemo(() => ({ route: text("Route", "Route"), bookings: text("Boekingen", "Bookings"), plan: text("Dagplanning", "Itinerary"), costs: text("Kosten", "Expenses") }), [text]);

  return <div className={`overflow-hidden rounded-[1.75rem] border border-primary/20 bg-background shadow-2xl shadow-primary/10 ${expanded ? "mx-auto max-w-5xl" : ""}`}>
    <div className="flex flex-wrap items-center justify-between gap-3 border-b bg-muted/30 px-5 py-4"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-primary">{text("Live productrondleiding", "Live product tour")}</p><h2 className="mt-1 font-display text-xl font-semibold">Scandinavië 2026</h2></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Users className="size-4" />Domenic & Puck</div></div>
    <div className={`grid ${expanded ? "lg:grid-cols-[13rem_1fr]" : ""}`}>
      <nav className={`gap-1 border-b bg-muted/15 p-3 ${expanded ? "grid grid-cols-2 sm:grid-cols-4 lg:block lg:border-b-0 lg:border-r" : "grid grid-cols-4"}`} aria-label={text("Demo-onderdelen", "Demo sections")}>
        {STEPS.map((id, position) => <button key={id} type="button" onClick={() => setStep(id)} aria-current={step === id ? "step" : undefined} className={`flex min-w-0 items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-medium transition ${step === id ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><span className="grid size-5 shrink-0 place-items-center rounded-full border border-current/30 text-[10px]">{position + 1}</span><span className="truncate">{labels[id]}</span></button>)}
      </nav>
      <div className={`p-4 sm:p-6 ${expanded ? "min-h-[31rem]" : "min-h-[25rem]"}`}>
        {step === "route" && <div className="space-y-4"><Header icon={MapPinned} title={text("Zet de hele reis op de kaart", "Map the complete trip")} copy={text("Orden je stops en zie direct hoe de reis loopt.", "Order your stops and immediately see how the trip flows.")} /><div className="relative h-52 overflow-hidden rounded-2xl bg-[#082f2c] sm:h-64"><div className="absolute inset-0 opacity-20" style={{backgroundImage:"radial-gradient(circle at 1px 1px,#99f6e4 1px,transparent 0)",backgroundSize:"24px 24px"}}/><svg viewBox="0 0 600 260" className="relative h-full w-full" role="img" aria-label={text("Route van Amsterdam via Zweden naar Noorwegen", "Route from Amsterdam through Sweden to Norway")}><path d="M70 215 C150 190 130 80 245 105 S340 55 410 115 S500 115 545 55" fill="none" stroke="#5eead4" strokeWidth="4" strokeDasharray="9 8"/>{[[70,215,"Amsterdam"],[245,105,"Stockholm"],[410,115,"Kiruna"],[545,55,"Lofoten"]].map(([x,y,name],i)=><g key={String(name)}><circle cx={Number(x)} cy={Number(y)} r="13" fill="#0f766e" stroke="#99f6e4" strokeWidth="3"/><text x={Number(x)+(i===3?-68:18)} y={Number(y)-15} fill="white" fontSize="13">{name}</text></g>)}</svg></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><Stat value="10" label={text("stops","stops")}/><Stat value="14" label={text("dagen","days")}/><Stat value="2.840 km" label={text("route","route")}/></div></div>}
        {step === "bookings" && <div className="space-y-4"><Header icon={Plane} title={text("Alle bevestigingen op hun plek", "Every confirmation in its place")} copy={text("Vlucht, verblijf en vervoer staan naast de planning.", "Flights, stays and transport sit alongside the itinerary.")} /><div className="space-y-2">{[[Plane,"KL1217 · Amsterdam → Stockholm","8 dec · 08:45",text("Live vluchtgegevens","Live flight data")],[BedDouble,"Arctic City Suite · Rovaniemi","9–12 dec","Booking.com"],[ReceiptText,text("Huurauto · Luleå Airport","Rental car · Luleå Airport"),"8–22 dec","Sixt"]].map(([Icon,title,date,meta])=><article key={String(title)} className="flex items-center gap-3 rounded-2xl border p-3.5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{title as string}</p><p className="mt-1 text-xs text-muted-foreground">{date as string} · {meta as string}</p></div><Check className="ml-auto size-4 text-emerald-500"/></article>)}</div></div>}
        {step === "plan" && <div className="space-y-4"><Header icon={CalendarDays} title={text("Iedere dag weet iedereen wat er speelt", "Everyone knows the plan for every day")} copy={text("Klik op een dag en vink de paklijst zelf af.", "Choose a day and tick off the packing item yourself.")} /><div className="flex gap-2">{[text("Dag 1","Day 1"),text("Dag 5","Day 5"),text("Dag 9","Day 9")].map((label,i)=><button type="button" key={label} onClick={()=>setSelectedDay(i)} className={`rounded-full border px-3 py-2 text-xs ${selectedDay===i?"border-primary bg-primary/10 text-primary":""}`}>{label}</button>)}</div><div className="rounded-2xl border p-5"><p className="text-xs text-muted-foreground">{["Stockholm","Rovaniemi","Lofoten"][selectedDay]}</p><h3 className="mt-1 font-display text-xl font-semibold">{[text("Aankomst en Gamla Stan","Arrival and Gamla Stan"),text("Noorderlicht en sauna","Northern lights and sauna"),text("Langs vissersdorpen","Explore fishing villages")][selectedDay]}</h3><p className="mt-4 text-sm text-muted-foreground">10:30 · {["Arlanda Express","Arctic tour","Reinebringen"][selectedDay]}</p></div><button type="button" onClick={()=>setPacked(!packed)} className="flex w-full items-center gap-3 rounded-xl bg-muted/60 p-3 text-sm"><span className={`grid size-5 place-items-center rounded border ${packed?"border-primary bg-primary text-primary-foreground":""}`}>{packed&&<Check className="size-4"/>}</span>{text("Warme handschoenen ingepakt","Warm gloves packed")}<span className="ml-auto text-xs text-muted-foreground">{packed?text("Klaar","Done"):text("Nog doen","To do")}</span></button></div>}
        {step === "costs" && <div className="space-y-4"><Header icon={Wallet} title={text("Eerlijk verrekenen zonder rekenwerk", "Settle fairly without spreadsheets")} copy={text("GlobeTrotr rekent uit welke betaling de groep weer gelijk trekt.", "GlobeTrotr calculates which payment balances the group.")} /><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-primary/10 p-5"><p className="text-xs text-muted-foreground">{text("Totaal gepland","Total planned")}</p><p className="mt-1 font-display text-3xl font-semibold">{money(5248)}</p></div><div className="rounded-2xl border p-5"><p className="text-xs text-muted-foreground">{text("Verschil","Difference")}</p><p className="mt-1 font-display text-3xl font-semibold">{settled?money(0):money(318)}</p></div></div><div className={`rounded-2xl border p-4 ${settled?"border-emerald-500/30 bg-emerald-500/10":""}`}><p className="text-sm font-medium">{settled?text("Helemaal verrekend","Fully settled"):"Puck → Domenic"}</p><p className="mt-1 text-xs text-muted-foreground">{settled?text("Iedereen staat weer gelijk.","Everyone is balanced again."):money(318)}</p><button type="button" onClick={()=>setSettled(!settled)} className="mt-4 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground">{settled?text("Ongedaan maken","Undo"):text("Markeer als betaald","Mark as paid")}</button></div></div>}
      </div>
    </div>
    <div className="flex items-center justify-between gap-3 border-t bg-muted/20 px-5 py-3"><p className="text-[11px] text-muted-foreground">{text("Veilige voorbeelddata · niets wordt opgeslagen", "Safe sample data · nothing is saved")}</p>{index < STEPS.length-1 && <button type="button" onClick={()=>setStep(STEPS[index+1]!)} className="flex items-center gap-1 text-xs font-semibold text-primary">{text("Volgende stap","Next step")}<ChevronRight className="size-4"/></button>}</div>
  </div>;
}

function Header({icon:Icon,title,copy}:{icon:typeof MapPinned;title:string;copy:string}){return <div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div><h3 className="font-display text-xl font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{copy}</p></div></div>}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-xl border bg-card p-3"><p className="font-display text-lg font-semibold">{value}</p><p className="text-muted-foreground">{label}</p></div>}
