import { useMemo, useState } from "react";
import { BedDouble, BookHeart, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Compass, GitCompareArrows, MapPinned, Plane, Plus, ReceiptText, RotateCcw, Users, Wallet, WifiOff } from "lucide-react";
import { useLocale } from "@/lib/locale";

const STEPS = ["route", "bookings", "compare", "plan", "discover", "costs", "journal", "offline"] as const;
type Step = (typeof STEPS)[number];

export function LandingDemo({ expanded = false }: { expanded?: boolean }) {
  const { text, locale } = useLocale();
  const [step, setStep] = useState<Step>("route");
  const [routeChanged, setRouteChanged] = useState(false);
  const [bookingAdded, setBookingAdded] = useState(false);
  const [choice, setChoice] = useState<number>();
  const [selectedDay, setSelectedDay] = useState(0);
  const [packed, setPacked] = useState(false);
  const [savedPlace, setSavedPlace] = useState(false);
  const [expenseAdded, setExpenseAdded] = useState(false);
  const [settled, setSettled] = useState(false);
  const [memoryTitle, setMemoryTitle] = useState("");
  const [memorySaved, setMemorySaved] = useState(false);
  const [sharedMemory, setSharedMemory] = useState(false);
  const [offlineSaved, setOfflineSaved] = useState(false);
  const index = STEPS.indexOf(step);
  const money = (value: number) => new Intl.NumberFormat(locale, { style: "currency", currency: "EUR" }).format(value);
  const labels = useMemo(() => ({ route: text("Route", "Route"), bookings: text("Boekingen", "Bookings"), compare: text("Vergelijken", "Compare"), plan: text("Dagplanning", "Itinerary"), discover: text("Ontdekken", "Discover"), costs: text("Kosten", "Expenses"), journal: text("Dagboek", "Journal"), offline: text("Offline", "Offline") }), [text]);
  const completed: Record<Step, boolean> = { route: routeChanged, bookings: bookingAdded, compare: choice !== undefined, plan: packed, discover: savedPlace, costs: expenseAdded && settled, journal: memorySaved, offline: offlineSaved };
  const completedCount = STEPS.filter((id) => completed[id]).length;
  function reset() { setStep("route"); setRouteChanged(false); setBookingAdded(false); setChoice(undefined); setSelectedDay(0); setPacked(false); setSavedPlace(false); setExpenseAdded(false); setSettled(false); setMemoryTitle(""); setMemorySaved(false); setSharedMemory(false); setOfflineSaved(false); }

  return <div className={`overflow-hidden rounded-[1.75rem] border border-primary/20 bg-background shadow-2xl shadow-primary/10 ${expanded ? "mx-auto max-w-6xl" : ""}`}>
    <div className="flex flex-wrap items-center justify-between gap-4 border-b bg-muted/30 px-5 py-4"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-primary">{text("Begeleide oefenreis", "Guided practice trip")}</p><h2 className="mt-1 font-display text-xl font-semibold">Noordlichtavontuur</h2><p className="mt-1 text-xs text-muted-foreground"><Users className="mr-1 inline size-3"/>Noor & Sam · 14 {text("dagen", "days")} · 10 stops</p></div><div className="min-w-48 flex-1 sm:max-w-xs"><div className="flex justify-between text-xs"><span>{text("Jouw voortgang", "Your progress")}</span><strong>{completedCount}/{STEPS.length}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${completedCount / STEPS.length * 100}%` }} /></div></div><button type="button" onClick={reset} className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><RotateCcw className="size-3.5" />{text("Opnieuw", "Reset")}</button></div>
    <div className={`grid ${expanded ? "lg:grid-cols-[14rem_1fr]" : ""}`}>
      <nav className={`gap-1 border-b bg-muted/15 p-3 ${expanded ? "grid grid-cols-2 sm:grid-cols-4 lg:block lg:border-b-0 lg:border-r" : "grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8"}`} aria-label={text("Demo-onderdelen", "Demo sections")}>{STEPS.map((id, position) => <button key={id} type="button" onClick={() => setStep(id)} aria-current={step === id ? "step" : undefined} className={`flex min-w-0 items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-medium transition ${step === id ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><span className={`grid size-5 shrink-0 place-items-center rounded-full border ${completed[id] ? "border-emerald-500 bg-emerald-500 text-white" : "border-current/30"}`}>{completed[id] ? <Check className="size-3" /> : position + 1}</span><span className="truncate">{labels[id]}</span></button>)}</nav>
      <div className={`space-y-4 p-4 sm:p-6 ${expanded ? "min-h-[38rem]" : "min-h-[29rem]"}`}><Guide done={completed[step]} title={guide(step, text)[0]} body={guide(step, text)[1]} />
        {step === "route" && <section className="space-y-4"><Header icon={MapPinned} title={text("Zet de hele reis op de kaart", "Map the complete trip")} copy={text("De route, afstanden en overnachtingsplaatsen blijven in één volgorde bij elkaar.", "Keep the route, distances and overnight stops together in one order.")} /><div className="relative h-52 overflow-hidden rounded-2xl bg-[#082f2c] sm:h-64"><div className="absolute inset-0 opacity-20" style={{backgroundImage:"radial-gradient(circle at 1px 1px,#99f6e4 1px,transparent 0)",backgroundSize:"24px 24px"}}/><svg viewBox="0 0 600 260" className="relative h-full w-full"><path d={routeChanged ? "M70 215 C150 190 130 80 245 105 S410 115 545 55" : "M70 215 C150 190 130 80 245 105 S340 55 410 115 S500 115 545 55"} fill="none" stroke="#5eead4" strokeWidth="4" strokeDasharray="9 8"/>{[[70,215,"Amsterdam"],[245,105,"Stockholm"],[410,115,"Kiruna"],[545,55,"Lofoten"]].map(([x,y,name],i)=><g key={String(name)}><circle cx={Number(x)} cy={Number(y)} r="13" fill="#0f766e" stroke="#99f6e4" strokeWidth="3"/><text x={Number(x)+(i===3?-68:18)} y={Number(y)-15} fill="white" fontSize="13">{name}</text></g>)}</svg></div><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><div className="grid grid-cols-3 gap-2 text-center text-xs"><Stat value="10" label={text("stops","stops")}/><Stat value="14" label={text("dagen","days")}/><Stat value={routeChanged ? "2.610 km" : "2.840 km"} label={text("route","route")}/></div><Action onClick={()=>setRouteChanged(true)} disabled={routeChanged}>{routeChanged ? text("Route aangepast", "Route updated") : text("Korter voorstel toepassen", "Apply shorter proposal")}</Action></div></section>}
        {step === "bookings" && <section className="space-y-4"><Header icon={Plane} title={text("Alle bevestigingen op hun plek", "Every confirmation in its place")} copy={text("Vlucht, verblijf en vervoer staan direct naast de dagplanning.", "Flights, stays and transport sit directly beside the itinerary.")} /><div className="space-y-2"><Row icon={Plane} title="KL1217 · Amsterdam → Stockholm" meta="8 dec · 08:45"/><Row icon={BedDouble} title="Arctic City Suite · Rovaniemi" meta="9–12 dec"/><Row icon={ReceiptText} title={text("Huurauto · Luleå Airport","Rental car · Luleå Airport")} meta="8–22 dec"/>{bookingAdded&&<Row icon={CalendarDays} title={text("Noorderlichttour","Northern lights tour")} meta="15 dec · 18:45"/>}</div><button type="button" onClick={()=>setBookingAdded(true)} disabled={bookingAdded} className="flex w-full items-center justify-center gap-2 rounded-xl border p-3 text-sm font-semibold hover:border-primary disabled:opacity-60"><Plus className="size-4"/>{bookingAdded?text("Activiteit toegevoegd","Activity added"):text("Voorbeeldactiviteit toevoegen","Add sample activity")}</button></section>}
        {step === "compare" && <section className="space-y-4"><Header icon={GitCompareArrows} title={text("Vergelijk voordat je boekt", "Compare before you book")} copy={text("Bekijk volledige prijs, voorwaarden en groepsstemmen naast elkaar.", "Review total price, conditions and group votes side by side.")} /><div className="grid gap-3 sm:grid-cols-2">{[["Aurora Lodge",1290,"3–1",text("Ontbijt inbegrepen","Breakfast included")],["Arctic City Suite",1045,"1–3",text("Gratis annuleren","Free cancellation")]].map(([name,price,votes,condition],i)=><button type="button" key={String(name)} onClick={()=>setChoice(i)} className={`rounded-2xl border p-5 text-left transition ${choice===i?"border-primary bg-primary/10 ring-1 ring-primary":"hover:border-primary/40"}`}><div className="flex justify-between"><BedDouble className="size-5 text-primary"/><span className="text-xs">{votes} {text("stemmen","votes")}</span></div><p className="mt-4 font-display text-lg font-semibold">{name as string}</p><p className="text-sm">{money(Number(price))}</p><p className="mt-2 text-xs text-muted-foreground">{condition as string}</p><p className="mt-4 text-xs font-semibold text-primary">{choice===i?text("Gekozen voor de reis","Selected for the trip"):text("Kies deze kandidaat","Choose this candidate")}</p></button>)}</div></section>}
        {step === "plan" && <section className="space-y-4"><Header icon={CalendarDays} title={text("Iedere dag weet iedereen wat er speelt", "Everyone knows the plan for every day")} copy={text("Wissel van dag en werk samen een taak af.", "Switch days and complete a shared task.")} /><div className="flex flex-wrap gap-2">{[text("Dag 1","Day 1"),text("Dag 5","Day 5"),text("Dag 9","Day 9")].map((label,i)=><button type="button" key={label} onClick={()=>setSelectedDay(i)} className={`rounded-full border px-3 py-2 text-xs ${selectedDay===i?"border-primary bg-primary/10 text-primary":""}`}>{label}</button>)}</div><div className="rounded-2xl border p-5"><p className="text-xs text-muted-foreground">{["Stockholm","Rovaniemi","Lofoten"][selectedDay]}</p><h3 className="mt-1 font-display text-xl font-semibold">{[text("Aankomst en Gamla Stan","Arrival and Gamla Stan"),text("Noorderlicht en sauna","Northern lights and sauna"),text("Langs vissersdorpen","Explore fishing villages")][selectedDay]}</h3><p className="mt-4 text-sm text-muted-foreground">10:30 · {["Arlanda Express","Arctic tour","Reinebringen"][selectedDay]}</p></div><Toggle checked={packed} onClick={()=>setPacked(!packed)} label={text("Warme handschoenen ingepakt","Warm gloves packed")} value={packed?text("Klaar","Done"):text("Nog doen","To do")}/></section>}
        {step === "discover" && <section className="space-y-4"><Header icon={Compass} title={text("Vind wat bij de route past", "Find what fits the route")} copy={text("GlobeTrotr koppelt ontbrekende nachten en plekken aan de routepositie van die dag.", "GlobeTrotr connects missing nights and places to that day's route position.")} /><div className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4"><strong className="text-sm">{text("Nog 1 nacht zonder verblijf", "1 night still needs accommodation")}</strong><p className="text-xs text-muted-foreground">16–17 december · Rovaniemi</p></div>{[["Arktikum","1,2 km",text("Museum","Museum")],["Café & Bar 21","650 m",text("Restaurant","Restaurant")]].map(([name,distance,type],i)=><button key={String(name)} type="button" onClick={()=>i===0&&setSavedPlace(true)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left ${savedPlace&&i===0?"border-primary bg-primary/10":"hover:border-primary/40"}`}><MapPinned className="size-5 text-primary"/><span><strong className="block">{name as string}</strong><span className="text-xs text-muted-foreground">{distance as string} · {type as string}</span></span>{i===0&&<span className="ml-auto text-xs font-semibold text-primary">{savedPlace?text("In planning","In itinerary"):text("Toevoegen","Add")}</span>}</button>)}</section>}
        {step === "costs" && <section className="space-y-4"><Header icon={Wallet} title={text("Eerlijk verrekenen zonder rekenwerk", "Settle fairly without spreadsheets")} copy={text("Voeg een uitgave toe en rond daarna de voorgestelde terugbetaling af.", "Add an expense and then complete the suggested repayment.")} /><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-primary/10 p-5"><p className="text-xs">{text("Totaal uitgegeven","Total spent")}</p><p className="font-display text-3xl font-semibold">{money(expenseAdded?5308:5248)}</p></div><button type="button" onClick={()=>setExpenseAdded(true)} disabled={expenseAdded} className="rounded-2xl border p-5 text-left hover:border-primary disabled:opacity-60"><Plus className="size-5 text-primary"/><strong className="mt-2 block">{expenseAdded?text("Diner toegevoegd","Dinner added"):text("Diner van €60 toevoegen","Add €60 dinner")}</strong><span className="text-xs text-muted-foreground">{text("Betaald door Noor · gedeeld","Paid by Noor · shared")}</span></button></div><div className={`rounded-2xl border p-4 ${settled?"border-emerald-500/30 bg-emerald-500/10":""}`}><strong>{settled?text("Helemaal verrekend","Fully settled"):"Sam → Noor"}</strong><p className="text-sm text-muted-foreground">{settled?text("Iedereen staat weer gelijk.","Everyone is balanced again."):money(expenseAdded?348:318)}</p><Action onClick={()=>setSettled(true)} disabled={!expenseAdded||settled}>{text("Markeer als betaald","Mark as paid")}</Action></div></section>}
        {step === "journal" && <section className="space-y-4"><Header icon={BookHeart} title={text("Bewaar meer dan alleen de planning", "Keep more than the itinerary")} copy={text("Schrijf zelf een titel, bewaar de herinnering en bepaal daarna de zichtbaarheid.", "Write a title, save the memory and then choose its visibility.")} /><div className="overflow-hidden rounded-2xl border"><div className="h-36 bg-gradient-to-br from-cyan-950 via-sky-700 to-amber-200"/><div className="space-y-3 p-4"><p className="text-xs text-muted-foreground">15 december · Rovaniemi · ★★★★★</p><input value={memoryTitle} onChange={(e)=>{setMemoryTitle(e.target.value);setMemorySaved(false)}} placeholder={text("Geef deze herinnering een titel…","Give this memory a title…")} className="w-full rounded-xl border bg-background px-3 py-2 font-display text-lg font-semibold"/><p className="text-sm text-muted-foreground">{text("Na uren wachten kleurde ineens de hele lucht groen. Een moment om nooit te vergeten.","After hours of waiting, the entire sky suddenly turned green. A moment never to forget.")}</p><Action onClick={()=>setMemorySaved(true)} disabled={!memoryTitle.trim()||memorySaved}>{memorySaved?text("Herinnering opgeslagen","Memory saved"):text("Herinnering bewaren","Save memory")}</Action></div></div><Toggle checked={sharedMemory} disabled={!memorySaved} onClick={()=>setSharedMemory(!sharedMemory)} label={text("In openbare reisterugblik tonen","Show in public trip story")} value={sharedMemory?text("Openbaar","Public"):text("Reisleden","Trip members")}/></section>}
        {step === "offline" && <section className="space-y-4"><Header icon={WifiOff} title={text("Je reis bij de hand zonder bereik", "Keep your trip available without reception")} copy={text("Kies bewust wat op dit apparaat beschikbaar blijft.", "Deliberately choose what remains available on this device.")} /><div className="rounded-2xl border bg-muted/20 p-5"><div className="flex justify-between"><div><p className="text-xs">{text("Dinsdag 15 december","Tuesday 15 December")}</p><h3 className="font-display text-xl font-semibold">Rovaniemi</h3></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${offlineSaved?"bg-emerald-500/10 text-emerald-700":"bg-muted"}`}>{offlineSaved?text("Op apparaat","On device"):text("Online","Online")}</span></div><div className="mt-4 space-y-2 text-sm"><p className="rounded-xl bg-background p-3">09:30 · {text("Sneeuwschoenwandeling","Snowshoe hike")}</p><p className="rounded-xl bg-background p-3"><BookHeart className="mr-2 inline size-4 text-primary"/>{text("Herinnering + 1 gekozen foto","Memory + 1 selected photo")}</p></div><Action onClick={()=>setOfflineSaved(true)} disabled={offlineSaved}>{offlineSaved?text("Offline pakket gereed · 3,4 MB","Offline pack ready · 3.4 MB"):text("Bewaar voor offline gebruik","Save for offline use")}</Action></div><p className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-muted-foreground">{text("Boekingscodes, documenten en bestaande bedragen blijven buiten het pakket. Wijzigingen wachten zichtbaar op synchronisatie.","Booking references, documents and existing amounts stay outside the pack. Changes visibly wait for synchronisation.")}</p></section>}
      </div>
    </div>
    <div className="flex items-center justify-between gap-3 border-t bg-muted/20 px-5 py-3"><button type="button" disabled={index===0} onClick={()=>setStep(STEPS[index-1]!)} className="flex items-center gap-1 text-xs font-semibold disabled:invisible"><ChevronLeft className="size-4"/>{text("Vorige","Previous")}</button><p className="hidden text-[11px] text-muted-foreground sm:block">{text("Veilige voorbeelddata · niets wordt opgeslagen", "Safe sample data · nothing is saved")}</p>{index<STEPS.length-1?<button type="button" onClick={()=>setStep(STEPS[index+1]!)} className="flex items-center gap-1 text-xs font-semibold text-primary">{completed[step]?text("Volgende stap","Next step"):text("Sla over","Skip")}<ChevronRight className="size-4"/></button>:<button type="button" onClick={reset} className="flex items-center gap-1 text-xs font-semibold text-primary">{text("Demo opnieuw","Restart demo")}<RotateCcw className="size-4"/></button>}</div>
  </div>;
}

function guide(step: Step, text: (nl: string, en: string) => string): [string,string] { const guides: Record<Step,[string,string]> = { route:[text("Opdracht: verbeter de route","Task: improve the route"),text("Pas het kortere routevoorstel toe en zie afstand en lijn veranderen.","Apply the shorter route proposal and watch the distance and line change.")], bookings:[text("Opdracht: voeg een activiteit toe","Task: add an activity"),text("Voeg de noorderlichttour toe aan de bestaande boekingen.","Add the northern lights tour to the existing bookings.")], compare:[text("Opdracht: maak een groepskeuze","Task: make a group choice"),text("Vergelijk prijs, voorwaarden en stemmen en kies één verblijf.","Compare price, conditions and votes and choose one stay.")], plan:[text("Opdracht: werk samen aan de dag","Task: work on the day together"),text("Bekijk verschillende dagen en vink de gedeelde paktaak af.","Explore different days and complete the shared packing task.")], discover:[text("Opdracht: ontdek iets rond de route","Task: discover something along the route"),text("Bekijk de ontbrekende nacht en voeg Arktikum aan de planning toe.","Review the missing night and add Arktikum to the itinerary.")], costs:[text("Opdracht: voeg toe en verreken","Task: add and settle"),text("Voeg het diner toe en rond de voorgestelde betaling af.","Add the dinner and complete the suggested payment.")], journal:[text("Opdracht: leg een herinnering vast","Task: capture a memory"),text("Schrijf een titel, bewaar de herinnering en probeer de zichtbaarheid.","Write a title, save the memory and try its visibility setting.")], offline:[text("Opdracht: bereid je voor op geen bereik","Task: prepare for no reception"),text("Bewaar de dagplanning en gekozen dagboekfoto lokaal op dit apparaat.","Save the itinerary and selected journal photo locally on this device.")] }; return guides[step]; }
function Guide({done,title,body}:{done:boolean;title:string;body:string}) { return <div className={`flex gap-3 rounded-2xl border p-4 ${done?"border-emerald-500/30 bg-emerald-500/10":"border-primary/25 bg-primary/5"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-full ${done?"bg-emerald-500 text-white":"bg-primary text-primary-foreground"}`}>{done?<Check className="size-5"/>:<CircleHelp className="size-5"/>}</span><div><strong className="text-sm">{title}</strong><p className="mt-1 text-xs text-muted-foreground">{done?"✓ "+body:body}</p></div></div>; }
function Header({icon:Icon,title,copy}:{icon:typeof MapPinned;title:string;copy:string}) { return <div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div><h3 className="font-display text-xl font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{copy}</p></div></div>; }
function Stat({value,label}:{value:string;label:string}) { return <div className="rounded-xl border bg-card p-3"><p className="font-display text-lg font-semibold">{value}</p><p className="text-muted-foreground">{label}</p></div>; }
function Action({children,onClick,disabled}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}) { return <button type="button" onClick={onClick} disabled={disabled} className="mt-3 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50">{children}</button>; }
function Row({icon:Icon,title,meta}:{icon:typeof Plane;title:string;meta:string}) { return <article className="flex items-center gap-3 rounded-2xl border p-3.5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground">{meta}</p></div><Check className="ml-auto size-4 text-emerald-500"/></article>; }
function Toggle({checked,onClick,label,value,disabled}:{checked:boolean;onClick:()=>void;label:string;value:string;disabled?:boolean}) { return <button type="button" disabled={disabled} onClick={onClick} className="flex w-full items-center gap-3 rounded-xl bg-muted/60 p-3 text-sm disabled:opacity-40"><span className={`grid size-5 place-items-center rounded border ${checked?"border-primary bg-primary text-primary-foreground":""}`}>{checked&&<Check className="size-4"/>}</span>{label}<span className="ml-auto text-xs">{value}</span></button>; }
