import { useEffect,useState } from "react";
import { CloudDownload,RefreshCw,Trash2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { clearJournalOfflineTrip,journalOfflineUsage,journalQueue,loadJournalSnapshot,loadOfflinePhoto,pruneOfflinePhotos,removeJournalQueueItem,saveJournalSnapshot,saveOfflinePhoto,type JournalQueueItem,type OfflineJournalEntry } from "@/lib/journal-offline-store";
import { useLocale } from "@/lib/locale";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
type Entry=OfflineJournalEntry&{photoItems:{path:string;url:string}[]};
export function TripJournalOffline({tripId,entries,refetch}:{tripId:string;entries:Entry[];refetch:()=>Promise<unknown>}){
 const{text}=useLocale(),[selected,setSelected]=useState<string[]>([]),[queue,setQueue]=useState<JournalQueueItem[]>([]),[bytes,setBytes]=useState(0),[busy,setBusy]=useState(false),[offlineEntries,setOfflineEntries]=useState<Array<OfflineJournalEntry&{urls:string[]}>>([]);
 async function refresh(){setQueue(await journalQueue(tripId));setBytes(await journalOfflineUsage(tripId));const snapshot=await loadJournalSnapshot(tripId);const loaded=await Promise.all((snapshot?.entries??[]).map(async entry=>{const urls=(await Promise.all(entry.photo_paths.map(path=>loadOfflinePhoto(tripId,path)))).flatMap(blob=>blob?[URL.createObjectURL(blob)]:[]);return{...entry,urls}}));setOfflineEntries(loaded)}
 // refresh deliberately reloads the trip-scoped IndexedDB stores when the trip changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void refresh()},[tripId]);
 useEffect(()=>()=>{offlineEntries.forEach(entry=>entry.urls.forEach(url=>URL.revokeObjectURL(url)))},[offlineEntries]);
 async function cache(){setBusy(true);try{await saveJournalSnapshot(tripId,entries.map(({photoItems,...entry})=>entry));await pruneOfflinePhotos(tripId,selected);for(const entry of entries)for(const photo of entry.photoItems)if(selected.includes(photo.path)&&!await loadOfflinePhoto(tripId,photo.path))await saveOfflinePhoto(tripId,photo.path,photo.url);await refresh();toast.success(text("Dagboek offline bijgewerkt.","Journal updated for offline use."))}catch{toast.error(text("Offline dagboek kon niet worden opgeslagen.","Offline journal could not be saved."))}finally{setBusy(false)}}
 async function clearLocal(){if(!confirm(text("Offline herinneringen, foto's en niet-gesynchroniseerde wijzigingen van deze reis verwijderen?","Remove offline memories, photos and unsynchronised changes for this trip?")))return;setBusy(true);try{await clearJournalOfflineTrip(tripId);setSelected([]);await refresh();toast.success(text("Offline dagboek van dit apparaat verwijderd.","Offline journal removed from this device."))}finally{setBusy(false)}}
 async function sync(){setBusy(true);try{for(const item of queue){if(item.kind==="delete"){const{error}=await(supabase as any).from("trip_journal_entries").delete().eq("id",item.entry.id).eq("trip_uuid",tripId);if(error)throw error}else if(item.kind==="update"){const{photo_paths:_,...payload}=item.entry;const{error}=await(supabase as any).from("trip_journal_entries").update({...payload,updated_at:new Date().toISOString()}).eq("id",item.entry.id).eq("trip_uuid",tripId);if(error)throw error}else{const{error}=await(supabase as any).from("trip_journal_entries").insert({...item.entry,trip_uuid:tripId,photo_paths:[],photo_captions:{}});if(error)throw error;const paths:string[]=[];for(const[index,file]of(item.files??[]).entries()){const extension=file.type==="image/jpeg"?"jpg":file.type.split("/")[1],path=tripId+"/"+item.entry.id+"/"+(index+1)+"-"+crypto.randomUUID()+"."+extension;const upload=await supabase.storage.from("trip-journal").upload(path,file,{contentType:file.type});if(upload.error)throw upload.error;paths.push(path)}if(paths.length){const captions=Object.fromEntries(paths.map((path,index)=>[path,item.entry.photo_captions["offline:"+index]??""]));const sizes=Object.fromEntries(paths.map((path,index)=>[path,item.files?.[index]?.size??0]));const update=await(supabase as any).from("trip_journal_entries").update({photo_paths:paths,photo_captions:captions,photo_sizes:sizes,updated_at:new Date().toISOString()}).eq("id",item.entry.id);if(update.error)throw update.error}}await removeJournalQueueItem(item.id)}await refresh();await refetch();toast.success(text("Offline wijzigingen gesynchroniseerd.","Offline changes synced."))}catch{toast.error(text("Synchronisatie gestopt. De resterende wijzigingen blijven veilig in de wachtrij.","Sync stopped. Remaining changes stay safely queued."))}finally{setBusy(false)}}
 const online=typeof navigator==="undefined"||navigator.onLine;
 return <Card className="surface"><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{text("Offline dagboek","Offline journal")}</strong><p className="text-xs text-muted-foreground">{text("Herinneringen worden lokaal bewaard. Kies alleen de foto's die je echt offline nodig hebt.","Memories are stored locally. Select only the photos you actually need offline.")}</p></div><span className="text-xs">{(bytes/1024/1024).toFixed(1)} MB · {queue.length} {text("in wachtrij","queued")}</span></div><div className="max-h-44 space-y-1 overflow-y-auto">{entries.flatMap(entry=>entry.photoItems.map(photo=><label key={photo.path} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={selected.includes(photo.path)} onChange={e=>setSelected(e.target.checked?[...selected,photo.path]:selected.filter(path=>path!==photo.path))}/><span className="truncate">{entry.title} · {entry.photo_captions[photo.path]||text("foto zonder bijschrift","photo without caption")}</span></label>))}</div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>void cache()}><CloudDownload className="size-4"/>{text("Offline bewaren","Save offline")}</Button>{queue.length>0&&<Button disabled={busy||!online} onClick={()=>void sync()}><RefreshCw className="size-4"/>{text("Wachtrij synchroniseren","Sync queue")}</Button>}</div>{!online&&offlineEntries.length>0&&<div className="space-y-3 border-t pt-3">{offlineEntries.map(entry=><article key={entry.id} className="rounded-xl bg-muted/30 p-3"><small>{entry.entry_date}{entry.location_name?" · "+entry.location_name:""}</small><strong className="block">{entry.title}</strong><p className="whitespace-pre-wrap text-sm">{entry.body}</p>{entry.urls.length>0&&<div className="mt-2 flex gap-2">{entry.urls.map(url=><img key={url} src={url} alt="" className="size-20 rounded-lg object-cover"/>)}</div>}</article>)}</div>}</CardContent></Card>
}







