import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { BookHeart, Camera, ChevronLeft, ChevronRight, Grid2X2, Lightbulb, List, Map, MapPin, Pencil, Star, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Stop } from "@/lib/types";
import { useLocale } from "@/lib/locale";
import { useAuth } from "@/lib/auth";
import TripMap, { type TripMapPoint } from "@/components/TripMap";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { journalSuggestions } from "@/lib/journal-suggestions";
import { clearJournalDraft, journalDraftBytes, loadJournalDraft, saveJournalDraft } from "@/lib/journal-offline";

type Visibility = "private" | "members" | "public";
type View = "timeline" | "gallery" | "map";
type Entry = { id: string; author_id: string; entry_date: string; title: string; body: string; location_name: string | null; rating: number | null; visibility: Visibility; photo_path: string | null; photo_paths: string[] | null; photo_captions: Record<string, string> | null; photoItems: { path: string; url: string }[]; photoUrls: string[]; authorName?: string };
const allowed = ["image/jpeg", "image/png", "image/webp"];
const maxPhotos = 8;
const maxPhotoBytes = 5 * 1024 * 1024;

export function TripJournal({ tripId, start, end, editable, stops }: { tripId: string; start: string; end: string; editable: boolean; stops: Stop[] }) {
  const { text, locale } = useLocale();
  const { user } = useAuth();
  const db = supabase as any;
  const [date, setDate] = useState(start), [title, setTitle] = useState(""), [body, setBody] = useState(""), [location, setLocation] = useState("");
  const [rating, setRating] = useState(5), [visibility, setVisibility] = useState<Visibility>("members"), [photos, setPhotos] = useState<File[]>([]);
  const [busy, setBusy] = useState(false), [view, setView] = useState<View>("timeline"), [filter, setFilter] = useState("all");
  const [draftBytes, setDraftBytes] = useState(0);
  const [editing, setEditing] = useState<Entry>(), [editingPhotos, setEditingPhotos] = useState<File[]>([]), [editingReplacements, setEditingReplacements] = useState<Record<string, File>>({}), [uploadStates, setUploadStates] = useState<Record<string, "uploading" | "done" | "error">>({}), [lightbox, setLightbox] = useState<{ urls: string[]; captions: string[]; index: number }>();
  const query = useQuery({ queryKey: ["trip-journal", tripId], queryFn: async () => {
    const { data, error } = await db.from("trip_journal_entries").select("id,author_id,entry_date,title,body,location_name,rating,visibility,photo_path,photo_paths,photo_captions").eq("trip_uuid", tripId).order("entry_date", { ascending: false }).order("created_at", { ascending: false });
    if (error) throw error;
    const raw = (data ?? []) as Entry[];
    const { data: members } = await db.from("trip_members").select("user_id,name").eq("trip_uuid", tripId).not("user_id", "is", null);
    const names = new globalThis.Map<string, string>((members ?? []).map((member: { user_id: string; name: string }) => [member.user_id, member.name]));
    return Promise.all(raw.map(async (entry) => {
      const paths = [...new Set([...(entry.photo_paths ?? []), ...(entry.photo_path ? [entry.photo_path] : [])])];
      const signed = paths.length ? await supabase.storage.from("trip-journal").createSignedUrls(paths, 900) : { data: [] };
      const photoItems = paths.flatMap((path, index) => signed.data?.[index]?.signedUrl ? [{ path, url: signed.data[index]!.signedUrl! }] : []);
      return { ...entry, authorName: names.get(entry.author_id) || undefined, photoItems, photoUrls: photoItems.map((item) => item.url) };
    }));
  }, retry: false });
  const entries = useMemo(() => filter === "all" ? (query.data ?? []) : (query.data ?? []).filter((entry) => entry.location_name === filter), [filter, query.data]);
  const locations = [...new Set((query.data ?? []).map((entry) => entry.location_name).filter(Boolean))] as string[];
  const rated = (query.data ?? []).filter((entry) => entry.rating), average = rated.reduce((total, entry) => total + (entry.rating ?? 0), 0) / Math.max(1, rated.length);
  const photoCount = (query.data ?? []).reduce((total, entry) => total + entry.photoUrls.length, 0);
  const mapPoints = useMemo<TripMapPoint[]>(() => entries.flatMap((entry) => { const stop = stops.find((item) => item.name === entry.location_name); return stop ? [{ id: entry.id, lat: stop.lat, lon: stop.lon, title: entry.title, detail: entry.entry_date, kind: "journal" as const }] : []; }), [entries, stops]);
  const suggestions = useMemo(() => journalSuggestions(start, end, stops, (query.data ?? []).map((entry) => entry.entry_date)), [end, query.data, start, stops]);
  useEffect(() => { const draft = loadJournalDraft(tripId); if (!draft) return; setDate(draft.date); setTitle(draft.title); setBody(draft.body); setLocation(draft.location); setDraftBytes(journalDraftBytes(draft)); }, [tripId]);
  useEffect(() => { if (!title.trim() && !body.trim()) return; const timer = window.setTimeout(() => { const draft = { tripId, date, title, body, location, savedAt: new Date().toISOString() }; saveJournalDraft(draft); setDraftBytes(journalDraftBytes(draft)); }, 400); return () => window.clearTimeout(timer); }, [body, date, location, title, tripId]);

  function choosePhotos(files: FileList | null) {
    const selected = Array.from(files ?? []).slice(0, maxPhotos);
    if (selected.some((file) => !allowed.includes(file.type) || file.size > maxPhotoBytes)) { toast.error(text("Gebruik maximaal acht JPG-, PNG- of WebP-foto's van elk maximaal 5 MB.", "Use up to eight JPG, PNG or WebP photos of no more than 5 MB each.")); return; }
    setPhotos(selected);
  }
  async function add() {
    if (!title.trim() || date < start || date > end) { toast.error(text("Vul een titel en geldige reisdatum in.", "Enter a title and valid trip date.")); return; }
    if (!navigator.onLine) { toast.success(text("Concept offline bewaard. Synchroniseer wanneer je weer online bent.", "Draft saved offline. Sync it when you are back online.")); return; }
    setBusy(true); const id = crypto.randomUUID(), uploaded: string[] = [];
    try {
      const { error: createError } = await db.from("trip_journal_entries").insert({ id, trip_uuid: tripId, entry_date: date, title: title.trim(), body: body.trim(), location_name: location || null, rating, visibility, photo_paths: [], photo_captions: {} });
      if (createError) throw createError;
      for (const [index, photo] of photos.entries()) {
        setUploadStates((current) => ({ ...current, [photoKey(photo)]: "uploading" }));
        const extension = photo.type === "image/jpeg" ? "jpg" : photo.type.split("/")[1], path = `${tripId}/${id}/${index + 1}-${crypto.randomUUID()}.${extension}`;
        const { error } = await supabase.storage.from("trip-journal").upload(path, photo, { contentType: photo.type }); if (error) { setUploadStates((current) => ({ ...current, [photoKey(photo)]: "error" })); throw error; } uploaded.push(path); setUploadStates((current) => ({ ...current, [photoKey(photo)]: "done" }));
      }
      if (uploaded.length) { const { error } = await db.from("trip_journal_entries").update({ photo_paths: uploaded, updated_at: new Date().toISOString() }).eq("id", id).eq("trip_uuid", tripId); if (error) throw error; }
      clearJournalDraft(tripId); setDraftBytes(0); setTitle(""); setBody(""); setPhotos([]); setUploadStates({}); await query.refetch(); toast.success(text("Herinnering toegevoegd.", "Memory added."));
    } catch { if (uploaded.length) await supabase.storage.from("trip-journal").remove(uploaded); await db.from("trip_journal_entries").delete().eq("id", id).eq("trip_uuid", tripId); toast.error(text("Herinnering kon niet worden opgeslagen.", "Memory could not be saved.")); }
    finally { setBusy(false); }
  }
  async function update() {
    if (!editing) return; setBusy(true);
    const original = query.data?.find((entry) => entry.id === editing.id), uploaded: string[] = [];
    try {
      const paths = [...(editing.photo_paths ?? [])], captionDraft = { ...(editing.photo_captions ?? {}) };
      for (const [oldPath, photo] of Object.entries(editingReplacements)) { const index = paths.indexOf(oldPath); if (index < 0) continue; setUploadStates((current) => ({ ...current, [photoKey(photo)]: "uploading" })); const extension = photo.type === "image/jpeg" ? "jpg" : photo.type.split("/")[1], path = `${tripId}/${editing.id}/${index + 1}-${crypto.randomUUID()}.${extension}`; const { error } = await supabase.storage.from("trip-journal").upload(path, photo, { contentType: photo.type }); if (error) { setUploadStates((current) => ({ ...current, [photoKey(photo)]: "error" })); throw error; } paths[index] = path; uploaded.push(path); captionDraft[path] = captionDraft[oldPath] ?? ""; delete captionDraft[oldPath]; setUploadStates((current) => ({ ...current, [photoKey(photo)]: "done" })); }
      for (const [index, photo] of editingPhotos.entries()) { setUploadStates((current) => ({ ...current, [photoKey(photo)]: "uploading" })); const extension = photo.type === "image/jpeg" ? "jpg" : photo.type.split("/")[1], path = `${tripId}/${editing.id}/${paths.length + index + 1}-${crypto.randomUUID()}.${extension}`; const { error } = await supabase.storage.from("trip-journal").upload(path, photo, { contentType: photo.type }); if (error) { setUploadStates((current) => ({ ...current, [photoKey(photo)]: "error" })); throw error; } paths.push(path); uploaded.push(path); setUploadStates((current) => ({ ...current, [photoKey(photo)]: "done" })); }
      const captions = Object.fromEntries(Object.entries(captionDraft).filter(([path]) => paths.includes(path)));
      const { error } = await db.from("trip_journal_entries").update({ entry_date: editing.entry_date, title: editing.title.trim(), body: editing.body.trim(), location_name: editing.location_name || null, rating: editing.rating, visibility: editing.visibility, photo_paths: paths, photo_captions: captions, updated_at: new Date().toISOString() }).eq("id", editing.id).eq("trip_uuid", tripId); if (error) throw error;
      const removed = (original?.photo_paths ?? []).filter((path) => !paths.includes(path)); if (removed.length) await supabase.storage.from("trip-journal").remove(removed);
      setEditing(undefined); setEditingPhotos([]); setEditingReplacements({}); setUploadStates({}); await query.refetch(); toast.success(text("Herinnering bijgewerkt.", "Memory updated."));
    } catch { if (uploaded.length) await supabase.storage.from("trip-journal").remove(uploaded); toast.error(text("Wijzigingen konden niet worden opgeslagen.", "Changes could not be saved.")); } finally { setBusy(false); }
  }
  async function remove(entry: Entry) {
    if (!confirm(text(`${entry.title} verwijderen?`, `Delete ${entry.title}?`))) return; setBusy(true);
    try { const paths = [...new Set([...(entry.photo_paths ?? []), ...(entry.photo_path ? [entry.photo_path] : [])])]; const { error } = await db.from("trip_journal_entries").delete().eq("id", entry.id).eq("trip_uuid", tripId); if (error) throw error; if (paths.length) await supabase.storage.from("trip-journal").remove(paths); await query.refetch(); }
    catch { toast.error(text("Herinnering kon niet worden verwijderd.", "Memory could not be deleted.")); } finally { setBusy(false); }
  }

  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-3"><Stat value={query.data?.length ?? 0} label={text("Herinneringen", "Memories")} /><Stat value={photoCount} label={text("Foto's", "Photos")} /><Stat value={average ? average.toFixed(1) : "—"} label={text("Gemiddelde waardering", "Average rating")} /></div>
    <Card className="surface overflow-hidden"><CardHeader className="border-b bg-gradient-to-br from-primary/10 via-background to-background"><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><BookHeart className="size-5 text-primary" />{text("Reisdagboek", "Travel journal")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{text("Bewaar het verhaal achter je route.", "Keep the story behind your route.")}</p></div><div className="flex flex-wrap gap-2"><ViewButton active={view === "timeline"} onClick={() => setView("timeline")} icon={<List />} label={text("Tijdlijn", "Timeline")} /><ViewButton active={view === "gallery"} onClick={() => setView("gallery")} icon={<Grid2X2 />} label={text("Galerij", "Gallery")} /><ViewButton active={view === "map"} onClick={() => setView("map")} icon={<Map />} label={text("Kaart", "Map")} /></div></div></CardHeader>
      <CardContent className="space-y-5 p-4 sm:p-6">{editable && <>{draftBytes > 0 && <p className="text-xs text-muted-foreground">{text(`Offline concept: ${(draftBytes / 1024).toFixed(1)} KB · wordt na controle gesynchroniseerd`, `Offline draft: ${(draftBytes / 1024).toFixed(1)} KB · synchronised after review`)}</p>}{suggestions.length > 0 && <div className="flex flex-wrap items-center gap-2 rounded-xl border border-dashed p-3 text-sm"><Lightbulb className="size-4 text-primary" /><span className="text-muted-foreground">{text("Nog geen herinnering voor:", "No memory yet for:")}</span>{suggestions.map((suggestion) => <Button key={suggestion.date} size="sm" variant="ghost" onClick={() => { setDate(suggestion.date); setLocation(suggestion.location ?? ""); }}>{suggestion.date}{suggestion.location ? ` · ${suggestion.location}` : ""}</Button>)}</div>}<div className="grid gap-3 rounded-2xl border bg-muted/20 p-4 md:grid-cols-3"><Input aria-label={text("Datum", "Date")} type="date" min={start} max={end} value={date} onChange={(event) => setDate(event.target.value)} /><Select value={location} set={setLocation} options={stops.map((stop) => stop.name)} empty={text("Geen bestemming", "No destination")} /><Visibility value={visibility} set={setVisibility} text={text} /><Input className="md:col-span-3" maxLength={160} placeholder={text("Geef deze herinnering een titel", "Give this memory a title")} value={title} onChange={(event) => setTitle(event.target.value)} /><Textarea className="md:col-span-3" rows={5} maxLength={10000} placeholder={text("Wat gebeurde er, wat voelde bijzonder en wat wil je later nog weten?", "What happened, what felt special and what would you like to remember?")} value={body} onChange={(event) => setBody(event.target.value)} /><label className="flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-md border bg-background px-3 text-sm"><Camera className="size-4" />{photos.length ? text(`${photos.length} foto('s) gekozen`, `${photos.length} photo(s) selected`) : text("Foto's kiezen", "Choose photos")}<input className="sr-only" type="file" multiple accept={allowed.join(",")} onChange={(event) => choosePhotos(event.target.files)} /></label><Rating value={rating} set={setRating} /><Button disabled={busy || !title.trim()} onClick={() => void add()}>{text("Herinnering bewaren", "Save memory")}</Button>{photos.length > 0 && <div className="flex flex-wrap gap-2 md:col-span-3">{photos.map((photo, index) => <span key={`${photo.name}-${index}`} className="rounded-full bg-muted px-3 py-1 text-xs">{photo.name}{uploadStates[photoKey(photo)] ? ` · ${uploadLabel(uploadStates[photoKey(photo)]!, text)}` : ""}</span>)}</div>}</div></>}
        <div className="flex flex-wrap items-center justify-between gap-3">{locations.length > 0 ? <Select value={filter} set={setFilter} options={locations} empty={text("Alle bestemmingen", "All destinations")} emptyValue="all" /> : <span />}<span className="text-xs text-muted-foreground">{text(`${entries.length} herinnering(en)`, `${entries.length} memory/memories`)}</span></div>
        {query.isError ? <p>{text("Voer migratie 1800 uit.", "Run migration 1800.")}</p> : view === "map" ? <div className="space-y-3"><TripMap stops={stops} points={mapPoints} /><p className="text-xs text-muted-foreground">{text("Alleen herinneringen die aan een routeplaats zijn gekoppeld verschijnen op de kaart.", "Only memories linked to a route stop appear on the map.")}</p></div> : entries.length ? <div className={view === "gallery" ? "grid gap-4 sm:grid-cols-2 lg:grid-cols-3" : "relative space-y-5 before:absolute before:bottom-4 before:left-[11px] before:top-4 before:w-px before:bg-border sm:before:left-[19px]"}>{entries.map((entry) => <EntryCard key={entry.id} entry={entry} gallery={view === "gallery"} editable={editable && entry.author_id === user?.id} locale={locale} text={text} edit={() => { setEditing({ ...entry, photo_paths: entry.photoItems.map((item) => item.path) }); setEditingPhotos([]); setEditingReplacements({}); setUploadStates({}); }} remove={() => void remove(entry)} openPhotos={(index) => setLightbox({ urls: entry.photoUrls, captions: entry.photoItems.map((item) => entry.photo_captions?.[item.path] ?? ""), index })} />)}</div> : <p className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">{text("Nog geen herinneringen. Begin met het moment dat deze reis bijzonder maakte.", "No memories yet. Start with the moment that made this trip special.")}</p>}
      </CardContent></Card>
    <Dialog open={!!editing} onOpenChange={(open) => { if (!open) { setEditing(undefined); setEditingPhotos([]); setEditingReplacements({}); } }}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{text("Herinnering bewerken", "Edit memory")}</DialogTitle></DialogHeader>{editing && <><Input type="date" min={start} max={end} value={editing.entry_date} onChange={(event) => setEditing({ ...editing, entry_date: event.target.value })} /><Select value={editing.location_name ?? ""} set={(value) => setEditing({ ...editing, location_name: value || null })} options={stops.map((stop) => stop.name)} empty={text("Geen bestemming", "No destination")} /><Input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} /><Textarea rows={7} value={editing.body} onChange={(event) => setEditing({ ...editing, body: event.target.value })} /><Rating value={editing.rating ?? 5} set={(value) => setEditing({ ...editing, rating: value })} /><Visibility value={editing.visibility} set={(value) => setEditing({ ...editing, visibility: value })} text={text} /><PhotoManager entry={editing} setEntry={setEditing} queued={editingPhotos} setQueued={setEditingPhotos} replacements={editingReplacements} setReplacements={setEditingReplacements} uploadStates={uploadStates} text={text} /><DialogFooter><Button variant="outline" onClick={() => { setEditing(undefined); setEditingPhotos([]); setEditingReplacements({}); }}>{text("Annuleren", "Cancel")}</Button><Button disabled={busy || !editing.title.trim()} onClick={() => void update()}>{text("Opslaan", "Save")}</Button></DialogFooter></>}</DialogContent></Dialog>
    <PhotoViewer state={lightbox} set={setLightbox} text={text} />
  </div>;
}

function PhotoManager({ entry, setEntry, queued, setQueued, replacements, setReplacements, uploadStates, text }: { entry: Entry; setEntry: (entry: Entry) => void; queued: File[]; setQueued: (files: File[]) => void; replacements: Record<string, File>; setReplacements: (files: Record<string, File>) => void; uploadStates: Record<string, "uploading" | "done" | "error">; text: (nl: string, en: string) => string }) {
  const paths = entry.photo_paths ?? [];
  const urlByPath = new globalThis.Map(entry.photoItems.map((item) => [item.path, item.url]));
  const [dragged, setDragged] = useState<string>();
  function move(index: number, direction: -1 | 1) { const next = [...paths], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setEntry({ ...entry, photo_paths: next }); }
  function remove(path: string) { const next = { ...replacements }; delete next[path]; setReplacements(next); setEntry({ ...entry, photo_paths: paths.filter((item) => item !== path) }); }
  function caption(path: string, value: string) { setEntry({ ...entry, photo_captions: { ...(entry.photo_captions ?? {}), [path]: value.slice(0, 240) } }); }
  function addFiles(files: FileList | null) { const room = maxPhotos - paths.length, selected = Array.from(files ?? []).slice(0, room); if (selected.some((file) => !allowed.includes(file.type) || file.size > maxPhotoBytes)) { toast.error(text("Gebruik JPG, PNG of WebP van maximaal 5 MB.", "Use JPG, PNG or WebP up to 5 MB.")); return; } setQueued([...queued, ...selected].slice(0, room)); }
  function replace(path: string, files: FileList | null) { const file = files?.[0]; if (!file) return; if (!allowed.includes(file.type) || file.size > maxPhotoBytes) { toast.error(text("Gebruik JPG, PNG of WebP van maximaal 5 MB.", "Use JPG, PNG or WebP up to 5 MB.")); return; } setReplacements({ ...replacements, [path]: file }); }
  function drop(target: string) { if (!dragged || dragged === target) return; const next = [...paths], from = next.indexOf(dragged), to = next.indexOf(target); if (from < 0 || to < 0) return; next.splice(to, 0, next.splice(from, 1)[0]!); setEntry({ ...entry, photo_paths: next }); setDragged(undefined); }
  return <section className="space-y-3 rounded-xl border p-3"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm">{text("Foto's beheren", "Manage photos")}</strong><p className="text-xs text-muted-foreground">{text("De eerste foto is de omslag. Wijzigingen gelden na Opslaan.", "The first photo is the cover. Changes apply after Save.")}</p></div><label className={`cursor-pointer rounded-md border px-3 py-2 text-xs ${(paths.length + queued.length) >= maxPhotos ? "pointer-events-none opacity-50" : ""}`}><Camera className="mr-1 inline size-4" />{text("Toevoegen", "Add")}<input className="sr-only" type="file" multiple accept={allowed.join(",")} onChange={(event) => addFiles(event.target.files)} /></label></div>
    {paths.map((path, index) => <div key={path} draggable onDragStart={() => setDragged(path)} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(path)} className="grid cursor-grab gap-2 rounded-lg bg-muted/40 p-2 sm:grid-cols-[5rem_1fr_auto]"><img src={urlByPath.get(path)} alt="" className="h-16 w-20 rounded-md object-cover" /><div><Input maxLength={240} placeholder={text("Bijschrift", "Caption")} value={entry.photo_captions?.[path] ?? ""} onChange={(event) => caption(path, event.target.value)} /><div className="mt-1 flex flex-wrap gap-2 text-xs">{index === 0 && <span className="font-medium text-primary">{text("Omslagfoto", "Cover photo")}</span>}<label className="cursor-pointer underline">{replacements[path] ? text("Vervanging gekozen", "Replacement selected") : text("Foto vervangen", "Replace photo")}<input className="sr-only" type="file" accept={allowed.join(",")} onChange={(event) => replace(path, event.target.files)} /></label>{replacements[path] && uploadStates[photoKey(replacements[path])] && <span>{uploadLabel(uploadStates[photoKey(replacements[path])]!, text)}</span>}</div></div><div className="flex items-center gap-1"><Button type="button" size="icon" variant="ghost" disabled={index === 0} aria-label={text("Naar voren", "Move forward")} onClick={() => move(index, -1)}><ChevronLeft /></Button><Button type="button" size="icon" variant="ghost" disabled={index === paths.length - 1} aria-label={text("Naar achteren", "Move back")} onClick={() => move(index, 1)}><ChevronRight /></Button><Button type="button" size="icon" variant="ghost" aria-label={text("Foto verwijderen", "Delete photo")} onClick={() => remove(path)}><Trash2 /></Button></div></div>)}
    {queued.length > 0 && <div className="flex flex-wrap gap-2">{queued.map((file, index) => <span key={photoKey(file)} className="flex items-center gap-1 rounded-full bg-muted px-3 py-1 text-xs">{file.name}{uploadStates[photoKey(file)] ? ` · ${uploadLabel(uploadStates[photoKey(file)]!, text)}` : ""}<button type="button" aria-label={text("Nieuwe foto verwijderen", "Remove new photo")} onClick={() => setQueued(queued.filter((_, itemIndex) => itemIndex !== index))}><X className="size-3" /></button></span>)}</div>}
  </section>;
}

function photoKey(file: File) { return `${file.name}:${file.size}:${file.lastModified}`; }
function uploadLabel(status: "uploading" | "done" | "error", text: (nl: string, en: string) => string) { return status === "uploading" ? text("uploaden…", "uploading…") : status === "done" ? text("klaar", "done") : text("mislukt", "failed"); }

function EntryCard({ entry, gallery, editable, locale, text, edit, remove, openPhotos }: { entry: Entry; gallery: boolean; editable: boolean; locale: string; text: (nl: string, en: string) => string; edit: () => void; remove: () => void; openPhotos: (index: number) => void }) {
  const formattedDate = new Intl.DateTimeFormat(locale, { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${entry.entry_date}T12:00:00`));
  return <article className={gallery ? "overflow-hidden rounded-2xl border bg-card shadow-sm" : "relative ml-8 overflow-hidden rounded-2xl border bg-card shadow-sm sm:ml-12"}>{!gallery && <span className="absolute -left-[27px] top-6 size-3 rounded-full border-2 border-background bg-primary sm:-left-[37px] sm:size-4" />}{entry.photoUrls.length > 0 ? <PhotoGrid urls={entry.photoUrls} compact={gallery} open={openPhotos} /> : gallery ? <div className="grid aspect-[4/3] place-items-center bg-gradient-to-br from-primary/10 to-muted"><BookHeart className="size-10 text-primary/60" /></div> : null}<div className="p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span className="capitalize">{formattedDate} · {visibilityLabel(entry.visibility, text)}</span>{entry.authorName && <span>{text("Door", "By")} {entry.authorName}</span>}</div><h3 className="mt-1 text-xl font-semibold leading-tight">{entry.title}</h3>{entry.location_name && <p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4" />{entry.location_name}</p>}{entry.rating && <p className="mt-2 text-amber-600" aria-label={`${entry.rating}/5`}>{"★".repeat(entry.rating)}<span className="text-muted-foreground/30">{"☆".repeat(5 - entry.rating)}</span></p>}{entry.body && <p className={`mt-3 whitespace-pre-wrap text-sm leading-6 ${gallery ? "line-clamp-5" : ""}`}>{entry.body}</p>}{editable && <div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={edit}><Pencil className="size-4" />{text("Bewerken", "Edit")}</Button><Button size="icon" variant="ghost" aria-label={text("Herinnering verwijderen", "Delete memory")} onClick={remove}><Trash2 className="size-4" /></Button></div>}</div></article>;
}
function PhotoGrid({ urls, compact, open }: { urls: string[]; compact: boolean; open: (index: number) => void }) { const shown = urls.slice(0, compact ? 1 : 4); return <div className={`grid overflow-hidden bg-muted ${shown.length === 1 ? "grid-cols-1" : "grid-cols-2"}`}>{shown.map((url, index) => <button key={url} type="button" className={`relative ${compact ? "aspect-[4/3]" : shown.length === 3 && index === 0 ? "row-span-2 min-h-64" : "min-h-32"}`} onClick={() => open(index)}><img src={url} alt="" loading="lazy" className="absolute inset-0 size-full object-cover transition-transform hover:scale-[1.02]" />{index === shown.length - 1 && urls.length > shown.length && <span className="absolute inset-0 grid place-items-center bg-black/50 text-lg font-semibold text-white">+{urls.length - shown.length}</span>}</button>)}</div>; }
function PhotoViewer({ state, set, text }: { state?: { urls: string[]; captions: string[]; index: number }; set: (value?: { urls: string[]; captions: string[]; index: number }) => void; text: (nl: string, en: string) => string }) { if (!state) return null; const previous = () => set({ ...state, index: (state.index - 1 + state.urls.length) % state.urls.length }), next = () => set({ ...state, index: (state.index + 1) % state.urls.length }); return <Dialog open onOpenChange={(open) => { if (!open) set(undefined); }}><DialogContent className="max-w-5xl border-0 bg-black p-0 text-white"><DialogTitle className="sr-only">{text("Foto bekijken", "View photo")}</DialogTitle><div className="relative grid min-h-[60vh] place-items-center"><img src={state.urls[state.index]} alt={state.captions[state.index] ?? ""} className="max-h-[85vh] max-w-full object-contain" /><Button className="absolute right-3 top-3" size="icon" variant="secondary" aria-label={text("Sluiten", "Close")} onClick={() => set(undefined)}><X /></Button>{state.urls.length > 1 && <><Button className="absolute left-3" size="icon" variant="secondary" aria-label={text("Vorige foto", "Previous photo")} onClick={previous}><ChevronLeft /></Button><Button className="absolute right-3" size="icon" variant="secondary" aria-label={text("Volgende foto", "Next photo")} onClick={next}><ChevronRight /></Button></>}<div className="absolute bottom-3 max-w-[80%] rounded-xl bg-black/70 px-4 py-2 text-center text-sm">{state.captions[state.index] && <p>{state.captions[state.index]}</p>}<span className="text-xs text-white/70">{state.index + 1} / {state.urls.length}</span></div></div></DialogContent></Dialog>; }
function ViewButton({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: ReactNode; label: string }) { return <Button size="sm" variant={active ? "secondary" : "outline"} onClick={onClick}>{icon}{label}</Button>; }
function Select({ value, set, options, empty, emptyValue = "" }: { value: string; set: (value: string) => void; options: string[]; empty: string; emptyValue?: string }) { return <select className="h-10 max-w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={(event) => set(event.target.value)}><option value={emptyValue}>{empty}</option>{options.map((option) => <option key={option}>{option}</option>)}</select>; }
function Visibility({ value, set, text }: { value: Visibility; set: (value: Visibility) => void; text: (nl: string, en: string) => string }) { return <select className="h-10 rounded-md border bg-background px-3 text-sm" value={value} onChange={(event) => set(event.target.value as Visibility)}><option value="private">{text("Alleen ik", "Only me")}</option><option value="members">{text("Reisgenoten", "Travellers")}</option><option value="public">{text("Gedeelde reisgids", "Shared trip guide")}</option></select>; }
function Rating({ value, set }: { value: number; set: (value: number) => void }) { return <label className="flex min-h-10 items-center gap-2 text-sm"><Star className="size-4 text-amber-500" /><input className="min-w-0 flex-1 accent-amber-500" type="range" min="1" max="5" value={value} onChange={(event) => set(Number(event.target.value))} />{value}/5</label>; }
function Stat({ value, label }: { value: string | number; label: string }) { return <div className="rounded-xl border bg-card p-4"><strong className="text-2xl">{value}</strong><p className="text-xs text-muted-foreground">{label}</p></div>; }
function visibilityLabel(value: Visibility, text: (nl: string, en: string) => string) { return value === "private" ? text("Alleen ik", "Only me") : value === "members" ? text("Reisgenoten", "Travellers") : text("Reisgids", "Trip guide"); }
