import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Copy, Mail, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { createTripBookingMail, getTripBookingMail, reviewTripBookingMail, revokeTripBookingMail } from "@/lib/booking-mail.functions";

type Draft={id:string;subject:string;sender_address:string;booking_type:string;confidence:number;status:string;parsed_data:Record<string,unknown>};
export function TripBookingMail({tripId,text,acceptDraft}:{tripId:string;text:(nl:string,en:string)=>string;acceptDraft:(draft:Draft)=>Promise<void>}){
 const query=useQuery({queryKey:["trip-booking-mail",tripId],queryFn:()=>getTripBookingMail({data:{tripId}}),retry:false});
 const[senders,setSenders]=useState("");const[retentionDays,setRetentionDays]=useState(30);const[busy,setBusy]=useState(false);const[edits,setEdits]=useState<Record<string,Record<string,string>>>({});const address=query.data?.address as any;
 const allowedSendersKey=Array.isArray(address?.allowed_senders)?address.allowed_senders.join(", "):"";
 useEffect(()=>{setSenders(allowedSendersKey);if(address?.retention_days)setRetentionDays(Number(address.retention_days))},[address?.id,allowedSendersKey,address?.retention_days]);
 async function save(){setBusy(true);try{await createTripBookingMail({data:{tripId,retentionDays,allowedSenders:senders.split(",")}});await query.refetch();toast.success(text("Boekingsadres is klaar.","Booking address is ready."))}catch{toast.error(text("Boekingsadres kon niet worden opgeslagen.","Booking address could not be saved."))}finally{setBusy(false)}}
 async function revoke(){if(!confirm(text("Dit adres intrekken? Nieuwe mail wordt niet meer verwerkt.","Revoke this address? New mail will no longer be processed.")))return;setBusy(true);try{await revokeTripBookingMail({data:{tripId}});await query.refetch();toast.success(text("Boekingsadres ingetrokken.","Booking address revoked."))}catch{toast.error(text("Adres kon niet worden ingetrokken.","Address could not be revoked."))}finally{setBusy(false)}}
 async function review(draft:Draft,action:"accepted"|"rejected"){try{if(action==="accepted")await acceptDraft(draft);await reviewTripBookingMail({data:{tripId,draftId:draft.id,action}});await query.refetch();toast.success(action==="accepted"?text("Boeking toegevoegd.","Booking added."):text("Concept afgewezen.","Draft rejected."))}catch{toast.error(text("Concept kon niet worden bijgewerkt.","Draft could not be updated."))}}
 return <div className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Mail className="size-4"/>{text("Boekingen per e-mail","Bookings by email")}</CardTitle></CardHeader><CardContent className="space-y-3">
  <p className="text-sm text-muted-foreground">{text("Stuur bevestigingen naar dit unieke adres. GlobeTrotr maakt alleen een concept; controleer dit voordat je een boeking toevoegt.","Forward confirmations to this unique address. GlobeTrotr only creates a draft; review it before adding a booking.")}</p>
  {address?.active?<div className="flex flex-wrap items-center gap-2"><code className="rounded bg-muted px-3 py-2 text-sm">{address.address}</code><Button variant="outline" size="sm" onClick={()=>navigator.clipboard.writeText(address.address)}><Copy className="mr-2 size-4"/>{text("Kopieren","Copy")}</Button><Badge>{address.corporate_mailboxes?.provisioning_status??"pending"}</Badge><Button variant="destructive" size="sm" disabled={busy} onClick={revoke}>{text("Intrekken","Revoke")}</Button></div>:<Button disabled={busy} onClick={save}>{busy&&<RefreshCw className="mr-2 size-4 animate-spin"/>}{text("Maak boekingsadres","Create booking address")}</Button>}
  <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_10rem_auto]"><label className="space-y-1 text-sm"><span>{text("Toegestane afzenders (optioneel, gescheiden door komma's)","Allowed senders (optional, comma-separated)")}</span><Input value={senders} onChange={e=>setSenders(e.target.value)} placeholder="booking@example.com"/></label><label className="space-y-1 text-sm"><span>{text("Bewaren (dagen)","Retention (days)")}</span><Input type="number" min={1} max={365} value={retentionDays} onChange={e=>setRetentionDays(Number(e.target.value))}/></label><Button className="self-end" variant="outline" disabled={busy} onClick={save}>{text("Opslaan","Save")}</Button></div>
 </CardContent></Card><div className="space-y-3">{(query.data?.drafts??[]).map((draft:any)=>{const values={...(draft.parsed_data??{}),...(edits[draft.id]??{})};const reviewed={...draft,parsed_data:values};return <Card key={draft.id}><CardContent className="space-y-2 pt-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{draft.subject||text("Zonder onderwerp","No subject")}</strong><Badge variant="outline">{draft.booking_type} / {Math.round(Number(draft.confidence)*100)}%</Badge></div><p className="text-xs text-muted-foreground">{draft.sender_address}</p><div className="grid gap-2 text-sm sm:grid-cols-2">{Object.entries(values).map(([key,value])=><label className="space-y-1" key={key}><span className="text-muted-foreground">{key}</span><Input disabled={draft.status!=="pending"||key==="changeKind"} value={String(value)} onChange={event=>setEdits(current=>({...current,[draft.id]:{...(current[draft.id]??{}),[key]:event.target.value}}))}/></label>)}</div>{draft.status==="pending"?<div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>review(reviewed,"accepted")}>{text("Als boeking toevoegen","Add as booking")}</Button><Button size="sm" variant="outline" onClick={()=>review(draft,"rejected")}>{text("Afwijzen","Reject")}</Button></div>:<Badge>{draft.status}</Badge>}</CardContent></Card>})}</div></div>;
}
