/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BekendeProblemenRouteImport } from './routes/bekende-problemen'
import { Route as BetaVoorwaardenRouteImport } from './routes/beta-voorwaarden'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as MogelijkhedenRouteImport } from './routes/mogelijkheden'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as AuthenticatedCorporateAdminRouteImport } from './routes/_authenticated/corporate-admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as ReisTokenTripIdRouteImport } from './routes/reis.$token.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BekendeProblemenRoute = BekendeProblemenRouteImport.update({
  id: '/bekende-problemen',
  path: '/bekende-problemen',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaVoorwaardenRoute = BetaVoorwaardenRouteImport.update({
  id: '/beta-voorwaarden',
  path: '/beta-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const MogelijkhedenRoute = MogelijkhedenRouteImport.update({
  id: '/mogelijkheden',
  path: '/mogelijkheden',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorporateAdminRoute =
  AuthenticatedCorporateAdminRouteImport.update({
    id: '/corporate-admin',
    path: '/corporate-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ReisTokenTripIdRoute = ReisTokenTripIdRouteImport.update({
  id: '/reis/$token/$tripId',
  path: '/reis/$token/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bekende-problemen': typeof BekendeProblemenRoute
  '/beta-voorwaarden': typeof BetaVoorwaardenRoute
  '/changelog': typeof ChangelogRoute
  '/mogelijkheden': typeof MogelijkhedenRoute
  '/privacy': typeof PrivacyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/corporate-admin': typeof AuthenticatedCorporateAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/reis/$token/$tripId': typeof ReisTokenTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bekende-problemen': typeof BekendeProblemenRoute
  '/beta-voorwaarden': typeof BetaVoorwaardenRoute
  '/changelog': typeof ChangelogRoute
  '/mogelijkheden': typeof MogelijkhedenRoute
  '/privacy': typeof PrivacyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/corporate-admin': typeof AuthenticatedCorporateAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/reis/$token/$tripId': typeof ReisTokenTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bekende-problemen': typeof BekendeProblemenRoute
  '/beta-voorwaarden': typeof BetaVoorwaardenRoute
  '/changelog': typeof ChangelogRoute
  '/mogelijkheden': typeof MogelijkhedenRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/corporate-admin': typeof AuthenticatedCorporateAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/reis/$token/$tripId': typeof ReisTokenTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bekende-problemen'
    | '/beta-voorwaarden'
    | '/changelog'
    | '/mogelijkheden'
    | '/privacy'
    | '/account'
    | '/analytics'
    | '/billing'
    | '/branding'
    | '/corporate-admin'
    | '/dashboard'
    | '/team'
    | '/trips/$tripId'
    | '/reis/$token/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bekende-problemen'
    | '/beta-voorwaarden'
    | '/changelog'
    | '/mogelijkheden'
    | '/privacy'
    | '/account'
    | '/analytics'
    | '/billing'
    | '/branding'
    | '/corporate-admin'
    | '/dashboard'
    | '/team'
    | '/trips/$tripId'
    | '/reis/$token/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bekende-problemen'
    | '/beta-voorwaarden'
    | '/changelog'
    | '/mogelijkheden'
    | '/privacy'
    | '/_authenticated/account'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/branding'
    | '/_authenticated/corporate-admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/team'
    | '/_authenticated/trips/$tripId'
    | '/reis/$token/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BekendeProblemenRoute: typeof BekendeProblemenRoute
  BetaVoorwaardenRoute: typeof BetaVoorwaardenRoute
  ChangelogRoute: typeof ChangelogRoute
  MogelijkhedenRoute: typeof MogelijkhedenRoute
  PrivacyRoute: typeof PrivacyRoute
  ReisTokenTripIdRoute: typeof ReisTokenTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bekende-problemen': {
      id: '/bekende-problemen'
      path: '/bekende-problemen'
      fullPath: '/bekende-problemen'
      preLoaderRoute: typeof BekendeProblemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-voorwaarden': {
      id: '/beta-voorwaarden'
      path: '/beta-voorwaarden'
      fullPath: '/beta-voorwaarden'
      preLoaderRoute: typeof BetaVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mogelijkheden': {
      id: '/mogelijkheden'
      path: '/mogelijkheden'
      fullPath: '/mogelijkheden'
      preLoaderRoute: typeof MogelijkhedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corporate-admin': {
      id: '/_authenticated/corporate-admin'
      path: '/corporate-admin'
      fullPath: '/corporate-admin'
      preLoaderRoute: typeof AuthenticatedCorporateAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/reis/$token/$tripId': {
      id: '/reis/$token/$tripId'
      path: '/reis/$token/$tripId'
      fullPath: '/reis/$token/$tripId'
      preLoaderRoute: typeof ReisTokenTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedCorporateAdminRoute: typeof AuthenticatedCorporateAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedCorporateAdminRoute: AuthenticatedCorporateAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BekendeProblemenRoute: BekendeProblemenRoute,
  BetaVoorwaardenRoute: BetaVoorwaardenRoute,
  ChangelogRoute: ChangelogRoute,
  MogelijkhedenRoute: MogelijkhedenRoute,
  PrivacyRoute: PrivacyRoute,
  ReisTokenTripIdRoute: ReisTokenTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
