-- Provider-onafhankelijke e-mailwachtrij. Standaard testmodus: niets wordt verzonden.
-- Uitvoeren na 20260908063000_agency_domains_and_mail.sql.
BEGIN;
CREATE TABLE public.email_delivery_config(id BOOLEAN PRIMARY KEY DEFAULT true CHECK(id),mode TEXT NOT NULL DEFAULT 'test' CHECK(mode IN('test','live')),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL);INSERT INTO public.email_delivery_config(id) VALUES(true);
CREATE TABLE public.email_outbox(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),notification_id UUID NOT NULL UNIQUE REFERENCES public.notifications(id) ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,recipient_email TEXT NOT NULL,locale TEXT NOT NULL CHECK(locale IN('nl','en')),template_key TEXT NOT NULL,payload JSONB NOT NULL CHECK(jsonb_typeof(payload)='object' AND pg_column_size(payload)<=4096),status TEXT NOT NULL DEFAULT 'held' CHECK(status IN('held','pending','processing','sent','failed','cancelled')),attempts SMALLINT NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 10),available_at TIMESTAMPTZ NOT NULL DEFAULT now(),claimed_at TIMESTAMPTZ,sent_at TIMESTAMPTZ,last_error_code TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE INDEX email_outbox_worker_idx ON public.email_outbox(status,available_at) WHERE status IN('pending','failed');
CREATE OR REPLACE FUNCTION private.queue_notification_email() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE v_email TEXT;v_locale TEXT;v_mode TEXT;BEGIN IF NEW.dismissed_at IS NOT NULL THEN UPDATE public.email_outbox SET status='cancelled',updated_at=now() WHERE notification_id=NEW.id AND status IN('held','pending','failed');RETURN NEW;END IF;IF NEW.kind NOT IN('invitation','trip_access','agency_access','trip_settlement','platform','account') THEN RETURN NEW;END IF;SELECT email INTO v_email FROM auth.users WHERE id=NEW.user_id AND email_confirmed_at IS NOT NULL;IF v_email IS NULL THEN RETURN NEW;END IF;SELECT CASE WHEN lower(COALESCE(profile.locale,'')) LIKE 'en%' THEN 'en' ELSE 'nl' END INTO v_locale FROM public.profiles profile WHERE profile.id=NEW.user_id;v_locale:=COALESCE(v_locale,'nl');SELECT mode INTO v_mode FROM public.email_delivery_config WHERE id=true;INSERT INTO public.email_outbox(notification_id,user_id,recipient_email,locale,template_key,payload,status) VALUES(NEW.id,NEW.user_id,lower(v_email),v_locale,NEW.kind,jsonb_build_object('title',left(NEW.title,160),'body',left(NEW.body,1000),'tripId',NEW.trip_uuid),CASE WHEN v_mode='live' THEN 'pending' ELSE 'held' END) ON CONFLICT(notification_id) DO UPDATE SET payload=EXCLUDED.payload,locale=EXCLUDED.locale,updated_at=now(),status=CASE WHEN email_outbox.status IN('sent','processing') THEN email_outbox.status ELSE EXCLUDED.status END;RETURN NEW;END $$;
CREATE TRIGGER queue_notification_email AFTER INSERT OR UPDATE OF title,body,dismissed_at ON public.notifications FOR EACH ROW EXECUTE FUNCTION private.queue_notification_email();
CREATE OR REPLACE FUNCTION public.claim_email_outbox(p_limit INTEGER DEFAULT 25) RETURNS SETOF public.email_outbox LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN IF (SELECT mode FROM public.email_delivery_config WHERE id=true)<>'live' THEN RETURN;END IF;RETURN QUERY UPDATE public.email_outbox o SET status='processing',claimed_at=now(),attempts=attempts+1,updated_at=now() WHERE o.id IN(SELECT q.id FROM public.email_outbox q WHERE q.status IN('pending','failed') AND q.available_at<=now() AND q.attempts<10 ORDER BY q.available_at,q.created_at FOR UPDATE SKIP LOCKED LIMIT LEAST(GREATEST(p_limit,1),100)) RETURNING o.*;END $$;
ALTER TABLE public.email_delivery_config ENABLE ROW LEVEL SECURITY;ALTER TABLE public.email_outbox ENABLE ROW LEVEL SECURITY;REVOKE ALL ON public.email_delivery_config,public.email_outbox FROM PUBLIC,anon,authenticated;GRANT ALL ON public.email_delivery_config,public.email_outbox TO service_role;REVOKE ALL ON FUNCTION private.queue_notification_email(),public.claim_email_outbox(INTEGER) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.claim_email_outbox(INTEGER) TO service_role;COMMIT;
